### ISSUE TITLE
UTXO screen

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#10]

**Comment by Denis-Asipenko** [comment]
does not match the design
![image](https://user-images.githubusercontent.com/45556620/54917692-650c8800-4f0d-11e9-8ccb-df7b35f23636.png)

![image](https://user-images.githubusercontent.com/45556620/54918431-4e673080-4f0f-11e9-9fce-5b6d32adbc83.png)

**Comment by DenisDemyanko** [comment]
@Denis-Asipenko 

Please see this task - https://github.com/BeamMW/ios-wallet/issues/52
also all statuses received from the SDK and match with the desktop application.

https://github.com/BeamMW/beam/blob/08e7a492bd56954001dcd856a4575718443a35d9/ui/viewmodel/utxo_view.cpp (line 56)

**Comment by Denis-Asipenko** [comment]
checked
