### ISSUE TITLE
Settings: Incompatible Node error

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#102]

**Comment by alexandrashelenkova** [comment]
zpl.io/VxL47yX

**Comment by kaminskyelina** [comment]
@alexandrashelenkova - I added a comment in the design, please take a look

**Comment by alexandrashelenkova** [comment]
@kaminskyelina I changed background screen on that design and Sasha answered a question :)

**Comment by Denis-Asipenko** [comment]
@alexandrashelenkova I think we need to solve node or peer and display one option.
![image](https://user-images.githubusercontent.com/45556620/56428217-48bef980-62c7-11e9-8051-c4664d6717a2.png)

**Comment by alexandrashelenkova** [comment]
Let's keep "node", I will update screens in zeplin later

**Comment by Denis-Asipenko** [comment]
checked
