### ISSUE TITLE
Categories for addresses and transactions

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#104]

**Comment by alexandrashelenkova** [comment]
Added categories screens in addresses and settings sections:
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5c9a1124c2d2d2052d550aed
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5cb44498ecae12a09a7d7c72

**Comment by DenisDemyanko** [comment]
@alexandrashelenkova 
Please add categories to this screen - zpl://screen?pid=5c73dc8aa74b4b4085a86a91&sid=5c73e6ed1896bf1a964c4fe4

**Comment by Denis-Asipenko** [comment]
@alexandrashelenkova  Please to add a confirmation window delete the category in design.
@DenisDemyanko When tapping to "delete" button category doesn't delete. And you need to implement a confirmation window delete the category after adding to the design.

**Comment by alexandrashelenkova** [comment]
@Denis-Asipenko @DenisDemyanko design is here zpl.io/b64WelW

**Comment by alexandrashelenkova** [comment]
@Denis-Asipenko @DenisDemyanko also updated this screens with "None" category https://zpl.io/VQvjeeP https://zpl.io/29wW4yl

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/58477412-2341cd00-815c-11e9-803b-b95bc65122ea.png)
![image](https://user-images.githubusercontent.com/45556620/58479331-bf6dd300-8160-11e9-963e-dbfd4b056464.png)

**Comment by Denis-Asipenko** [comment]
Bug: it is possible to create two identical categories
Steps the behaviour to reproduce:
1. Go to settings screen.
2. Create 2 new categories with different names.
3. Change the name of one category to the same name as the second category.
Expected: error: this category name already exists.
Actual: you can save a category with the same name.
Feature: in this way, you can create only two identical categories, if you try to create a third, then an error appears.
![image](https://user-images.githubusercontent.com/45556620/58554324-58fbba00-821f-11e9-8af5-4e0b4af1c903.png)

**Comment by Denis-Asipenko** [comment]
Add dialogue
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5cc51fc8e0ef892d8b1389d9
![image](https://user-images.githubusercontent.com/45556620/58558561-d75d5980-8229-11e9-8f70-01fa12774f3d.png)

**Comment by Denis-Asipenko** [comment]
checked
