### ISSUE TITLE
Clear data screen-Delete all addresses,all contacts,all transaction.

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#107]

**Comment by alexandrashelenkova** [comment]
Decided with Sasha to add that in settings, screens are here
zpl.io/25OMeK8
zpl.io/bzqnAvX
zpl.io/bA7EZ8x

**Comment by Denis-Asipenko** [comment]
Doesn't match the design.
Design:
![image](https://user-images.githubusercontent.com/45556620/56564196-32aa8500-65b6-11e9-8350-1ef38faeac8d.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/56564136-17d81080-65b6-11e9-852a-94cfce2dd85a.png)

**Comment by Denis-Asipenko** [comment]
checked
