### ISSUE TITLE
Link to transactions in blockchain explorer (including switch that allows to "click out" of the app)

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#108]

**Comment by dariatarakanova** [comment]
Design with additional link under kernel ID - https://zpl.io/VDABmrv
When user clicks on link (Open in Block Explorer) display popup with a notice https://zpl.io/bLdPojM and only after choose "Open" Block Explorer open in browser

**Comment by DenisDemyanko** [comment]
Waiting for a new link from Alexander Braginskiy

**Comment by Denis-Asipenko** [comment]
@iscander01 When tapping on a link make redirects to the kernel ID.

**Comment by iscander01** [comment]
@Denis-Asipenko  done

**Comment by Denis-Asipenko** [comment]
checked
