### ISSUE TITLE
Nice sharing of addresses

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#109]

**Comment by dariatarakanova** [comment]
1. Please pay attention on button - now it SHARE ADDRESS. 
2. How it works: 
a) user click on button "share address"
b) the link with information (address, amount, comment) is generating and opens activity view (https://developer.apple.com/design/human-interface-guidelines/ios/views/activity-views/)
с) send link in the way you want (message, telegram, mail etc)
d) When second user gets this link he clicks on it and opens wallet (screen Send) with information that filled in first user (address, amount, comment)

3) Designs are here: 
receive page - https://zpl.io/aBRRzR0
receive-qr page - https://zpl.io/V1OOx1Q

**Comment by Denis-Asipenko** [comment]
b) the link isn't generated. when you sharing an address, then is sent not the reference and simply worded
![image](https://user-images.githubusercontent.com/45556620/57127357-cfc8a300-6d98-11e9-9c29-793ba1a43501.png)

**Comment by sasha-abramovich** [comment]
The design supports many cases such as deep link and branded link generation. For the current task, all we need is to share the address via the system dialog. Deep link and branded links will be opened as separate tasks later on.

**Comment by Denis-Asipenko** [comment]
checked
