### ISSUE TITLE
Transaction hangs in receiving for 2+ days

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/ios-wallet#115]
**Description**
After the weekend I noticed that one of the transactions is hanging in "receiving" status. The app has not been opened during the entire weekend. Looks like this transaction must have been failed in 720 blocks (approx. 12 hours). Logs attached. 
[logs.zip](https://github.com/BeamMW/ios-wallet/files/3078694/logs.zip)

**How to reproduce**
**Pre-conditions**
Wallet A (desktop app, sender) is installed and running. 
Wallet A has some UTXO to send.
Wallet B (mobile app, receiver) is installed and running.

**Steps to reproduce**
1. Send some UTXO from Wallet A to Wallet B.
2. **Act fast now:** When transaction in Wallet B appears in "receiving" status - cancel the transaction in Wallet A while it's still in "waiting for receiver".
3. Check the transaction status in Wallet B in some time.

**Actual:** Hangs in "receiving" forever.
**Expected:** Appears in "expired" status in 720 blocks.

**Comment by DenisDemyanko** [comment]
[wallet.db.zip](https://github.com/BeamMW/ios-wallet/files/3079228/wallet.db.zip)

password: 1

**Comment by kaminskyelina** [comment]
@anatolse @DenisDemyanko what a status of this investigation please?

**Comment by anatolse** [comment]
fixed on master

**Comment by DenisDemyanko** [comment]
please test on masternet build.

**Comment by Denis-Asipenko** [comment]
checked
