### ISSUE TITLE
In progress transaction icons for iOS

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#12]

**Comment by kaminskyelina** [comment]
![image](https://user-images.githubusercontent.com/45590119/53793958-9eb62880-3f37-11e9-9008-5f23ec5fe97f.png)

**Comment by alexandrashelenkova** [comment]
@kaminskyelina what exactly I have to do in this task? All these icons were already in zeplin and exportable zpl.io/VqWLnGl

**Comment by alexandrashelenkova** [comment]
Ah I see it's done already, sorry)

**Comment by Denis-Asipenko** [comment]
checked
