### ISSUE TITLE
Show Kernel ID and not Transaction ID in UTXO details

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#121]
It was decided by Sasha to show Kerner ID and not Transaction ID in UTXO screen

@alexandrashelenkova  please change also in the design, so it will not confuse in future

**Comment by dariatarakanova** [comment]
Design here: https://zpl.io/29wO7Zd

**Comment by dariatarakanova** [comment]
Design here: https://zpl.io/V0Lqvmo

**Comment by Denis-Asipenko** [comment]
checked
