### ISSUE TITLE
Don't show UTXO balance at all in privacy mode

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#122]
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5cc2750ffc3c5d3dab3b3c41
![image](https://user-images.githubusercontent.com/45556620/57126986-9d6a7600-6d97-11e9-9790-03bcf758032f.png)

**Comment by Denis-Asipenko** [comment]
design:
![image](https://user-images.githubusercontent.com/45556620/57127021-b96e1780-6d97-11e9-9b4a-b0b3e01417c5.png)
actual:
![image](https://user-images.githubusercontent.com/45556620/57127042-d1459b80-6d97-11e9-8182-dfc5e9e75b5f.png)

**Comment by Denis-Asipenko** [comment]
checked
