### ISSUE TITLE
The dialog that explains what the "hide amounts" mode is about should be shown only once.

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#129]
![image](https://user-images.githubusercontent.com/44961099/57003107-905e5300-6bee-11e9-904c-f156d8b80deb.png)

**Comment by sasha-abramovich** [comment]
also, the text should say "_until the eye icon is tapped again_"

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/57126855-20d79780-6d97-11e9-89c9-c505051013fb.png)

**Comment by Denis-Asipenko** [comment]
checked
