### ISSUE TITLE
Testnet design for iOS (colours)

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#13]

**Comment by sasha-abramovich** [comment]
can we take the colors from Android/desktop to save time please?

**Comment by alexandrashelenkova** [comment]
Testnet colours are here:
zpl.io/am50LqK
zpl.io/agz0mLN

**Comment by alexandrashelenkova** [comment]
@sasha-abramovich to who I have to assign that task now?

**Comment by Denis-Asipenko** [comment]
checked
