### ISSUE TITLE
Change maximum Send/ Receive value to 262,800,000 Beams

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/ios-wallet#131]
**Description
C**hange maximum value to **262,800,000** Beams in the BEAM fields in the **Send** and **Receive** screens.
Please make sure to take into account the Fee value, e.g. if the fee is 10 groths, than the maximum amount to enter will be reduced accordingly.

**Comment by DenisDemyanko** [comment]
Also user can't input fee, if send value is maximum.
Example: set fee to zero, amount set to maximum.
Expected result: user can't input fee

**Comment by Denis-Asipenko** [comment]
in the line transaction amount it is possible to enter 9 zeros to the decimal point.
![image](https://user-images.githubusercontent.com/45556620/58475074-a14ea580-8155-11e9-9a2a-6ec885b34466.png)
Please implement the same logic of entering the amount on "receive" and "send" screens as on the desktop wallet.

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/58540380-ee885100-8201-11e9-8f43-e066ad9d2b7b.png)

**Comment by Denis-Asipenko** [comment]
сhecked
