### ISSUE TITLE
Add dialogue window on "Confirm seed phase" screen.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/ios-wallet#132]
Add dialogue window on "Confirm seed phase" screen when returning back to previous screen the same as it on Android.
![image](https://user-images.githubusercontent.com/45556620/57138663-f3e9ab80-6dbb-11e9-9b3f-7b59eac6d7c1.png)

**Comment by DenisDemyanko** [comment]
@sasha-abramovich 
@jurijakimuk proposed to change the button text from "Create new phrase" to "Return".
Please confirm or specify your text. Thx!

**Comment by sasha-abramovich** [comment]
Let's call it "GENERATE".

**Comment by sasha-abramovich** [comment]
also, the title text should say "Back to seed phrase", not "return to seed phrase".

FYI: @alexandrashelenkova (all these text can be changed later - if required - please create tasks)

**Comment by Denis-Asipenko** [comment]
checked
