### ISSUE TITLE
Deleting User Data: Change the warning text

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/ios-wallet#133]
**Description**
When a user is asked:
"Are you sure you want to delete all contacts from your device?" This could sound frightening.
I suggest replacing the word "device" with the word "wallet". 
@sasha-abramovich If you agree - please pass the task to the devs. Thank you.

**Screenshot**
![image](https://user-images.githubusercontent.com/41323026/57140724-1500cb00-6dc1-11e9-9432-016fd8713b83.png)

**Link to the design**
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5cb6a194d86e673994b0cfcc

**Comment by sasha-abramovich** [comment]
should be "wallet", not "device" indeed

**Comment by Denis-Asipenko** [comment]
checked
