### ISSUE TITLE
iOS device won't autolock with wallet being active app

### ISSUE THREAD

**Issue by beggsdl** [BeamMW/ios-wallet#135]
Running v2.1.1.3.  I noticed if the Beam wallet is open and the active app, it will not allow the iOS device to auto-lock according to the iOS auto-lock setting.  If the wallet needs to stay open to ensure a tx completes, maybe add a setting to allow the device to auto-lock after x minutes, or to use the iOS auto-lock setting, or maybe after the open tx is complete.  Something to allow the device to auto-lock and be secure.

**Comment by beggsdl** [comment]
I noticed this is now working in the update that just came out.  Thanks

**Comment by Denis-Asipenko** [comment]
checked
