### ISSUE TITLE
Onboarding screens

### ISSUE THREAD

**Issue by DenisDemyanko** [BeamMW/ios-wallet#137]
Creating onboard screens.
Show when the application is launched for the first time.

Example - https://thetool.io/wp-content/uploads/2017/10/mobile-onboarding-process.jpg

**Comment by sasha-abramovich** [comment]
Onboarding screens are required when the product is not very intuitive to use. Do you see this case with our wallet?

**Comment by dariatarakanova** [comment]
already done
