### ISSUE TITLE
Permissions screen

### ISSUE THREAD

**Issue by DenisDemyanko** [BeamMW/ios-wallet#138]
Show a friendly screen before requesting permissions. 

Example: https://camo.githubusercontent.com/cf6a75da9f840e61a98bde3c61b3938bb0ce1f61/68747470733a2f2f64323632696c623531686c7478302e636c6f756466726f6e742e6e65742f6d61782f323030302f312a4e4551796c7054704e4b753441704152664735302d412e6a706567

**Comment by sasha-abramovich** [comment]
this is a very useful and friendly feature!
@DenisDemyanko please enlist all the scenarios where we are asking for the features and reassign to @alexandrashelenkova for design

**Comment by sasha-abramovich** [comment]
@DenisDemyanko following up on this one. if not relevant anymore - let's close
