### ISSUE TITLE
3d touch - quick access to the wallet qr-code

### ISSUE THREAD

**Issue by DenisDemyanko** [BeamMW/ios-wallet#139]
On the address list screen - the user can quickly view the qr-code and other information about the address using 3d touch.

Example (read section Peek) - https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/Adopting3DTouchOniPhone/

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova thoughts? Personally I don't use 3D touch, but lots of users find it helpful. How can we leverage that on the main screen and within the app?

**Comment by dariatarakanova** [comment]
https://zpl.io/2GGeEBr
https://zpl.io/aX3dYQM

@alexandrashelenkova could you please have a look?

**Comment by alexandrashelenkova** [comment]
@dariatarakanova That looks good 👍

**Comment by dariatarakanova** [comment]
@DenisDemyanko you turn =) 

https://zpl.io/2GGeEBr
https://zpl.io/aX3dYQM

**Comment by Denis-Asipenko** [comment]
checked
