### ISSUE TITLE
Add swipe to transaction cells, addresses

### ISSUE THREAD

**Issue by DenisDemyanko** [BeamMW/ios-wallet#140]
Add the ability to quickly delete or edit transactions and addresses using a swipe gesture

Example - https://i.stack.imgur.com/H6oeX.png

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova this idea sounds "natural" to the wallet UX. Thoughts?

**Comment by dariatarakanova** [comment]
Addresses https://zpl.io/2vOGKO7
Transactions https://zpl.io/2vOGKKr

@alexandrashelenkova could you please check designs, thanks a lot!

**Comment by dariatarakanova** [comment]
Splited to 2 separated tasks:

https://github.com/BeamMW/ios-wallet/issues/158
https://github.com/BeamMW/ios-wallet/issues/157
