### ISSUE TITLE
Adding a feedback dialogue.

### ISSUE THREAD

**Issue by DenisDemyanko** [BeamMW/ios-wallet#141]
A user can select an app rating mark.
If it’s positive, then the store is going to open with a possibility to give feedback. If it’s negative, then mail is going to open directed to our address.
The dialogue is going to be displayed every 10th start or with successful getting/sending of the 2nd transactions.

example - https://cdn-images-1.medium.com/max/1200/0*kHtaRGaYqPEAVvo7.png

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova please design

**Comment by dariatarakanova** [comment]
https://zpl.io/29w3Bne 
https://zpl.io/VkpPk75

@alexandrashelenkova please check the designs

**Comment by sasha-abramovich** [comment]
I think the name is misleading. It's about featuring ratings on the settings page.

**Comment by sasha-abramovich** [comment]
and I'm sure we don't need a popup

**Comment by Denis-Asipenko** [comment]
checked
