### ISSUE TITLE
Login / restore screen updates

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#142]
On following screens change restore button to a link:
https://zpl.io/aXP3K3p
https://zpl.io/VKPDEjJ
https://zpl.io/bLPWBl7

Text updates:
https://zpl.io/a3eR9JQ
https://zpl.io/agQPwAA

Rename button:
https://zpl.io/VxLwjyW

**Comment by DenisDemyanko** [comment]
The task will be done when it is possible to restore the wallet
