### ISSUE TITLE
Language settings

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#144]
zpl.io/25OMeK8
zpl.io/25JjNMe
English language should always be on top of the list (even if not selected). By default app should use device language (if supported), if not supported - english.

**Comment by sasha-abramovich** [comment]
before starting this one - let's discuss with @anatolse - to sync the language engine across the platforms

**Comment by sasha-abramovich** [comment]
@DenisDemyanko in case only 1 language is installed in the system - we don't need to show the language switcher in settings.

**Comment by DenisDemyanko** [comment]
in case only 1 language is installed in the system - we don't need to show the language switcher in settings.
