### ISSUE TITLE
fix spelling

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#145]
![image](https://user-images.githubusercontent.com/44961099/57971642-b9d2f900-79ba-11e9-8406-77b7b54149f4.png)

should read “funds AT risk”, instead of IN risk, and “strongly recommend” instead of strictly recommend

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/58481972-26da5180-8166-11e9-88e6-621deed2801b.png)

**Comment by Denis-Asipenko** [comment]
checked
