### ISSUE TITLE
Beam Widget for smartphones

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#146]

**Comment by sasha-abramovich** [comment]
I think widgets are in Android

**Comment by dariatarakanova** [comment]
> I think widgets are in Android

For iOS we can create such widgets as here:
![IMG_2610](https://user-images.githubusercontent.com/47353570/58169842-74544b80-7c9a-11e9-99a7-aff6becf4b36.PNG)
