### ISSUE TITLE
Address detail screen - update design

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#149]
Updated design https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5c9a068896545605b285ee5c

Additional screens
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5c9a06898aaf5905283bdd64
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5cc2e5acd3744f2de543d69b
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5cc51fc8e528ae3da58ab3b7
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5cc51fc8f62b202ce92a9af5
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5cc51fc8e0ef892d8b1389a7
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5cc51fc8e0ef892d8b1389d9
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5cc51fc84a92851016fa21e2
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5cc51fc9f62b202ce92a9b31
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5cc51fc8ff13633dd5e23994
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5ce3f07039f2e51e0118e016

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/58475552-ef17dd80-8156-11e9-9409-4ef2fb96c956.png)
![image](https://user-images.githubusercontent.com/45556620/58475559-f6d78200-8156-11e9-8c77-28e24d562da5.png)

**Comment by Denis-Asipenko** [comment]
Add dialogue
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5cc51fc8e0ef892d8b1389d9
![image](https://user-images.githubusercontent.com/45556620/58558561-d75d5980-8229-11e9-8f70-01fa12774f3d.png)

**Comment by Denis-Asipenko** [comment]
checked
