### ISSUE TITLE
Design side menu

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#150]

**Comment by dariatarakanova** [comment]
https://zpl.io/awJBnjd

**Comment by Denis-Asipenko** [comment]
@alexandrashelenkova @dariatarakanova how incoming and outgoing amounts should be displayed in the "in progress" window?

so
![image](https://user-images.githubusercontent.com/45556620/58536462-50908880-81f9-11e9-8f0d-edff5e9161c2.png)
or
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5cc144e896c2ae2d43231faa
![image](https://user-images.githubusercontent.com/45556620/58537795-4d4acc00-81fc-11e9-9267-6d41c1e1bd10.png)
Please leave only one current version on the layouts to avoid confusion.

**Comment by alexandrashelenkova** [comment]
@Denis-Asipenko Second one is correct, moved first one to "Archive" section.

**Comment by Denis-Asipenko** [comment]
according to the design, the animation should be as follows:

**Comment by Denis-Asipenko** [comment]
checked
