### ISSUE TITLE
Send screen - snackbar for UNDO send tx

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#151]

**Comment by dariatarakanova** [comment]
https://zpl.io/bA79nvO

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/58551482-c7894980-8218-11e9-969e-d2a7562997ed.png)
![image](https://user-images.githubusercontent.com/45556620/58551490-cd7f2a80-8218-11e9-94ca-31e79b871458.png)
now it looks like a hung transaction

**Comment by Denis-Asipenko** [comment]
@DenisDemyanko Crash wallet
Steps the behaviour to reproduce: 
1. Go to Send screen.
2. Send transaction oneself or another wallet
3. On the last second of the timer tap on the UNDO.

**Comment by Denis-Asipenko** [comment]
Transaction is sent after it is UNDO. Also, some transactions get the status "failed".
Steps the behaviour to reproduce:
1. Go to Send screen.
2. Send transaction oneself or another wallet
3. On the last second of the timer tap on the UNDO(several times).
4. To close and open  wallet.
![image](https://user-images.githubusercontent.com/45556620/58941812-37518400-8785-11e9-9758-de10418d441f.png)
Logs are attached
[logs (11).zip](https://github.com/BeamMW/ios-wallet/files/3256249/logs.11.zip)

**Comment by Denis-Asipenko** [comment]
checked
