### ISSUE TITLE
Send / receive screens redesign

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#152]
New version of send/receive screes are here:
send https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5ce239536c73511dec2404fa
receive https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5ce2394739f2e51e01fd8c6f

**Comment by Denis-Asipenko** [comment]
checked
