### ISSUE TITLE
Owner's key

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#153]
Add ability to see and copy/share owner's key in settings. Ask password or fingerprint/face id before showing it. Add alert that showing that key will show all your transactions on other devices where it will be implemented.

**Comment by dariatarakanova** [comment]
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5ced22678930b01d6e7a9403

**Comment by Denis-Asipenko** [comment]
Actual:
![image](https://user-images.githubusercontent.com/45556620/58704567-2be11000-83b5-11e9-940b-59700a3f0539.png)
Design:
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5ced223e5d01801e1cb9f119
![image](https://user-images.githubusercontent.com/45556620/58704602-4915de80-83b5-11e9-9934-c8c608e8361f.png)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/58797749-75299d80-8609-11e9-984c-5291a378a27d.png)

**Comment by Denis-Asipenko** [comment]
checked
