### ISSUE TITLE
Default confirmation

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#155]
Add confirmation setting in settings screen, add statuses for transactions (sending 1/10, receiving 1/10, etc...)
Default should be set to 0.

Please see the design below in comments!

**Comment by sasha-abramovich** [comment]
as a part of this task let's also display the actual confirmations number in transaction details
also, when trying to send a transaction that uses UTXO with less confirmations than the threshold user should receive a warning

**Comment by sasha-abramovich** [comment]
6 confirmations is a good default for the settings.

**Comment by dariatarakanova** [comment]
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5cefec9686ef376f60033c50

**Comment by dariatarakanova** [comment]
1) Add "Minimum confirmations" in Settings screen https://zpl.io/2yGrwqp
![image](https://user-images.githubusercontent.com/47353570/86445636-68e7a680-bd1b-11ea-9384-9529ebf63738.png)


2) "Minimum confirmations" screen https://zpl.io/aRx3ORz
![image](https://user-images.githubusercontent.com/47353570/86445607-5c634e00-bd1b-11ea-8488-976408c42774.png)


3) Add "Confirmation status" to transaction details (example: confirmed) https://zpl.io/VkeXBWv
![image](https://user-images.githubusercontent.com/47353570/86445572-4f465f00-bd1b-11ea-8cf6-c695140be059.png)

4) Add "Confirmation status" to shared transaction details (example: confirming) https://zpl.io/awPeoDM
![image](https://user-images.githubusercontent.com/47353570/86445543-4190d980-bd1b-11ea-8448-24437ef22889.png)

**Comment by AndreyDyakonov** [comment]
Checked
