### ISSUE TITLE
Swipe on transaction list

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#157]
**Main screen** https://zpl.io/2vOGKKr

**Tap on Cancel** - https://zpl.io/bPxz1kk

**Tap on Repeat**:
_Send TX_ - https://zpl.io/amdEkAv.
_Receive TX_ - https://zpl.io/bA70DAn 
As we repeat transaction so amount, comment, address and fee should be already filled but user should be able to edit them if he wants.

**Tap on Delete** - https://zpl.io/VYrdo5p

**UNDO for actions:**
Cancel - https://zpl.io/bWNpXOp
Delete - https://zpl.io/aRxgGRp

**Comment by alexandrashelenkova** [comment]
Already implemented
