### ISSUE TITLE
Swipe to addresses

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#158]
Main screen - https://zpl.io/2vOGKO7

Tap on Delete - https://zpl.io/29wkj7e
Tap on Edit - https://zpl.io/29wW4yl - show different Edit address screen that depends on status (active/expired)

Undo Delete address -= https://zpl.io/Vx0GwAW

**Comment by Denis-Asipenko** [comment]
if you delete an address, there is no additional menu
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5ce69a05c9ef1d1e3731e6c5
![image](https://user-images.githubusercontent.com/45556620/58704837-07d1fe80-83b6-11e9-8094-37eedf31a304.png)

**Comment by Denis-Asipenko** [comment]
checked
