### ISSUE TITLE
Share transaction details

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#159]
Think about what details we can share and what - we can't

**Comment by dariatarakanova** [comment]
https://zpl.io/VOdBzeQ

**Comment by Denis-Asipenko** [comment]
@dariatarakanova  for this we have payment proof
![image](https://user-images.githubusercontent.com/45556620/59101422-9a801980-8931-11e9-899b-74b5c65c12d0.png)

**Comment by dariatarakanova** [comment]
this screen https://zpl.io/VOdBzeQ will be as an image. The same as receipe in mobile banking so I can send this image to other user, right @sasha-abramovich ?

**Comment by dariatarakanova** [comment]
Please notice, this screen should be a picture, not screen in wallet. The picture can be shared in telegram, email, other chats.

**Comment by Denis-Asipenko** [comment]
When a user shares transaction details, the picture should show the status at the time the user decided to share the transaction details. The beam icon should be displayed to the left of the status.

**Comment by Denis-Asipenko** [comment]
design:
![image](https://user-images.githubusercontent.com/45556620/62208704-48db9480-b3a0-11e9-93c0-9a4e9134d08c.png)
actual:
![image](https://user-images.githubusercontent.com/45556620/62208731-5ee95500-b3a0-11e9-8d9a-b2860f6510d8.png)

**Comment by Denis-Asipenko** [comment]
checked
