### ISSUE TITLE
Replace words with icons

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#161]

**Comment by alexandrashelenkova** [comment]
![2019-06-05 09 24 33](https://user-images.githubusercontent.com/7249484/58923814-cd7cae80-8773-11e9-80ca-18b9932a2e87.jpg)

**Comment by dariatarakanova** [comment]
transaction https://zpl.io/2vOGKKr

**Comment by Denis-Asipenko** [comment]
checked
