### ISSUE TITLE
Settings screen - doesn't request the password when disables function.

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#165]
When the user disables the "Ask for password on every sending transaction" need to request a password.

**Comment by Denis-Asipenko** [comment]
@alexandrashelenkova this is already implemented on IOS and Android platforms. Maybe you want a different design, but for now, the confirmation screen looks like this:
![image](https://user-images.githubusercontent.com/45556620/59194598-33ad6b00-8b92-11e9-9d72-40b013afda33.png)

**Comment by dariatarakanova** [comment]
Please change text  "Enter your current password" to "Enter your current password to proceed changes in settings"

**Comment by Denis-Asipenko** [comment]
checked
