### ISSUE TITLE
Show upgrade notification if node protocol version is higher than wallet protocol version

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#166]

**Comment by dariatarakanova** [comment]
https://zpl.io/a7d5GRj

@alexandrashelenkova @sasha-abramovich could you please check the text? and let me know if it is not good. TX

**Comment by sasha-abramovich** [comment]
Moving this back to backlog, not critical for fork and problematic from implementation view. @beam-mw  will check whether this task should be closed.
