### ISSUE TITLE
Fix the text on the send and receive screens

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#167]
The text at the bottom of the BOTH screens should say:

- **For Receiver:** _For the transaction to complete, you should get online during the 12 hours after Beams are sent._ 
- **For Sender:** _For the transaction to complete, the recipient must get online within the next 12 hours and you should get online within 2 hours afterwards._

@alexandrashelenkova please update the text on receive screen in Zeplin.

[
![fullsizeoutput_5386](https://user-images.githubusercontent.com/44961099/59551895-9fd10a00-8faa-11e9-97c4-37e12226a2a4.jpeg)
](url)

**Comment by sasha-abramovich** [comment]
@DenisDemyanko @alexandrashelenkova the text was updated for both Send and Receive screens: please see description

**Comment by Denis-Asipenko** [comment]
checked
