### ISSUE TITLE
Address disappears in Receive flow

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#168]
Scenario:
* Tap "Receive" from the main screen and see the Receive screen
* Tap "Change" - see two addresses (in my fresh wallet I was seeing new address and default address)
* Tap any of these two addresses to select and get back to the main Receive screen
* Assume that the address was selected by mistake and tap "Change" again
* I was seeing only "Default"  address, I think I expect to see both

![fullsizeoutput_5382](https://user-images.githubusercontent.com/44961099/59551915-01917400-8fab-11e9-85e4-ac91cde71236.jpeg)
![fullsizeoutput_5381](https://user-images.githubusercontent.com/44961099/59551916-01917400-8fab-11e9-9b5a-2a9807fffe5d.jpeg)

**Comment by Denis-Asipenko** [comment]
Wallet crashes. 
Steps to reproduce the behaviour:
1.go to "Receive" screen.
2. Tap "Change".
3. Select to address. 
Expected: address selected. 
Actual: Wallet crashes.

**Comment by Denis-Asipenko** [comment]
checked
