### ISSUE TITLE
Is this the best way to show the address on Receive flow?

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#169]
@alexandrashelenkova we have lots of place maybe we could show the address better? (i.e. using all the end-to-end space? or similar to how it was presented near the "Change" button on the previous screen)?

![fullsizeoutput_5382](https://user-images.githubusercontent.com/44961099/59551993-b9bf1c80-8fab-11e9-8748-1a6a1f248e38.jpeg)

**Comment by alexandrashelenkova** [comment]
By now let's use all end-to-end space, but if any address on the list has category, then show address same as on screenshot (first and last 6 symbols).

**Comment by Denis-Asipenko** [comment]
checked
