### ISSUE TITLE
The address should say "auto-generated"

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#170]
The non-default address should say "auto-generated". 

![fullsizeoutput_5387](https://user-images.githubusercontent.com/44961099/59552030-16bad280-8fac-11e9-9e2e-64bdcb0acd83.jpeg)

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova FYI

**Comment by DenisDemyanko** [comment]
@sasha-abramovich 
if the address does not have a name - this text should be displayed as placeholder?

**Comment by alexandrashelenkova** [comment]
If address doesn't have name, it should has "No name" name

**Comment by Denis-Asipenko** [comment]
checked
