### ISSUE TITLE
The numbers on the seed phrase should be more contrast as they are not very visible in the dark

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#171]
![fullsizeoutput_5385](https://user-images.githubusercontent.com/44961099/59552091-a6f91780-8fac-11e9-9412-1a37b7d836a8.jpeg)

**Comment by alexandrashelenkova** [comment]
Updated screens here 
https://zpl.io/a7OQ4dj
https://zpl.io/2ZLnkpq
https://zpl.io/2GyWQQd

**Comment by Denis-Asipenko** [comment]
checked
