### ISSUE TITLE
Fix requested amount

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#174]
When I've opened the screen the "Requested amount" was blank (as it should be). I've tried to tap the word itself and nothing happened. The diff between black and blue background is very subtle - FYI @alexandrashelenkova. When I've finally tapped the black field, "0" value appeared. 

Two issues:
* If I've tapped the amount accidentally, what is my way to select "nothing", to "cancel"?
* We need to tell user where to tap. Either make the field header tapable, or to change the background or whatever.
* We might consider showing an empty value in some way like "not specified" or something - maybe it would solve the issue.

**Comment by alexandrashelenkova** [comment]
When focus is on Transaction fee 0 shouldn't appear by default. Also if user put only 0 and try tried to open qr or share address, show that alert https://zpl.io/bz6X4PE

**Comment by Denis-Asipenko** [comment]
checked
