### ISSUE TITLE
The usage direction can't be differentiated from value

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#175]
On this screen, "search by..." directions are not differentiated from the value (e.g. the addresses below). Maybe italic font would help? Similar to what we write at the bottom of send/receive screens.
![fullsizeoutput_5382](https://user-images.githubusercontent.com/44961099/59552227-71edc480-8fae-11e9-8567-de4d30c0cc82.jpeg)

**Comment by alexandrashelenkova** [comment]
Made hint darker and italic (hint should be shown only when focus is on that field).
https://zpl.io/blMx9o5

**Comment by Denis-Asipenko** [comment]
checked
