### ISSUE TITLE
Receive | Edit address | Name it's unclear where to tap

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#176]
Similar to #174, it's unclear where to tap to enter the address name

**Comment by alexandrashelenkova** [comment]
Decided to add "No name" as default name. Updated screens here https://zpl.io/bPxQBjL

**Comment by DenisDemyanko** [comment]
also, if the user clicks on the title - the text field should be open

**Comment by Denis-Asipenko** [comment]
checked
