### ISSUE TITLE
Selected expiration should be highlighted

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#177]
When getting to the screen there should be green "v" near the value which is already selected

![fullsizeoutput_5389](https://user-images.githubusercontent.com/44961099/59552289-2982d680-8faf-11e9-8415-1b4a70776161.jpeg)

**Comment by sasha-abramovich** [comment]
should be 3 states: "as set, in 24 hours, never"

**Comment by DenisDemyanko** [comment]
@sasha-abramovich 
there is a situation when you have a 24 hour address and you want to extend it by 24 hours

**Comment by sasha-abramovich** [comment]
Great point! Let's make it "as set, in 24 hours, never".

**Comment by DenisDemyanko** [comment]
@sasha-abramovich 

sorry, I don't understand
please make a description with examples

**Comment by sasha-abramovich** [comment]
As agreed in the channel, let's add the value "as set now (hours)" which is selected by default. For 2.4 a separate task will be opened _if_ needed.

**Comment by alexandrashelenkova** [comment]
Updated design here https://zpl.io/2pv9OLy

**Comment by sasha-abramovich** [comment]
added design (as Alexandra wrote above): https://zpl.io/2pv9OLy

**Comment by Denis-Asipenko** [comment]
checked
