### ISSUE TITLE
How can I create the address if I want to share it later? (probably not a showstopper)

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#178]
Currently when I press "Receive" the address will be created only if I share it somehow _right now_. If I wanna use that address later I need to tap "Share" and then tap "Copy" or actually share it somewhere. Maybe there should be an easier way to create an address without sharing.

**Comment by alexandrashelenkova** [comment]
Updates screes here:
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5ce2394739f2e51e01fd8c6f

If user only opened screen and didn't do anything at all and used back button address shouldn't be created.
If user made some changes on the screen and used back button show that alert https://zpl.io/2jMW6BO
Tap on "Close and save address for later" button should bring user back to the previous screen (address created and saved).

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/59749793-60ded500-9286-11e9-8eb4-9c25792b1e95.png)

**Comment by Denis-Asipenko** [comment]
no alert

> If user only opened screen and didn't do anything at all and used back button show this alert https://zpl.io/2jMW6BO

>

**Comment by Denis-Asipenko** [comment]
checked
