### ISSUE TITLE
There should be an easier way to create the first category (not a showstopper)

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#179]
When there are no categories, I tap on "None" and I get a message that I should proceed to settings. I would prefer one of the following:
* To see that message without tapping on "None"
* To be taken somewhere to create my first category

In general there should be a way to create the category from send/receive screen IF it's easy.

**Comment by alexandrashelenkova** [comment]
if categories list is empty open this screen https://zpl.io/aNDMJnQ
Add note to categories screen https://zpl.io/VQvjeeP

**Comment by Denis-Asipenko** [comment]
checked
