### ISSUE TITLE
The categories dots should be easier tappable

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#180]
It takes time to make the precise tap. Please make the tapping zone bigger. If possible, please check that the visual feedback (e.g. the green outer circle) is shown fast enough

![fullsizeoutput_538a](https://user-images.githubusercontent.com/44961099/59552396-98acfa80-8fb0-11e9-9d9e-9ef9f901162f.jpeg)

**Comment by Denis-Asipenko** [comment]
checked
