### ISSUE TITLE
Edit address could be possibly done in-place (not in a separate screen) and in-style with Send/Receive

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#181]
![fullsizeoutput_538b](https://user-images.githubusercontent.com/44961099/59552441-1ec94100-8fb1-11e9-9f5d-86e41df1227d.jpeg)

**Comment by alexandrashelenkova** [comment]
@sasha-abramovich I don't think that this task is correct. By now in design address detail screen (https://zpl.io/2EBYKmn) and edit address screen (https://zpl.io/29wW4yl) looks completely different. I will also a little bit improve it for new send/receive screens (remove annotation, add address name field, etc.), but details view and edit is different actions and they shouldn't be on one screen.

**Comment by alexandrashelenkova** [comment]
Will consider other options during screen redesign

**Comment by alexandrashelenkova** [comment]
No need in that task
