### ISSUE TITLE
Update notification text and appearance

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#182]
* The text should say "Incoming transaction" and "Transaction status update"

![fullsizeoutput_538e](https://user-images.githubusercontent.com/44961099/59562146-3f49d780-9053-11e9-8e29-4ea0a6194f11.jpeg)
![fullsizeoutput_538f](https://user-images.githubusercontent.com/44961099/59562147-3f49d780-9053-11e9-8441-4dc2ee030e2b.jpeg)

**Comment by Denis-Asipenko** [comment]
checked
