### ISSUE TITLE
When pasting own address in "send" the contact-like info should be displayed

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#183]
![fullsizeoutput_5397](https://user-images.githubusercontent.com/44961099/59562939-a2d90280-905d-11e9-9695-67501e68411c.jpeg)

**Comment by alexandrashelenkova** [comment]
Updated design here https://zpl.io/2EgZ4yy

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/60009024-c7486680-967d-11e9-8498-15d229e8446f.png)

**Comment by Denis-Asipenko** [comment]
checked
