### ISSUE TITLE
When entering amounts "Done" button should appear (sample banking app attached for inspiration)

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#184]
![fullsizeoutput_5396](https://user-images.githubusercontent.com/44961099/59562973-1f6be100-905e-11e9-8030-1c152d7a0c42.jpeg)
![fullsizeoutput_5399](https://user-images.githubusercontent.com/44961099/59562974-20047780-905e-11e9-9050-74db0fe29c4c.jpeg)

**Comment by Denis-Asipenko** [comment]
checked

**Comment by sasha-abramovich** [comment]
@DenisDemyanko can you make "Done" in bold please?

![fullsizeoutput_53ea](https://user-images.githubusercontent.com/44961099/59993994-7ab05b80-967c-11e9-8142-70ba16dea727.jpeg)

**Comment by Denis-Asipenko** [comment]
checked
