### ISSUE TITLE
When "Send all" is pressed, the amount is still less than the balance

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#186]
A hint should be shown that the difference is the transaction fee

![fullsizeoutput_5395](https://user-images.githubusercontent.com/44961099/59562995-72de2f00-905e-11e9-80c9-b2f777806b47.jpeg)

**Comment by alexandrashelenkova** [comment]
Added hint under the amount field here https://zpl.io/bPxQBjL
By now it would be just transaction fee, after we add exchange rate, transaction fee would be shown in breaks.

**Comment by Denis-Asipenko** [comment]
the tip is displayed only after you tap  "send all"
![image](https://user-images.githubusercontent.com/45556620/59842457-44629b80-935f-11e9-95d4-10a4a36ca5ab.png)

**Comment by Denis-Asipenko** [comment]
checked
