### ISSUE TITLE
Transaction statuses colors and names are out of sync

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#188]
![fullsizeoutput_539e](https://user-images.githubusercontent.com/44961099/59563524-935db780-9065-11e9-8961-d661e2cb47cc.jpeg)

**Comment by sasha-abramovich** [comment]
@DenisDemyanko told that "completed" is in white because in that transaction I've sent the money to myself. In that case, it's not a showstopper for a current release. @dariatarakanova please prepare all the state machine for transactions, so we could revise colors, icons and names for each state.

**Comment by dariatarakanova** [comment]
@sasha-abramovich @alexandrashelenkova please have a look https://zpl.io/VOd1L9X

**Comment by dariatarakanova** [comment]
Please update icons for transaction statuses.

Example - https://zpl.io/2v6p70Q
List of icons and statuses - https://zpl.io/2ERlRGn

**Comment by alexandrashelenkova** [comment]
Arrows would be implemented during that task https://github.com/BeamMW/ios-wallet/issues/245

**Comment by Denis-Asipenko** [comment]
checked
