### ISSUE TITLE
Own addresses should probably be marked somehow to differentiate from contacts

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#189]
On the screenshot below both addresses are created by me, there should be some indication which points it out.

![fullsizeoutput_539d](https://user-images.githubusercontent.com/44961099/59563541-be480b80-9065-11e9-82cd-1b0bb5c00ca9.jpeg)

**Comment by alexandrashelenkova** [comment]
Let's use "my sending/receiving address fields name for transactions between own addresses and "contact", "address" fields for other transactions.
screens are here:
https://zpl.io/a7dvPwM
https://zpl.io/bP9DErp

**Comment by Denis-Asipenko** [comment]
checked
