### ISSUE TITLE
Face ID needs to be presented instead of fingerprint on some iPhones

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#190]
![photo_2562-06-16 20 30 05](https://user-images.githubusercontent.com/44961099/59564812-8f399600-9075-11e9-9d77-398e7d39e383.jpeg)

![image](https://user-images.githubusercontent.com/44961099/59564806-7f21b680-9075-11e9-8075-483b84536466.png)

**Comment by alexandrashelenkova** [comment]
Added screens here 
https://zpl.io/VqYYZ3Z
https://zpl.io/25ppkjj

**Comment by Denis-Asipenko** [comment]
checked
