### ISSUE TITLE
There should be a "Done" button when the password is entered (and also in all the cases a keyboard without a "return" button is displayed)

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#191]
![image](https://user-images.githubusercontent.com/44961099/59616310-5caf9c00-914e-11e9-94bf-cbcf6457e557.png)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/59769264-72d46e00-92ae-11e9-90e0-523ebe3e273f.png)
![image](https://user-images.githubusercontent.com/45556620/59769275-77008b80-92ae-11e9-9958-21b6b1470c61.png)

**Comment by Denis-Asipenko** [comment]
checked
