### ISSUE TITLE
On "Receive" screen (and may be not only) the generated address should be copiable at a single (long?) tap

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#195]
User feedback: expected to copy on a long tap, see a message like "address copied" and send it in some channel (without the system "share"). 

In the case of copying and closing the screen - there should be no "save address?" dialog shown

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova maybe the same about send confirmation screen? or the send screen when the address is already specified? just to align all the cases.

**Comment by sasha-abramovich** [comment]
![fullsizeoutput_53e9](https://user-images.githubusercontent.com/44961099/59993900-23aa8680-967c-11e9-808f-a1601ea9aa3d.jpeg)
![fullsizeoutput_53e7](https://user-images.githubusercontent.com/44961099/59993901-23aa8680-967c-11e9-9846-24fa6e1a6c46.jpeg)

**Comment by alexandrashelenkova** [comment]
Added pop-up here https://zpl.io/VKDnR08

**Comment by Denis-Asipenko** [comment]
need to change text in  pop-up
![image](https://user-images.githubusercontent.com/45556620/60168432-7ff0e000-980d-11e9-8dfd-f6d126292f3a.png)
on 
![image](https://user-images.githubusercontent.com/45556620/60168498-9dbe4500-980d-11e9-9ad7-3e231ae5d6bf.png)

**Comment by alexandrashelenkova** [comment]
@DenisDemyanko after user copied address with a long tap on receive screen, lets keep him on the same screen, not back to main screen. If user goes back by back button, no save address dialog should be shown.

**Comment by alexandrashelenkova** [comment]
By now, let's have it only on receive screen. Will discuss with @sasha-abramovich about other screens and update a description if needed.

**Comment by Denis-Asipenko** [comment]
checked
