### ISSUE TITLE
Scan QR from album - very handy from mobile-to-mobile

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#196]
this is from Alipay

![photo_2562-06-24 11 10 49](https://user-images.githubusercontent.com/44961099/59991263-d8d74180-9670-11e9-9add-30a8f2ab1397.jpeg)

**Comment by alexandrashelenkova** [comment]
Screen is here https://zpl.io/2p4675o
@DenisDemyanko also in this task please make navigation bar looks same as in design.

**Comment by Denis-Asipenko** [comment]
checked
