### ISSUE TITLE
On swipe down the keyboard should disappear (not a showstopper)

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#197]

**Comment by sasha-abramovich** [comment]
![fullsizeoutput_53e8](https://user-images.githubusercontent.com/44961099/59994081-bfd48d80-967c-11e9-873b-7d30dc224889.jpeg)

**Comment by DenisDemyanko** [comment]
already implemented.

**Comment by sasha-abramovich** [comment]
following the talk with @DenisDemyanko the swipe latency can't be tweaked. closing this one.
