### ISSUE TITLE
There is no "transaction comment" on Receive screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#201]
Need to add "transaction comment" to Receive screen (advance tab)
https://zpl.io/2ZrGY7X

Now it is look like this:
![IMG_3103](https://user-images.githubusercontent.com/47353570/60003386-41bfb900-9673-11e9-8b99-700240b2903a.PNG)

**Comment by Denis-Asipenko** [comment]
1. Where this comment should be displayed?
2. Will it be possible to edit the comment?
3. How and when it can be edited? (if possible).On what screens?
4. Will the change affect past transactions or only future transactions?

**Comment by alexandrashelenkova** [comment]
This comment is for transaction only, not for address. So...
1. would be shown on transactions details screen https://zpl.io/bP9DErp
2. no, comment wouldn't be editable
3. -
4. no, only one transaction

**Comment by Denis-Asipenko** [comment]
checked
