### ISSUE TITLE
When focus is on address field, addresses/contacts list should be shown even when it's empty

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#205]
https://zpl.io/a3j3W18

**Comment by alexandrashelenkova** [comment]
![2019-06-25 16 41 46](https://user-images.githubusercontent.com/7249484/60083345-25517880-9768-11e9-8440-b8b810ada438.jpg)

**Comment by sasha-abramovich** [comment]
@DenisDemyanko please also add "Done" button  just as when entering amount (talked to @alexandrashelenkova on that).

**Comment by DenisDemyanko** [comment]
@sasha-abramovich What for? there is a button on the keyboard

**Comment by sasha-abramovich** [comment]
you are correct. no need for "Done" button.

**Comment by Denis-Asipenko** [comment]
If you select a contact and then erase the address, the address/contact list is no longer displayed again

**Comment by Denis-Asipenko** [comment]
checked
