### ISSUE TITLE
Fix status position on addresses screen

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#207]
"Online" status is lower than on other screens

**Comment by alexandrashelenkova** [comment]
[
![2019-06-25 16 50 14](https://user-images.githubusercontent.com/7249484/60084043-5ed6b380-9769-11e9-9713-8d08880b0ec3.jpg)
![2019-06-25 16 50 32](https://user-images.githubusercontent.com/7249484/60084044-5f6f4a00-9769-11e9-9f99-e357725abcbc.jpg)

](url)

**Comment by Denis-Asipenko** [comment]
checked
