### ISSUE TITLE
Receive screen fixes

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#217]
- Address name should have white colour, even if it's "No name"
- "None" category should have white colour 
- "Optional" in requested amount header shouldn't be all caps
- Add dot after "Send this address ..." on receive screen
- Address and Edit address should have same background
- Update Share address icon (The correct icon is here https://zpl.io/VKDnR08)
- QR should be in capital letters

**Comment by Denis-Asipenko** [comment]
checked
