### ISSUE TITLE
Date is in Russian after changing language from Russian to English

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#222]
![IMG_3131](https://user-images.githubusercontent.com/47353570/60188586-3cf83200-9838-11e9-9aa4-08d763d56afe.PNG)
![IMG_3132](https://user-images.githubusercontent.com/47353570/60188587-3cf83200-9838-11e9-9acb-546d2b5b6ecf.PNG)

**Comment by Denis-Asipenko** [comment]
checked
