### ISSUE TITLE
ip:port not shown as localized

### ISSUE THREAD

**Issue by jinpinggou** [BeamMW/ios-wallet#224]
![IMG_8381](https://user-images.githubusercontent.com/16055149/60233815-87c78780-98d4-11e9-91a1-fa10914626e8.PNG)

**Comment by Denis-Asipenko** [comment]
checked on testnet.
version : 2.4.19
![image](https://user-images.githubusercontent.com/45556620/62137377-88e23f00-b2ee-11e9-959b-5c0624c03be3.png)
