### ISSUE TITLE
addresses menu: "Default" and date format not localized

### ISSUE THREAD

**Issue by jinpinggou** [BeamMW/ios-wallet#225]
Every wallet comes with a default address. The address name "Default" should be included in the list to be translated.

Date format should be translated as well. As in China, 95% of the population don't know what "15 June, 2019" means. In China, the date format goes like:
1. 2019/6/15 as YYYY/MM/DD
2. 2019年6月15日 as YYYY"年"MM"月"DD"日"

P.S.: please ignore the "Copy" in the picture, as my device system language is in English. 

![IMG_8374](https://user-images.githubusercontent.com/16055149/60233940-e8ef5b00-98d4-11e9-8671-e2ea82a157f6.PNG)

**Comment by jinpinggou** [comment]
Thanks for the work. 
1. "Default" is done. Also, I've update on Crowdin. We are good.
2. The date format display is still weird in Chinese. As Chinese never use date format as DD/MM/YYYY. It should be like either of the following: 
- 2019/6/15 as YYYY/MM/DD
- 2019年6月15日 as YYYY"年"MM"月"DD"日"

P.S.: don't worry about the "MY ACTIVE" and "MY EXPIRED" tab in the screen snapshot, fixes have been made to Crowdin. 


![IMG_8442](https://user-images.githubusercontent.com/16055149/60693997-1066a900-9f0f-11e9-9b1d-7933b8c15ec5.PNG)



![IMG_8441](https://user-images.githubusercontent.com/16055149/60693994-0d6bb880-9f0f-11e9-8d35-b855349d00f5.PNG)

**Comment by sasha-abramovich** [comment]
@DenisDemyanko the bug still happens according to @jinpinggou (checked in the very latest version)

please have a look:
![image](https://user-images.githubusercontent.com/44961099/60694126-3c7e2c00-9f07-11e9-814c-8e0fb392d03a.png)

**Comment by DenisDemyanko** [comment]
@sasha-abramovich I don't see any problems. Date translated

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/62207939-2183c800-b39e-11e9-95df-009ac4abfda9.png)

**Comment by Denis-Asipenko** [comment]
check on testnet
version:2.4.24
