### ISSUE TITLE
UTXO screen redesign

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#226]
UTXO screens changes:
- change tabs view, rename tabs, add new tabs
- add gradient on top
- change main background colour (will affect all screens in the mainnet app)
- add related transaction comment (if there are one) and date. If utxo has few transactions, comment should be from latest one.

New screens are here
https://zpl.io/VKj7K18
https://zpl.io/V0grRxl
https://zpl.io/bz6dA08
https://zpl.io/boMJKOM

**Comment by Denis-Asipenko** [comment]
checked
