### ISSUE TITLE
Addresses/contacts screens redesign

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#227]
Left screenshot - new design, right one - old.
- change tabs view and rename tabs
- Plus icon - will allow to save contact for later (if user doesn't want to proceed transaction right now), will provide additional screens for that case
- add gradient on top
- change main background colour (will affect all screens in the mainnet app)
- replace expirations date header with an icons
- categories on separate line (for multi categories possibility )

https://zpl.io/aBB3j0q
https://zpl.io/VKPYoG7

**Comment by alexandrashelenkova** [comment]
<img width="644" alt="Screenshot 2019-06-28 at 15 37 08" src="https://user-images.githubusercontent.com/7249484/60325741-9be5b480-99ba-11e9-8ef6-2228ffcb5d15.png">
<img width="647" alt="Screenshot 2019-06-28 at 15 37 32" src="https://user-images.githubusercontent.com/7249484/60325768-ae5fee00-99ba-11e9-9769-d94041e15ba2.png">

**Comment by alexandrashelenkova** [comment]
<img width="566" alt="Screenshot 2019-07-02 at 19 42 39" src="https://user-images.githubusercontent.com/7249484/60510249-931a1900-9d01-11e9-8af6-8ffa9b562774.png">

**Comment by Denis-Asipenko** [comment]
checked
