### ISSUE TITLE
Settings screens redesign

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#228]
- add gradient on top
- change main background colour (will affect all screens in the mainnet app)
- reorganised settings items order
- change off toggle view
- version number should be in bold font
- Touch/Face ID should appear depends of devices specs, if there's no Touch/Face ID, that item shouldn't be in the settings at all
- Secondary currency item is not required  for now,  will be implemented when we'll have the info

https://zpl.io/VQvjoQ9

**Comment by Denis-Asipenko** [comment]
design:
![image](https://user-images.githubusercontent.com/45556620/60965331-45636900-a31e-11e9-9817-2bc67a9d4128.png)
actual:
![image](https://user-images.githubusercontent.com/45556620/60965392-64fa9180-a31e-11e9-9c64-3d756b705d02.png)

**Comment by Denis-Asipenko** [comment]
checked
