### ISSUE TITLE
Add "x" icon on text fields

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#229]
Add "x" icon for all text fields in the app (transaction comments, address names, tag names, send to, transaction search field). Not amount fields on send/receive screens.
"x" should be shown only when user already typed in something in the input field.
https://zpl.io/25J07B0

**Comment by Denis-Asipenko** [comment]
[video_2019-07-29_19-26-28.zip](https://github.com/BeamMW/ios-wallet/files/3443257/video_2019-07-29_19-26-28.zip)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/62120988-5ffc8280-b2cb-11e9-81f4-a77b3c56b872.png)

**Comment by Denis-Asipenko** [comment]
checked
