### ISSUE TITLE
On the screen "Seed phrase" there is no "Next" button in the zoomed mode.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/ios-wallet#230]
"Next" button not appear in the "Seed phrase" screen in zoomed mode on iPhone 6s.
Steps:
1. Go to iPhone's Settings > Display and Brightness.
2. Set Display Zoom View = Zoomed.
3. Run Beam app for the first time.
4. Create a new wallet.
5. Generate the seed phrase.
Actual:
The button the "next" isn't displayed. 
Expected:
The button is displayed. .
![image](https://user-images.githubusercontent.com/45556620/60459817-d1083600-9c4a-11e9-8ac0-b988c9649f5a.png)

**Comment by DenisDemyanko** [comment]
fixed. Maine build 2.3(3)

**Comment by Denis-Asipenko** [comment]
checked
![image](https://user-images.githubusercontent.com/45556620/60789509-f4117900-a167-11e9-9de2-0b1f8595d6f0.png)
