### ISSUE TITLE
the language switch should be on the very first screen since the first launch (while settings are inaccessible yet)

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#233]

**Comment by alexandrashelenkova** [comment]
@sasha-abramovich we discussed that in channel and I don't really agree that we need that.. I thought we still didn't come to agreement on that?

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova we've discussed it and after that customer complained again, so I wanted to raise again the issue. If we have the ability to change the language in the app in general, it should embrace the entire app functionality.

**Comment by alexandrashelenkova** [comment]
Added switcher here: https://zpl.io/aXP3K3p
Switcher should open this screen https://zpl.io/25JjNMe

**Comment by Denis-Asipenko** [comment]
the list of languages is not in alphabetical order
![image](https://user-images.githubusercontent.com/45556620/62047590-8e1e8b80-b213-11e9-9bc3-2d6d1ff779a0.png)

**Comment by Denis-Asipenko** [comment]
checked
