### ISSUE TITLE
Send/receive screens improvements

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#234]
- "send all" rename to "add all", make less attention to the button?
- “paste address or find contact” rename to "send to"
- "annotation" rename to "comment"
- "category" rename to "tag"
- "contacts"/"addresses" tabs - make tappable area bigger
- "existing addresses", "addresses" rename to "my active addresses"
- addresses/contacts view update to addresses/contacts screens (multi-categories, expiration date, etc)
- add hint about "local comment" in input field, remove "won't be shared" from comment's header
- remove first sentence on receive screens annotation ("Send this address over...")

Updated screens are here:
send https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5ce239536c73511dec2404fa
receive https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5ce2394739f2e51e01fd8c6f

**Comment by iamien1993** [comment]
1) "won't be shared"  is not removed from transaction comment on SEND screen.
**STR**
* Wallet > SEND > tap on TRANSACTION COMMENT
**ER:** hint "Local comment".
**AR:** hint "Won't be shared"
![image](https://user-images.githubusercontent.com/44057235/62205540-542ac200-b398-11e9-889a-f7867313ea3a.png)

**Comment by DenisDemyanko** [comment]
discussed with @alexandrashelenkova
we leave the current text

**Comment by iamien1993** [comment]
tested
app: testnet v2.4.24
phone's model: iPhone XR
