### ISSUE TITLE
Restore Wallet (manual)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#236]

**Comment by alexandrashelenkova** [comment]
@DenisDemyanko manual restore need some improvements, please by now work on automatic restore only.

**Comment by alexandrashelenkova** [comment]
Updated screens are here: https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5d19f974160fa1aff5706f5d

**Comment by Denis-Asipenko** [comment]
design:
![image](https://user-images.githubusercontent.com/45556620/62125531-11a0b100-b2d6-11e9-9c6e-eaf2d794d464.png)
actual:
![image](https://user-images.githubusercontent.com/45556620/62125553-23825400-b2d6-11e9-8ca2-b6c65d53e268.png)
words are not removed when you use the quick delete " X"
[video_2019-07-30_14-25-54.zip](https://github.com/BeamMW/ios-wallet/files/3446573/video_2019-07-30_14-25-54.zip)
Need to replace the loading screens in accordance with the design
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5c751b6726c62e6244b010ba
![image](https://user-images.githubusercontent.com/45556620/62125937-35b0c200-b2d7-11e9-8448-35e09d531926.png)
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5d1ad7c6384819076e3b61c4
![image](https://user-images.githubusercontent.com/45556620/62125964-495c2880-b2d7-11e9-8e8b-22f5ced89b8e.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/62126066-95a76880-b2d7-11e9-911e-6e0bd6f55827.png)
![image](https://user-images.githubusercontent.com/45556620/62126127-b374cd80-b2d7-11e9-9dc4-f9c2751e2c38.png)

**Comment by Denis-Asipenko** [comment]
https://github.com/BeamMW/ios-wallet/issues/6#issuecomment-516383185

**Comment by Denis-Asipenko** [comment]
https://github.com/BeamMW/ios-wallet/issues/6#issuecomment-516829057

**Comment by Denis-Asipenko** [comment]
checked
