### ISSUE TITLE
Hard to notice line under selected tab

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#240]

**Comment by alexandrashelenkova** [comment]
![File](https://user-images.githubusercontent.com/7249484/61269032-ee530d80-a7cf-11e9-81e7-420b4df14bb6.jpg)

**Comment by alexandrashelenkova** [comment]
Updated design here https://zpl.io/aBB3j0q

**Comment by iamien1993** [comment]
tested

app: testnet v2.4.20
phone's model: iPhone XR
