### ISSUE TITLE
Addresses details, edit addresses screens improvements

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#241]
details screen improvements

Changes:
- detail view fields, transactions list header updates 
- removed additional actions button from right upper corner. Now there are edit address and show QR buttons. Delete address moved inside editing view, copy address should work by long tap on address on address detail screen
- update headers on Choose tag and Expiration date screens https://zpl.io/ag6gqL1, https://zpl.io/2pv9OLy
- remove Save button on Expiration screen, close screen by choosing item from the list

Screens:
https://zpl.io/bekz86B
https://zpl.io/bAWOkgO

**Comment by alexandrashelenkova** [comment]
<img width="1059" alt="Screenshot 2019-07-18 at 13 01 40" src="https://user-images.githubusercontent.com/7249484/61430305-39019080-a95c-11e9-9b5f-1dc353ccf46e.png">
<img width="554" alt="Screenshot 2019-07-18 at 13 00 37" src="https://user-images.githubusercontent.com/7249484/61430313-3d2dae00-a95c-11e9-97d3-4e92a1f596ca.png">

**Comment by alexandrashelenkova** [comment]
@sasha-abramovich please review changes :)

**Comment by Denis-Asipenko** [comment]
Doesn't match design.
design:
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5d2ffc439dd4da61909f5a10
![image](https://user-images.githubusercontent.com/45556620/62055272-f70dff80-b223-11e9-8bff-8c954faeb5cf.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/62055299-01c89480-b224-11e9-97c1-0c34c9a71b67.png)
+
![image](https://user-images.githubusercontent.com/45556620/62055753-e90cae80-b224-11e9-92f8-98db31b3a214.png)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/62119859-27f44000-b2c9-11e9-9653-5d68f5ce5823.png)

**Comment by Denis-Asipenko** [comment]
checked
