### ISSUE TITLE
UTXO details screen improvements

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#242]
Screens are here
https://zpl.io/2jYMBWx
https://zpl.io/2pkMZPJ

Transactions should be displayed in Chronological order.

**Comment by iamien1993** [comment]
we need to choose sort's type: ASC or DESC

**Comment by iamien1993** [comment]
@alexandrashelenkova chose the DESC sort, so:
UTXO details contain a transaction history which using ASC type of sort.
**STR:**
* UTXO > choose any tab (available, in progress, spent, unavailable) > choose any record which contains more than 1 record in the transaction history
* check dates

**ER:** transaction history uses DESC sort
**AR:** transaction history uses ASC sort
![image](https://user-images.githubusercontent.com/44057235/62355686-2cfafe80-b518-11e9-9afa-8add959ca1e9.png)

**Comment by iamien1993** [comment]
tested
app version: v2.4.32
model: iPhone XR
