### ISSUE TITLE
Transaction details screen improvements

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#243]
https://zpl.io/VkeXBWv

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova tried to leave a message in Zeplin (twice) but couldn't see it saved when the page was reopened, writing here:

1. Kernel ID should be differentiated from Transaction ID, the order should be the same as one in the Transaction details on the main screen.
2. When clicking on Kernel ID it should lead to the blockchain explorer, the same way (with confirmation dialog) as from the transaction details.

**Comment by Denis-Asipenko** [comment]
checked
