### ISSUE TITLE
Make off toggle background darker (testnet)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#244]
Can we please make bag in off toggle position #0F0D17? By now it's hardly visible (testnet colours only).

**Comment by alexandrashelenkova** [comment]
![Artboard](https://user-images.githubusercontent.com/7249484/61358598-414ec280-a8ad-11e9-82f4-df5891ca7cb0.png)

**Comment by Denis-Asipenko** [comment]
at the moment bag in off toggle position #0f0d18

**Comment by Denis-Asipenko** [comment]
checked
