### ISSUE TITLE
Main screen improvements

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#245]
Screens are here
https://zpl.io/2pMmPPj
https://zpl.io/VqWLnGl
https://zpl.io/2v06g0Q
https://zpl.io/aNzDkzk

I suggest we show only 5 last transactions on the main screen, for more transactions user can use separate screen. Transaction search, payment proof and filters (when we will implement that) will be on transactions screen as well.

**Comment by Denis-Asipenko** [comment]
checked
