### ISSUE TITLE
UTXO empty state and secure mode icons should be on the same place

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#246]

**Comment by alexandrashelenkova** [comment]
<img width="625" alt="Screenshot 2019-07-18 at 12 06 37" src="https://user-images.githubusercontent.com/7249484/61428409-8f6ad100-a954-11e9-8887-0cd6d3e11c36.png">

**Comment by alexandrashelenkova** [comment]
Also @DenisDemyanko if there's no UTXO at all, can we not show tabs here please? (screenshot attached). Same for contacts/addresses empty screen state.

**Comment by alexandrashelenkova** [comment]
<img width="543" alt="Screenshot 2019-07-18 at 12 08 31" src="https://user-images.githubusercontent.com/7249484/61428487-d9ec4d80-a954-11e9-8e47-db651a7ee2b3.png">

**Comment by iamien1993** [comment]
Tested.
app: testnet 2.4.19
phone's model: iPhone XR
