### ISSUE TITLE
On UTXO screen when we switch between tabs, it should move left

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#247]
Problem: Currently is we choose Spent tab, we can't see that there are more tabs after.
Decision:
1. Make tabs name font size smaller, so 4th tab would be partly visible when user first opens screen (please check design, blockchain height header and tabs header should have same font size, currently tabs header size is bigger https://zpl.io/V0grRxl)
2. when user clicks Spent tab, move all tabs on the left, so last tab (Unavailable) would be fully visible https://zpl.io/bz6dA08

Also we don't need Maturing, Outgoing and Incoming tabs (it all is tab In progress), please remove.

**Comment by iamien1993** [comment]
app: Testnet v2.4.17
phone's model: iPhone XR

1) "blockchain height" and "last block hash" have a smaller size than tabs.
**STR:**
* open UTXO screen
**Expected result**: "blockchain height" and "last block hash" have a similar size as tabs
**Actual result**: "blockchain height" and "last block hash" have a smaller size than tabs.
![image](https://user-images.githubusercontent.com/44057235/62050922-ec02a180-b21a-11e9-9dbc-f9c6240b5db3.png)

2) Tabs Maturing, Outgoing and Incoming are not removed
**STR**
* open UTXO screen
* swipe tabs  right
**Expected result:** tabs "Maturing", "Outgoing" and "Incoming" have been removed from the interface
**Actual result:** tabs "Maturing", "Outgoing" and "Incoming" are available

**Comment by iamien1993** [comment]
checked.
app: Testnet v2.4.19
phone's model: iPhone XR
