### ISSUE TITLE
[Settings > Clear data] the confirmation popup contains mistake in case we choose 2 options out of 3

### ISSUE THREAD

**Issue by iamien1993** [BeamMW/ios-wallet#249]
**app:** Testnet v2.4.17, Prod 2.3.7
**phone's model:** iPhone XR

**STR:**
* run app > Settings > Clear data
* choose 2 options out of 3 (e.g. "Delete all addresses" + "Delete all transactions", etc.)
* Press "_Clear_"
**Expected result:** the message message "Are you sure you want to delete all addresses and transactions from your wallet?"
**Actual result:** the message "Are you sure you want to delete all addressesandtransactions from your wallet?"
![image](https://user-images.githubusercontent.com/44057235/62056452-553be200-b226-11e9-87d7-a5f51dd2dbab.png)

**Comment by Denis-Asipenko** [comment]
checked
