### ISSUE TITLE
Face ID UI/UX impovements

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#250]
Remove Face Id icon, if face not recognised show same dialog as while opening wallet flow.

**Comment by alexandrashelenkova** [comment]
![2019-07-29 23 03 48](https://user-images.githubusercontent.com/7249484/62059085-25580300-b255-11e9-9a8d-e0c1dab75939.jpg)

**Comment by iamien1993** [comment]
Need to think about description and implementation

**Comment by Denis-Asipenko** [comment]
checked
