### ISSUE TITLE
Add on Settings screen switcher "Connect to random node".

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/ios-wallet#251]
Need add on Settings screen switcher "Connect to random node" according design.
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5cc26a424a92851016e146d8
![image](https://user-images.githubusercontent.com/45556620/62203470-e9778780-b393-11e9-86da-497d71608b9c.png)

**Comment by sasha-abramovich** [comment]
when "random node" is switched on, the ip:port value should be not highlighted/pale/deactivated and not clickable (it also should show the node the wallet is currently connected to) - @alexandrashelenkova please design it

**Comment by alexandrashelenkova** [comment]
Design is here https://zpl.io/25OMeK8
node address isn't clickable on that screen

**Comment by iamien1993** [comment]
app version: Testnet 3.1.8

description: we need to return node that we have previously used in case we turn random node off

**STR:**
* move to Settings
* set up a node 
* turn random node on
* turn random node off

**Expected result:** old node's value has been returned.
**Actual result:** node = previous random node

**Comment by iamien1993** [comment]
tested

app version: testnet 3.1.9
