### ISSUE TITLE
Edit address screen, highlight delete address

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#252]
Updated screen is here https://zpl.io/bAWOkgO

**Comment by alexandrashelenkova** [comment]
![2019-08-02 12 06 22](https://user-images.githubusercontent.com/7249484/62343702-03dd6c80-b51e-11e9-8431-2859d049827f.jpg)

**Comment by alexandrashelenkova** [comment]
![2019-08-02 12 09 08](https://user-images.githubusercontent.com/7249484/62343869-5880e780-b51e-11e9-87f1-dc1882b52b90.jpg)

**Comment by iamien1993** [comment]
"Delete contact" is not changed on the Edit contact screen.
app version: Testnet 3.1.7

**STR:**
* move to: Addresses > tab Contacts
* choose a contact > edit
**Expected result:** the button "Delete contact" is red
**Actual result:** the button "Delete contact" is white
![image](https://user-images.githubusercontent.com/44057235/63337944-8ce00a80-c34a-11e9-83c2-bf065c439fb3.png)

**Comment by iamien1993** [comment]
checked:
app version: Testnet 3.1.8
