### ISSUE TITLE
Input field line isn't noticeable

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#257]
All input field lines should have #FFFFFF colour (opacity 10%)
https://zpl.io/bzqBKd8

**Comment by alexandrashelenkova** [comment]
![2019-08-01 20 18 17](https://user-images.githubusercontent.com/7249484/62522492-65764180-b864-11e9-9504-3a97203e8564.jpg)

**Comment by iamien1993** [comment]
tested:
app version: Testnet 3.1.6
