### ISSUE TITLE
Fix logo position on rate app dialog

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#258]
Please fix for all languages (if it depends on it)
![image](https://user-images.githubusercontent.com/47353570/61932791-eb54db80-af8c-11e9-8f0a-fc5e3651c0e7.png)

**Comment by iamien1993** [comment]
App version: Testnet 3.1.8
Phone's model: iPhone XR

Some languages have problems with this dialog:
* Finnish - defect of the bottom button + logo is too close with text area
![image](https://user-images.githubusercontent.com/44057235/63416241-bf9c0880-c407-11e9-8b40-13721f419cb6.png)
* Korean - logo is too close with text area
![image](https://user-images.githubusercontent.com/44057235/63416275-ce82bb00-c407-11e9-98c9-d40d970e1f7a.png)
* Vietnamese - defect of the bottom button + logo is too close with text area
![image](https://user-images.githubusercontent.com/44057235/63416290-d9d5e680-c407-11e9-96b9-bae80241ede6.png)

**Comment by iamien1993** [comment]
checked.

app version: testnet 3.1.9
phone's model: iPhone XR
