### ISSUE TITLE
Restore wallet on password screen

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#259]
Restore option is mission on input wallet screen
https://zpl.io/VKPDEjJ

**Comment by alexandrashelenkova** [comment]
![2019-08-06 23 56 43](https://user-images.githubusercontent.com/7249484/62555627-dbe76380-b8a5-11e9-8341-27437148f991.jpg)

**Comment by iamien1993** [comment]
checked

app version: Testnet 3.1.7
phone's model: iPhone XR
