### ISSUE TITLE
Fix text on restore alert

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#260]
Correct text is here https://zpl.io/VkeqZvM

**Comment by alexandrashelenkova** [comment]
![2019-08-06 23 58 02](https://user-images.githubusercontent.com/7249484/62555730-0afdd500-b8a6-11e9-92f5-e6879909de5b.jpg)

**Comment by iamien1993** [comment]
checked

app version: Testnet 3.1.6
