### ISSUE TITLE
Fix buttons position on login screen

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#262]
Move "Restore wallet" closer to "create new wallet" button, show app's version on the bottom of the screen.
Design https://zpl.io/aXP3K3p

**Comment by alexandrashelenkova** [comment]
Currently screen looks like that 
![IMG_0764](https://user-images.githubusercontent.com/7249484/62683753-cd0dc780-b9f1-11e9-91bf-def08357b043.PNG)

**Comment by iamien1993** [comment]
checked.
app version: Testnet 3.1.6
phone's model: iPhone XR
