### ISSUE TITLE
Do not show seed phrase screenshot alert dialog if seed phrase screen is empty (on restore)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#263]

**Comment by alexandrashelenkova** [comment]
![IMG_0768](https://user-images.githubusercontent.com/7249484/62688873-49a5a380-b9fc-11e9-9dd0-a633223d7917.PNG)

**Comment by iamien1993** [comment]
Tested.
app version: Testnet 3.1.8
