### ISSUE TITLE
Improve Show owner key flow

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#264]
Updated Show owner key is here https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5d80d2def6f828885ba70f12

- different text depends on user's device/settings (for password only, password + face id, password + touch id)
- request face/touch id BEFORE password
- after touch/face id failure - show default alert
![IMG_1674](https://user-images.githubusercontent.com/7249484/65042194-ef004f80-d98a-11e9-8517-69069e6381eb.PNG)
- updated design of Show owner key screen https://zpl.io/a8J0MW6

**Comment by Denis-Asipenko** [comment]
After entering 3 failed attempts Touch ID, fingerprint icon should highlight the in red.
Mainnet 3.0.1:
![image](https://user-images.githubusercontent.com/45556620/67281203-9404cf80-f4d7-11e9-822b-ee756215f696.png)
Actual on 3.1.29 .
As on the login screen so "Show owner key" screen.
[video_2019-10-22_14-14-39.zip](https://github.com/BeamMW/ios-wallet/files/3755168/video_2019-10-22_14-14-39.zip)

**Comment by DenisDemyanko** [comment]
@Denis-Asipenko related to task #250  we remove red color

**Comment by Denis-Asipenko** [comment]
checked
