### ISSUE TITLE
Remove "+" from addresses tabs

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#265]
"+" icon should be only on "Contacts" tab. Please make it appear and dissapear smooth, so it won't "Blink" during changing tabs

**Comment by alexandrashelenkova** [comment]
<img width="389" alt="Screenshot at Aug 15 16-01-12" src="https://user-images.githubusercontent.com/7249484/63081360-fbe9e780-bf75-11e9-9974-e5cf5c51a28e.png">

**Comment by iamien1993** [comment]
app version: Testnet 3.1.8

"+" button is available on **My active** and **My expired** tabs
![image](https://user-images.githubusercontent.com/44057235/63353895-25d34d80-c36c-11e9-975c-388b100327a2.png)

**Comment by iamien1993** [comment]
checked

app version: Testnet 3.1.9
phone's model: iPhone XR
