### ISSUE TITLE
Fix bugs in Thai app version

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#267]
Part of text has black font in the end

**Comment by alexandrashelenkova** [comment]
![2019-08-19 19 48 32](https://user-images.githubusercontent.com/7249484/63263174-6ffbf680-c2ba-11e9-8dbb-732312f129b0.jpg)
![Uploading 2019-08-19 19.48.38.jpg…]()

**Comment by iamien1993** [comment]
checked

app version: Testnet 3.1.9
phone's model: iPhone XR
