### ISSUE TITLE
Remove "Save" button on language screen

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#268]
Updated screen is here https://zpl.io/25JjNMe
Change language and bring back to settings screens just by tap on language line.

**Comment by alexandrashelenkova** [comment]
<img width="355" alt="Screenshot at Aug 19 20-13-52" src="https://user-images.githubusercontent.com/7249484/63264769-73917c80-c2be-11e9-93bb-3f09ff0f052f.png">

**Comment by iamien1993** [comment]
checked

app version: Testnet 3.1.8
