### ISSUE TITLE
Implement transaction statuses & icons

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#276]
Transaction statuses are here http://zpl.io/bLWRy77
These statuses should be used everywhere where user can see transactions in the app

**Comment by alexandrashelenkova** [comment]
@DenisDemyanko please rename "Sending" and "Receiving" statuses in to "In progress", cause it's more correct term for such statuses as "waiting", "confirming".

**Comment by Denis-Asipenko** [comment]
checked
