### ISSUE TITLE
Transaction search fixes

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#278]
1. Transaction search should be by kernel id too (not only transactions id), fix empty screen state wording https://zpl.io/aNzDkzk
2. Updated design https://zpl.io/brPoEm7
Transaction type, status, comment (with icon), date, amount should be shown always in transactions lists. Additional show field which contains searched info (transaction or kernel id, addresses or contact, contacts name (with icon). Searched words should be highlighted (#00F6D2).

**Comment by Denis-Asipenko** [comment]
I think the search should be for the first 6 characters (address, transaction ID, kernel ID, name, comment)
![image](https://user-images.githubusercontent.com/45556620/67009237-e0c16280-f0f3-11e9-953a-6fe673c54afa.png)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/67083929-b54a8080-f1a4-11e9-9b6b-7f6a01de52e2.png)

**Comment by Denis-Asipenko** [comment]
checked
