### ISSUE TITLE
Update Share transaction details screen

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#282]
New versions are here 
mainnet https://zpl.io/awPeoDM
testnet https://zpl.io/ad10ApK
masternet https://zpl.io/beW0gAW

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/67084664-0b6bf380-f1a6-11e9-9850-8946af6f4839.png)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/67282262-070f4580-f4da-11e9-86d8-fd93fd924378.png)

**Comment by Denis-Asipenko** [comment]
сhecked on testnet
Version: 3.1.30
