### ISSUE TITLE
Payment proof screen updates

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#285]
New screens are here https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5ca1ac27163c972ad46ebf27

Small changes have been done to match new app design

**Comment by Denis-Asipenko** [comment]
Design:
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91?seid=5ca1ac27163c972ad46ebf27
![image](https://user-images.githubusercontent.com/45556620/67001398-4c023900-f0e2-11e9-9b48-e964b6991110.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/67001486-91bf0180-f0e2-11e9-8722-57d10aee090d.png)

**Comment by Denis-Asipenko** [comment]
If the sender and the recipient have names, you need to display them
![image](https://user-images.githubusercontent.com/45556620/67081723-5d117f80-f1a0-11e9-8461-db63cd5b9d38.png)

**Comment by Denis-Asipenko** [comment]
checked
