### ISSUE TITLE
Edit / create tag update + tag screen

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#286]
Update create / edit tag design to match new design 
https://zpl.io/aNDMJnQ
https://zpl.io/bA7ovNp

**Comment by alexandrashelenkova** [comment]
Also let's put colour's name instead of "No name" in tag's name field (if user didn't add any name).

**Comment by Denis-Asipenko** [comment]
Actual:
![image](https://user-images.githubusercontent.com/45556620/67000625-d77aca80-f0e0-11e9-9a80-1c51814e962a.png)
Design:
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5d0b3b649d476859d60f62cb
![image](https://user-images.githubusercontent.com/45556620/67000692-f711f300-f0e0-11e9-83bf-7e2a88f8f413.png)

**Comment by Denis-Asipenko** [comment]
> Also let's put colour's name instead of "No name" in tag's name field (if user didn't add any name).

@DenisDemyanko please implement this

**Comment by Denis-Asipenko** [comment]
checked
