### ISSUE TITLE
Settings screens updates

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#287]
Update inner settings screens to match new design.
Screens:
Change password https://zpl.io/ad1vBwL https://zpl.io/boDgkdW
Clear data https://zpl.io/bzqnAvX
Node address https://zpl.io/2pvneqQ

**Comment by Denis-Asipenko** [comment]
Design:
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5cb962ed3ce4e433afcbd236
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5d8221145c120588c7110f31
![image](https://user-images.githubusercontent.com/45556620/67003408-866dd500-f0e6-11e9-880b-65eac29e758f.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/67003706-36dbd900-f0e7-11e9-98e8-c3a1f9456d2e.png)
