### ISSUE TITLE
Add Lock screen fictionality

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#288]
Add item on Settings screen https://zpl.io/25OMeK8
Add Lock time settings screen https://zpl.io/bAnJzMP

**Comment by Denis-Asipenko** [comment]
when you lock the screen, need to open the login screen, as implemented in the desktop wallet.
![image](https://user-images.githubusercontent.com/45556620/67196875-4f5c3400-f404-11e9-9b0a-316f48b28160.png)

**Comment by Denis-Asipenko** [comment]
Steps to reproduce behavior:
1. Go to wallet.
2. Go to "SETTINGS" screen.
3. Set the "Screen lock" for 15 seconds.
4. Roll up wallet.
5. After 15 seconds, expand the wallet and login.
6. Wait 15 seconds for the screen to lock.
Expected: Screen lock after 15 seconds.
Actual:  Screen doesn't lock after 15 seconds.
[video_2019-10-22_14-03-03.zip](https://github.com/BeamMW/ios-wallet/files/3755110/video_2019-10-22_14-03-03.zip)

**Comment by Denis-Asipenko** [comment]
Let's make as long as you move through the screens, the tabs of the wallet screens, then wallet should not be locked. As soon as no movement on the wallet does not occur, the timer started counting down 15 seconds or how much is set in the settings to lock the screen. 
Actual:
[video_2019-10-23_12-05-24.zip](https://github.com/BeamMW/ios-wallet/files/3761361/video_2019-10-23_12-05-24.zip)

**Comment by Denis-Asipenko** [comment]
checked
