### ISSUE TITLE
Transactions confirmations

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#289]
Add item on Settings screen https://zpl.io/25OMeK8 and minimum confirmations settings screen https://zpl.io/aRx3ORz
Add info about confirmations on Transaction details screen https://zpl.io/VkeXBWv and Share transaction details screen https://zpl.io/awPeoDM

**Comment by sasha-abramovich** [comment]
@DenisDemyanko talked with @beam-mw he said that this feature can be calculated from height differences
