### ISSUE TITLE
Default alerts in dark theme looks bad

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#292]
Can we make action's text on default alerts white? Now in dark iOS theme it looks bad 
![IMG_2110](https://user-images.githubusercontent.com/7249484/65748114-bfdda100-e135-11e9-9877-91ea64db5b94.PNG)
![IMG_2111](https://user-images.githubusercontent.com/7249484/65748115-bfdda100-e135-11e9-8638-048c48c7740c.PNG)

**Comment by Denis-Asipenko** [comment]
checked
