### ISSUE TITLE
Add 3D touch actions for transactions list

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#293]
Also add share in transactions actions with swipe

**Comment by alexandrashelenkova** [comment]
Screens are here 
https://zpl.io/2yPjDro
https://zpl.io/bzL5drG

**Comment by Denis-Asipenko** [comment]
Design:
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5d95636ef12c181635ba511b
![image](https://user-images.githubusercontent.com/45556620/67086884-73bcd400-f1aa-11e9-8b7c-f18280d45ca2.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/67086861-67d11200-f1aa-11e9-932e-c748bce214fb.png)

**Comment by DenisDemyanko** [comment]
it is not possible to add a cancel
tap outside the area will close the screen

**Comment by Denis-Asipenko** [comment]
checked
