### ISSUE TITLE
Easy onboarding

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#295]
Screens are here https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5d96c8768a04a81653621f97

1. Add "I will do it later" button on seed phrase screen, if user chooses that do not show seed phrase confirmation flow.
2. On main screen show Get beams and Secure your phrase cards (user can close it). Remove Transactions list header, leave only empty state icon and text (ability to go to Payment proof flow won't be here also by now until we will find a better place for that).
3. When user choose Get beams - show external link alert and send user back to the main screen (no get beams card anymore).
4. After user's balance reach 10 beams, the complete verification card couldn't be hidden anymore.
5. In settings add 2 items: Get beams from the community faucet (hide after user receives his first beams - even if not from the faucet) and Complete wallet verification (hide after user complete it). Reorganise\ items on Settings screen required too. Show seed phrase in settings until user complete verification

**Comment by Denis-Asipenko** [comment]
1.

> Add "I will do it later" button on seed phrase screen, if user chooses that do not show seed phrase confirmation flow.
![image](https://user-images.githubusercontent.com/45556620/69054077-e88a6480-0a1b-11ea-8f35-9a31b59c566c.png)

4. "Сomplete verification" card hidden.
> After user's balance reach 10 beams, the complete verification card couldn't be hidden anymore.
![image](https://user-images.githubusercontent.com/45556620/69054210-27b8b580-0a1c-11ea-8da0-8141d36dd9ff.png)

**Comment by Denis-Asipenko** [comment]
checked
