### ISSUE TITLE
Check buttons position on all screens

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#297]
Basic rule for all screen of login/restore flow and screen with one or 2 input fields:

**- if there's no need to type in anything and show keyboard - button should be on fixed height from the bottom of the screen (100 pt)**
examples
https://zpl.io/bJ7WOmE
https://zpl.io/29nAjve

**- if there're input fields, button should have fixed distance from input field (60 pt)**
examples
https://zpl.io/V4oYzD8
https://zpl.io/VKPDEjJ
https://zpl.io/2jMEMlr

**Exceptions:**
https://zpl.io/bJGod5x (error might be long so button should be 130 pt after input line)
https://zpl.io/2GyWQQd (on smallest screen there's not enough space to make height from the bottom of the screen 100 pt (for bigger screens it should be 100 pt though))

**Comment by Denis-Asipenko** [comment]
checked
