### ISSUE TITLE
"Logout" from wallet

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#298]
1. Add "Clear wallet" item in the settings https://zpl.io/VQvjoQ9
2. Add confirmation alert screen https://zpl.io/a3dx6mW

**Comment by alexandrashelenkova** [comment]
@DenisDemyanko after talk with Vika and Sasha, we decided to rename "Clear wallet" to "Remove current wallet". Also changed alert wording here https://zpl.io/a3dx6mW
Also please let's add password confirmation after this alert https://zpl.io/bADnlvo

**Comment by Denis-Asipenko** [comment]
Crashing the wallet when you use the "Remove current wallet".
 Steps to reproduce behavior:
1 Go to the "Settings" screen.
2. Tap button"Remove current wallet"
3. On the alert that appears, select "Remove wallet"
4. Enter password.
Expected: Removed current wallet.
Actual: Wallet crash.

**Comment by Denis-Asipenko** [comment]
Playable on version 4.4
> Crashing the wallet when you use the "Remove current wallet".
Steps to reproduce behavior:
1 Go to the "Settings" screen.
2. Tap button"Remove current wallet"
3. On the alert that appears, select "Remove wallet"
4. Enter password.
Expected: Removed current wallet.
Actual: Wallet crash.

> 
[video_2019-11-13_15-14-45.zip](https://github.com/BeamMW/ios-wallet/files/3841021/video_2019-11-13_15-14-45.zip)

**Comment by Denis-Asipenko** [comment]
checked
