### ISSUE TITLE
Change "Add All" (sending screen) view

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#300]
Made Add all button less visible https://zpl.io/amdEkAv
Also let's make it inactive if All funds already inputed in amount field https://zpl.io/br0vLg3

**Comment by alexandrashelenkova** [comment]
@sasha-abramovich please have a look at the screen so @dariatarakanova can do it for android as well.

**Comment by Denis-Asipenko** [comment]
design:
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5daee8d33b7725126d1c65aa
![image](https://user-images.githubusercontent.com/45556620/68118281-a7209200-ff10-11e9-8793-1f95855ec1e9.png)
actual:
![image](https://user-images.githubusercontent.com/45556620/68118298-b0116380-ff10-11e9-8359-9e7fed83a34d.png)

**Comment by Denis-Asipenko** [comment]
checked
