### ISSUE TITLE
Export / import transaction history, tags and addresses (in settings)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#306]
- Add "Export wallet data" and "Import wallet data" on Settings screen https://zpl.io/VQvjoQ9
- If user choses export, open this screen https://zpl.io/aBdRNrK (by default all items in the list should be selected). Next open default export screen 
![export data destination](https://user-images.githubusercontent.com/7249484/67277615-c58e9280-f4f9-11e9-937a-32ed95155adc.png)
- If user chooses Import open Files screen 
![IMG_3356](https://user-images.githubusercontent.com/7249484/67277646-d7703580-f4f9-11e9-825a-9a7e49372e36.PNG)
- Import alerts are here https://zpl.io/VY1rk3L https://zpl.io/bzjq1KM

**Comment by alexandrashelenkova** [comment]
@sasha-abramovich when you have time, please take a look at the screen so @dariatarakanova can do it for other platforms.

**Comment by alexandrashelenkova** [comment]
@sasha-abramovich main screens design is ready. Let't discuss some task details with developers when you have time.

**Comment by sasha-abramovich** [comment]
talked to @DenisDemyanko today, it looks like the most recent version of the transaction can always be displayed as we have transaction_id and last_modification_date

we seem to be good :)

**Comment by Denis-Asipenko** [comment]
@dariatarakanova Need to do an alert or add the info on the screen, that import is possible only in the wallet from which was made from export.

**Comment by dariatarakanova** [comment]
> @dariatarakanova Need to do an alert or add the info on the screen, that import is possible only in the wallet from which was made from export.

Show this alert after tap on "Import wallet data" https://zpl.io/2GR6zZd

**Comment by Denis-Asipenko** [comment]
@DenisDemyanko When export\import contacts don't transfer.

**Comment by Denis-Asipenko** [comment]
@DenisDemyanko We need to show an error warning if data has been imported into the wallet with another seed phrase.

**Comment by Denis-Asipenko** [comment]
When import addresses and contacts without tags which were assigned to them earlier displayed "None". I think we need doesn't display "None" in this case. 
![image](https://user-images.githubusercontent.com/45556620/70605433-8af8ca80-1c0b-11ea-9eee-aea189d7bdf5.png)

**Comment by Denis-Asipenko** [comment]
checked
