### ISSUE TITLE
Payment proof (if transactions list is empty)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#308]
- Add item "Payment proof" in settings https://zpl.io/25OMeK8 (Setting have to be regrouped as weel, with new section UTILITIES)
- Item should open Payment proof screen https://zpl.io/b6xM6jW
- If transactions list is empty, Payment proof would be available only from Settings ("Transactions" header should be removed in this task https://github.com/BeamMW/ios-wallet/issues/295)
- If there are transactions in the wallet, Payment proof would be available from Settings and Transactions list screen.

**Comment by alexandrashelenkova** [comment]
@sasha-abramovich when you have time, please take a look at the screens, so @dariatarakanova can do this task for other platforms.

**Comment by Denis-Asipenko** [comment]
checked
