### ISSUE TITLE
Add "Copy details" to transaction details actions

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#309]

**Comment by dariatarakanova** [comment]
Design: https://zpl.io/29zoBYp
Please also add "Copy details" to transactions list 3d touch: https://zpl.io/bzL5drG

Transaction details should copy as text.
Example: https://zpl.io/V1pzoWQ

**Comment by DenisDemyanko** [comment]
please note that we do not share comments and names of contacts

**Comment by Denis-Asipenko** [comment]
checked
