### ISSUE TITLE
Add version number on login/restore screens

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#312]
Currently version number user can see only on very first screen https://zpl.io/aXP3K3p
Let's also add it on:

- Input password screens (while login to existed wallet) https://zpl.io/VqYYZ3Z
- Restore and creating wallet loading screens https://zpl.io/bz63Kll https://zpl.io/bljL1q1

**Comment by Denis-Asipenko** [comment]
checked
