### ISSUE TITLE
Update Beam Wallet app icon

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#318]
Please update Beam wallet app icon for
Mainnet - https://drive.google.com/drive/u/1/folders/1s6eI2YASeMWv0rLXUlh0qK5Uk5vQxGWv
Testnet - https://drive.google.com/drive/u/1/folders/16o45T9tAxnqf6kiiflAIrALuFeEmvCml
Masternet - https://drive.google.com/drive/u/1/folders/1T-7lbKz9N-3tT5krDXBde483NwqlgJlE

**Comment by Denis-Asipenko** [comment]
design:
https://drive.google.com/drive/u/1/folders/16o45T9tAxnqf6kiiflAIrALuFeEmvCml
![image](https://user-images.githubusercontent.com/45556620/68112176-d5e33c00-ff01-11e9-8236-c6e4eca77e54.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/68112108-b0563280-ff01-11e9-91fc-36c2ba8b5fd0.png)

**Comment by Denis-Asipenko** [comment]
checked on masternet
version: 4.0.1
