### ISSUE TITLE
Dark mode for wallet

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#319]

**Comment by Alesio7** [comment]
Looking forward to this. Here's some inspiration.
![65392277-ec15ae00-dd40-11e9-88ff-577d70038ac4](https://user-images.githubusercontent.com/41215180/68077843-900f6200-fda1-11e9-9c8a-1b37d4c0f52a.jpg)

**Comment by dariatarakanova** [comment]
Color specification:

1) Background on all pages - #000000 (rgb 0 0 0)
2) All text boxes - rgb 20 20 20
![image](https://user-images.githubusercontent.com/47353570/68126737-1b613280-ff1d-11e9-94a9-75b86de564c6.png)

3) Color for colorful button's text and icons - rgb 28 28 30
![image](https://user-images.githubusercontent.com/47353570/68126813-477cb380-ff1d-11e9-9151-6976a7d0e888.png)

4) Gradient at the top of screen - should have opacity 85% from current colors
![image](https://user-images.githubusercontent.com/47353570/68126917-7dba3300-ff1d-11e9-8c41-08a2c2c1447c.png)

5) Titles H2 + transaction comment text + dates on transaction screen + comments (besides send and receive screen) - should be rgb 142 142 147
![image](https://user-images.githubusercontent.com/47353570/68127158-f9b47b00-ff1d-11e9-95f3-0a319195ba5d.png)

6) Shadow under alert should be - rgba 0 0 0, 0.4
![image](https://user-images.githubusercontent.com/47353570/68127520-ba3a5e80-ff1e-11e9-9089-5b541361b863.png)

7) Alert box color - rgb 28 28 30
Separator's color - rgb 72 72 74
![image](https://user-images.githubusercontent.com/47353570/68127582-d50cd300-ff1e-11e9-82b0-7ec98e845c26.png)

8) Action sheet background - rgb 44 44 46
![image](https://user-images.githubusercontent.com/47353570/68128037-aba07700-ff1f-11e9-9c1b-b79e02a27f1a.png)

Screen examples here: https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5dbc2700e1948c239ca23fd8

**Comment by gingervik** [comment]
@Denis-Asipenko QA will not check it - approved
