### ISSUE TITLE
Share transaction details image - Kernel ID goes beyond bottom edge

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#320]
Please make the image size depends on content. 

![image](https://user-images.githubusercontent.com/47353570/68017870-6d495480-fca0-11e9-86d0-d3c9dfce1a0b.png)

**Comment by Denis-Asipenko** [comment]
Checked on testnet.
Version: 4.4
Device: iPhone 8 
![image](https://user-images.githubusercontent.com/45556620/68759579-02ddd000-0621-11ea-8d08-6f9fde5f1f5a.png)
