### ISSUE TITLE
App Crashes When Deleting Transaction - iOS 13.1.3 - iPhone 7 Plus

### ISSUE THREAD

**Issue by Alesio7** [BeamMW/ios-wallet#321]
On the main screen, if I swipe on a past transaction to delete it, the app crashes. It doesn't matter whether it was a received, sent, or expired transaction, it will crash. This happens every time. I have sent 4+ crash reports

![IMAGE 2019-11-11 19:05:35](https://user-images.githubusercontent.com/41215180/68630740-436d0a80-04b6-11ea-87b7-5c31e9ffbbd3.jpg)
![IMAGE 2019-11-11 19:05:36](https://user-images.githubusercontent.com/41215180/68630742-4536ce00-04b6-11ea-9e04-c1bd28c75708.jpg)

**Comment by Denis-Asipenko** [comment]
checked on testnet.
Version: 4.4
