### ISSUE TITLE
Make sections on Settings screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#323]
To avoid long scroll on Settings screen please make sections with inner screens:
![image](https://user-images.githubusercontent.com/47353570/68206133-9cc7cc00-ffd4-11e9-8498-81ecf7e4b3bf.png)

All screens are here:
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5dc06c1ec73df203b4dd8b83

**Comment by Denis-Asipenko** [comment]
Align the indicator to the center.
![image](https://user-images.githubusercontent.com/45556620/68746899-90fa8c00-060a-11ea-9801-3c385ba7f582.png)

**Comment by Denis-Asipenko** [comment]
checked
