### ISSUE TITLE
Show seed phrase - create screens

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#326]
1) Add item menu "Show seed phrase" on screen Settings/Privacy -  https://zpl.io/blkg88X
2) Next open screen with face/touch id and then password - https://zpl.io/awgN9RN  https://zpl.io/VKQO5e6 https://zpl.io/2Zm68ew
3) Next show screen with seed phrase https://zpl.io/2j7geAp

**Comment by DenisDemyanko** [comment]
This option should be available only if the user has not completed verification.
after a verification or if the user restore the wallet, this options should be hidden

**Comment by Denis-Asipenko** [comment]
Bug.
Balance 100.99999699 B and the option "completed verification" is available.
Str:
1. On the main screen tap "Completed verification" button.
2. Use your Touch ID\Face ID.
3. Enter your password.
4. Confirm seed phrase.
Expected: verification completed.
Actual: Сrash of the wallet.
Note: After the crash of the wallet option "completed verification" isn't available(in Settings and the main screen).

**Comment by Denis-Asipenko** [comment]
Requests to complete the verification,  although I restore the wallet.
![image](https://user-images.githubusercontent.com/45556620/69040380-c2a29700-09fe-11ea-8019-e5ca46833b93.png)

**Comment by Denis-Asipenko** [comment]
checked
