### ISSUE TITLE
Change gradient color of side menu

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#328]
Colors should be the same as on design: https://zpl.io/2yP9ByL

Now gradient looks like from testnet:
![IMG_8568](https://user-images.githubusercontent.com/47353570/68312701-20a8b380-00bc-11ea-90f3-2cdbc20cd3e2.PNG)

**Comment by Denis-Asipenko** [comment]
darker than on the design
![image](https://user-images.githubusercontent.com/45556620/70814213-16c15100-1ddc-11ea-9b91-41ad31d3babf.png)

**Comment by Denis-Asipenko** [comment]
checked
