### ISSUE TITLE
Align text on buttons to center

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#329]
Please align text+icon to the center of buttons "change", "next", "add all", "show QR", "share address"  etc...

![IMG_8584](https://user-images.githubusercontent.com/47353570/68313096-b47a7f80-00bc-11ea-852a-cdd9eb572644.PNG)
![IMG_8569](https://user-images.githubusercontent.com/47353570/68313103-b6dcd980-00bc-11ea-8824-9420ea3d26c1.PNG)

**Comment by Denis-Asipenko** [comment]
checked
