### ISSUE TITLE
Change background shadow under popups (alerts)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#330]
Background shadow should be:
- on send screen https://zpl.io/V1QM19k
- on receive screen https://zpl.io/am5MNAQ
- on other screens https://zpl.io/bzjPPe3 

so everywhere it should be blured background (rgba 2 37 60, 0.3)

Now it looks like this:
![IMG_8583](https://user-images.githubusercontent.com/47353570/68313403-35397b80-00bd-11ea-926f-7185098bebab.PNG)

![IMG_8582](https://user-images.githubusercontent.com/47353570/68376812-ef7ac280-0151-11ea-8e54-c2f10ee4ddcb.PNG)

**Comment by Denis-Asipenko** [comment]
**TRANSACTION SCREEN**
![image](https://user-images.githubusercontent.com/45556620/68757150-821cd500-061c-11ea-8387-b88188dfa04a.png)
**TRANSACTION DETAILS**
![image](https://user-images.githubusercontent.com/45556620/68757288-c27c5300-061c-11ea-8c9a-c35c341f759a.png)
**I think background should be blurred.**  
![image](https://user-images.githubusercontent.com/45556620/68757747-80074600-061d-11ea-98c4-4bb5b8bc8a23.png)
**ADDRESSES SCREEN**
![image](https://user-images.githubusercontent.com/45556620/68757971-ef7d3580-061d-11ea-82b6-a3aabc60a6c6.png)

**Comment by Denis-Asipenko** [comment]
checked
