### ISSUE TITLE
Different text color on action sheet 

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#331]
On iOS dark mode: some text white, some text blue.
Text should be white color except "delete transaction" "delete address" etc. text color (red)
![IMG_8586](https://user-images.githubusercontent.com/47353570/68314385-c1986e00-00be-11ea-9c20-941e23b893f8.PNG)
![IMG_8588](https://user-images.githubusercontent.com/47353570/68314392-c3fac800-00be-11ea-945a-f343fc098a31.PNG)

On iOS light mode the same: some text dark (as on design) and some also blue.
Text should be dark color (https://zpl.io/bzL5drG) except "delete transaction" "delete address" etc. text color (red)

**Comment by Denis-Asipenko** [comment]
checked
