### ISSUE TITLE
RU localization - long phrases

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#332]
1) **If translated text is longer than EN place "..." only in the end of phrase, not in the middle**

Example: " Cоздать метку". 
In wallet it looks like "Созд...етку"
Should be: "Создать мет..." or replace with "Метка" (only in this case)

![IMG_8581](https://user-images.githubusercontent.com/47353570/68394174-07643d80-0176-11ea-97bd-e256f496d732.PNG)

2) Same issue on "Lock screen". Should be "Блокировать экр..."
![IMG_8580](https://user-images.githubusercontent.com/47353570/68394462-8fe2de00-0176-11ea-8c8e-891cc2a9f2b0.PNG)

3) "Owner screen" --- should be "Показать ключ..."

4) "Edit address"  -  just "Редактировать"

**Comment by Denis-Asipenko** [comment]
checked
