### ISSUE TITLE
RU localization - Replace words

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#333]
I have found some words that doesn't looks good in wallet context. I am sure you know about this, but maybe we can do it this time? @gingervik  @alexandrashelenkova 

1) Replace "ПОДРОБНОСТИ" with "ДЕТАЛИ"
![IMG_8613](https://user-images.githubusercontent.com/47353570/68395557-97a38200-0178-11ea-8889-a9779cb217f2.PNG)

2) Replace "Мои просро..."  with "Просроченные" ("Просрочен...")
![IMG_8610](https://user-images.githubusercontent.com/47353570/68395631-c6b9f380-0178-11ea-8056-e0fa51847da7.PNG)

3) Replace "Сдача" with "Изменить"
![IMG_8615](https://user-images.githubusercontent.com/47353570/68395720-fbc64600-0178-11ea-90f4-0cc060f7643f.PNG)

**Comment by Denis-Asipenko** [comment]
checked
