### ISSUE TITLE
Address expire notification

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#335]
There are 2 ways to show notification:

1) Show notification if user is not in the wallet - https://zpl.io/2yGM76L. After tap user gets to Addresses screen.
2) Show notification if user is in the wallet - https://zpl.io/bPDNdgM. Show this notification 5 seconds and automatically hide.

**Comment by alexandrashelenkova** [comment]
- On addresses screen we also need to show which addresses would be expired soon. And this screen we should open only if few addresses expired soon.
- If only one address is expired soon - open that address detail screen.
- Usually we have these snack bars on the bottom of the screen. @dariatarakanova why you want to put it on top of the screen in this case?

**Comment by sasha-abramovich** [comment]
we won't do it, it will produce too many notifications and save users' hassle only in limited number of cases
