### ISSUE TITLE
Update Beam logo

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#337]
We had some lettering issue so please update Beam logo to the updated one on all screens where it is:

- initialization screens
- restore screens
- side menu screens
- share transaction details screen https://zpl.io/awPeoDM

Please take logo from https://zpl.io/aXP3K3p (large) and from https://zpl.io/bljL1q1 (small).

**Comment by Denis-Asipenko** [comment]
On this screen, https://zpl.io/aXP3K3p logo seems low resolution.

**Comment by Denis-Asipenko** [comment]
checked
