### ISSUE TITLE
Add "restore wallet or create a new one" link to testnet v4.5

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#339]
Example https://zpl.io/VKPDEjJ

How it looks now:
![image](https://user-images.githubusercontent.com/47353570/68776794-54925480-0639-11ea-970a-9acaf93e6e7e.png)

**Comment by DenisDemyanko** [comment]
@dariatarakanova 
it is already implemented. but you opened the lock screen, which is set in the settings. On the unlock screen, it should not be possible to do something with the wallet

**Comment by Denis-Asipenko** [comment]
checked
