### ISSUE TITLE
Add an item for selection "Delete all tags" in  "CLEAR DATA" screen. 

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/ios-wallet#346]
Also, please note that you need to make changes to the alert. 
![image](https://user-images.githubusercontent.com/45556620/70603286-3ce1c800-1c07-11ea-9c5f-a88bc903edd6.png)

**Comment by dariatarakanova** [comment]
Design: https://zpl.io/bzqnAvX
Alert: https://zpl.io/bA7EZ8x

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/70713733-ab9e4e80-1cf7-11ea-9a7b-788dcadceefb.png)

**Comment by Denis-Asipenko** [comment]
checked
