### ISSUE TITLE
Change the sentence on Seed phrase screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#352]
Change the sentence “From now on you won’t be able to see the seed phrase in settings” to “After successful verification, you won’t be able to see your seed phrase in settings”

![image](https://user-images.githubusercontent.com/47353570/71161942-f87fa900-2252-11ea-9179-9209c0ae6803.png)

**Comment by Denis-Asipenko** [comment]
checked
