### ISSUE TITLE
Add snackbar after alert "external link" on onboarding wallet screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#357]
1) Tap on "open" https://zpl.io/bWXWd9P
2) Close this alert https://zpl.io/bWXWd9P
3) Show screen https://zpl.io/anEemgY with countdown ( start from 4 sec). 
4) Then go to faucet web-site

Comment was updated 29/01

**Comment by dariatarakanova** [comment]
@Denis-Asipenko comment was updated according to telegram discussion

**Comment by Denis-Asipenko** [comment]
checked
