### ISSUE TITLE
Check "rate the app" alert

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#358]
Please check if there is scroll on "rate the app" alert.

Zaidelson said the he can see small scroll. here is his screenshot:
![image](https://user-images.githubusercontent.com/47353570/71177713-41485980-2275-11ea-8fbc-ba03d5e14868.png)

My screenshot look ok and there is no scroll on alert:
![image](https://user-images.githubusercontent.com/47353570/71177763-5e7d2800-2275-11ea-9461-8e1d19b87d93.png)

**Comment by Denis-Asipenko** [comment]
checked on iPhone 8.
