### ISSUE TITLE
Settings screen - node.

### ISSUE THREAD

**Issue by DenisDemyanko** [BeamMW/ios-wallet#361]
Guy Corem, [Jan 8, 2020 at 10:19:22 AM]:
iOS wallet is a little buggy but at least u have one

I sent feedback

On node setting screen

**Comment by DenisDemyanko** [comment]
[2020-01-14 15.08.48.mp4.zip](https://github.com/BeamMW/ios-wallet/files/4059244/2020-01-14.15.08.48.mp4.zip)

**Comment by Denis-Asipenko** [comment]
checked
