### ISSUE TITLE
Displaying the amount in second currency

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#368]
Please add second currency amount on next screens:

1) Settings screen - add second currency (usd / btc) - https://zpl.io/VxX5RPk
2) Main wallet screen - https://zpl.io/VxX5rl3
3) Send screens (amount + total available) - https://zpl.io/b6mYBWg
4) Transaction fee screen - https://zpl.io/VQ7g1Om (updated 08/04) and https://zpl.io/VqgB9NY
5) Transaction confirmation screen - https://zpl.io/aR7Q9rK
6) Receive screens - https://zpl.io/aR7Q9or and https://zpl.io/amvl71A
5) Transaction detail screens - https://zpl.io/adG81zL https://zpl.io/bej7Wkm
6) Share transaction details - https://zpl.io/2pXZP7j

**Comment by Denis-Asipenko** [comment]
We need to add the option "off"  in section " Show amount in"
![image](https://user-images.githubusercontent.com/45556620/83404779-edd95a80-a413-11ea-9906-d72a23632f2c.png)
Also, when there is no transmit of rates(our node does not broadcast for some reason), but the user has a secondary currency set in the settings, I suggest displaying a dash with the name of the currency, as it is done in the desktop wallet.
![image](https://user-images.githubusercontent.com/45556620/83406186-cb950c00-a416-11ea-81ef-6dfbcd8314f9.png)

**Comment by dariatarakanova** [comment]
Updated design with "off" choice
![image](https://user-images.githubusercontent.com/47353570/83410119-6d6c2700-a41e-11ea-8983-d6118db19a57.png)

**Comment by Denis-Asipenko** [comment]
1. Fix
![image](https://user-images.githubusercontent.com/45556620/83520259-12056c00-a4e6-11ea-9cb2-8909dba1658d.png)
2. add 
![image](https://user-images.githubusercontent.com/45556620/83520286-1e89c480-a4e6-11ea-9825-99b5189b7369.png)

**Comment by Denis-Asipenko** [comment]
checked
