### ISSUE TITLE
Create Notifications

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#374]
1) please add Notifications to side menu https://zpl.io/a80gDpx
2) create Notifications item in Settings https://zpl.io/awkRBAM and https://zpl.io/290QGYW
3) create Notifications screen https://zpl.io/aMgOdd7 . All read notifications https://zpl.io/VKzxlmE
4) create Notification details view for "update" notification https://zpl.io/a808NWg
5) create Notification details view for "in the press", "hot news" etc.. https://zpl.io/2G08KZE
6) after tap on "address" notification - open screen with address details https://zpl.io/2pJwAJy
7) after tap on "transaction" notification - open screen with transaction details https://zpl.io/bej7Wkm
8) Empty notifications screen https://zpl.io/adJdPXe
9) when privacy mode is on do not show amounts on notifications https://zpl.io/25BPwm0

When open Notifications first time new notifications should be highlighted (as on design https://zpl.io/aMgOdd7). Notifications become read when user open it or if he goes to another screen and then come back (https://zpl.io/VKzxlmE).

In-app notification https://zpl.io/25BRje3
- news
- updates (if the app do not update automatically after 1-2 days)

Push notification https://zpl.io/2G0Kqn3
- transactions (send, receive, failed)
- AS (completed, failed, expired)
- addresses (expired)

all screens here https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5ea6f40291822a2631a16cea

**Comment by Denis-Asipenko** [comment]
1. We need to remove the switcher "Address expiration", but notification of the expiration address to leave.
![image](https://user-images.githubusercontent.com/45556620/83421449-cb096f00-a430-11ea-90ec-e3ad61e5273b.png)
2. When the user selects "expired address now", the push notification is not displayed, but the notification is displayed on the notification screen as implemented in the desktop wallet.

**Comment by dariatarakanova** [comment]
Design for notification settings was also updated https://zpl.io/V4BmGdN
![image](https://user-images.githubusercontent.com/47353570/83426591-0c514d00-a438-11ea-8162-ab5196650c69.png)

**Comment by Denis-Asipenko** [comment]
checked
