### ISSUE TITLE
Support Lelantus-MW: unlinking flow

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#376]
Designs: https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5ebebb97197908318d7c58e2

1) Add icon on Available block (available and unlinked tabs) https://zpl.io/ag469yO
![image](https://user-images.githubusercontent.com/47353570/83398881-e82a4780-a408-11ea-8197-d2db7e8a8c90.png)

Unlinked tab:
![image](https://user-images.githubusercontent.com/47353570/83398921-f4aea000-a408-11ea-964d-fcb0b6dbef46.png)

2) If in the wallet 0 Beams and no unlinked do not show tabs and icon "unlinked" https://zpl.io/VOwpL9P

3) Create tab "unlinked" and show it only if there are unlinked funds in the wallet https://zpl.io/a35drwW 
![image](https://user-images.githubusercontent.com/47353570/83398981-11e36e80-a409-11ea-9520-ddd154b61852.png)

4) Unlinked tab view https://zpl.io/VQXdymR
![image](https://user-images.githubusercontent.com/47353570/83399007-20318a80-a409-11ea-925b-ab9321b58f3b.png)

5) If all funds in the wallet unlinked - make "unlinked" icon inactive https://zpl.io/VQXdymR
![image](https://user-images.githubusercontent.com/47353570/83399025-2889c580-a409-11ea-9227-246e4242b49f.png)

6) Create screen Unlink https://zpl.io/VDJW7RJ
![image](https://user-images.githubusercontent.com/47353570/83399112-4eaf6580-a409-11ea-9b24-283d53b7c882.png)

7) Create confirmation screen https://zpl.io/aRJGove 
![image](https://user-images.githubusercontent.com/47353570/83399157-61c23580-a409-11ea-9895-dd5b1e84a557.png)

8) When unlink "in progress" - show also %
![image](https://user-images.githubusercontent.com/47353570/83399177-6edf2480-a409-11ea-8c3b-e5dcb66e9391.png)

9) Unlink statuses icons https://zpl.io/b6xJ58q

10) Unlinked transaction details https://zpl.io/ag4OqEA
![image](https://user-images.githubusercontent.com/47353570/83399495-ffb60000-a409-11ea-8c37-7a6b9b5c5582.png)

11) Unlinking transaction details https://zpl.io/2EJxEdl
![image](https://user-images.githubusercontent.com/47353570/83399518-06dd0e00-a40a-11ea-8b60-33916d2d11aa.png)

12) Transaction details actions: https://zpl.io/V0Q5WGR and https://zpl.io/V0Q5neQ
![image](https://user-images.githubusercontent.com/47353570/83399560-18261a80-a40a-11ea-8596-620637b56ee3.png)

![image](https://user-images.githubusercontent.com/47353570/83399609-2bd18100-a40a-11ea-9692-677441a44662.png)

13) Stop unlinking alert https://zpl.io/b6dxenK
![image](https://user-images.githubusercontent.com/47353570/83399685-4b68a980-a40a-11ea-9a8c-26214373620b.png)

14) Swipe on wallet screen https://zpl.io/br50j1X 
![image](https://user-images.githubusercontent.com/47353570/83399710-56233e80-a40a-11ea-8778-1162387bccdf.png)

**Comment by Megawatt7** [comment]
Hello, is this only a design for now or an upcoming and accessible feature for the next iOS Eager Electron 5.0 update?

**Comment by dariatarakanova** [comment]
invalid
