### ISSUE TITLE
Add versions to generated token

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/ios-wallet#382]
Will need to check when the token will be implemented
https://github.com/BeamMW/beam/issues/1435

**Comment by DenisDemyanko** [comment]
This task can't be done in this release.
This big solution. We need implement assets.

**Comment by Denis-Asipenko** [comment]
@DenisDemyanko This task was not implemented in version 5.1(8). Please implement this task.

**Comment by Denis-Asipenko** [comment]
The text color should be gray. 
![image](https://user-images.githubusercontent.com/45556620/93208604-7c74ac00-f765-11ea-8f16-502beacbf196.png)
![image](https://user-images.githubusercontent.com/45556620/93208638-87c7d780-f765-11ea-9171-037e91dec944.png)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/95200354-e8878480-07e6-11eb-9d24-f8d00bf9f6e9.png)

**Comment by Denis-Asipenko** [comment]
checked
