### ISSUE TITLE
Add wallet ID to TX detail

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#386]
Please add wallet ID to TX detail https://zpl.io/VkeXBWv

![image](https://user-images.githubusercontent.com/47353570/83406204-d485dd80-a416-11ea-8afc-80133fdffd34.png)

and to shared transaction details img https://zpl.io/awPeoDM
![image](https://user-images.githubusercontent.com/47353570/83408175-e10c3500-a41a-11ea-9724-6204a2fed3b5.png)

**Comment by Denis-Asipenko** [comment]
@DenisDemyanko please, implement a new design
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5d3d4d4cdc820b0cf1501841
![image](https://user-images.githubusercontent.com/45556620/92566509-006df600-f285-11ea-89ac-178958680a34.png)

**Comment by Denis-Asipenko** [comment]
Please, align
![image](https://user-images.githubusercontent.com/45556620/93209432-cf029800-f766-11ea-8925-a890f55023ed.png)

**Comment by Denis-Asipenko** [comment]
checked
