### ISSUE TITLE
Show error in status when exchange rate for BTC/USD was not broadcasted

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#387]
Please show "yellow" status when exchange rate for BTC/USD wasn't received and hide second currency:
https://zpl.io/VDEB8NW

![image](https://user-images.githubusercontent.com/47353570/85408112-c6863100-b56c-11ea-8d01-82c1cc61e38f.png)

**Comment by Denis-Asipenko** [comment]
With the "yellow" status, the second currency is not hidden.
> Please show "yellow" status when exchange rate for BTC/USD wasn't received **and hide second currency:**

Current:
![image](https://user-images.githubusercontent.com/45556620/92453605-25506380-f1c8-11ea-81d7-41a097debd23.png)

**Comment by Denis-Asipenko** [comment]
checked
