### ISSUE TITLE
Update the text on restore flow screens

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#388]
1) We updated text for RESTORE WITH OWN NODE (advanced) section (title+description). But please check all the text: https://zpl.io/VDKvq8w 
![image](https://user-images.githubusercontent.com/47353570/83534233-40407700-a4f9-11ea-8c5c-10965f6f0a88.png)

2) Update text for automatic restore alert https://zpl.io/VY1pXDM
![image](https://user-images.githubusercontent.com/47353570/83534403-77af2380-a4f9-11ea-8d02-3b88f5f00863.png)

3) Update text for trusted node restore alert https://zpl.io/aR9zXAv
![image](https://user-images.githubusercontent.com/47353570/83534507-9a413c80-a4f9-11ea-821a-ede4741f6c2f.png)

4) Update the text in red box on restore wallet node screen https://zpl.io/bJGod5x
![image](https://user-images.githubusercontent.com/47353570/83561911-52361000-a521-11ea-88f0-f133a5a8b8d4.png)

5) Update the text in red box on restore wallet wrong node screen https://zpl.io/aRzDRQe
![image](https://user-images.githubusercontent.com/47353570/83564464-6ed44700-a525-11ea-837e-f76e68506f85.png)

6) Update the comment on Owner key screen 
![image](https://user-images.githubusercontent.com/47353570/83562236-e43e1880-a521-11ea-849b-4eb0084129e4.png)

7) Update the text on Not enough space for restore alert https://zpl.io/aRznQDE
![image](https://user-images.githubusercontent.com/47353570/83535070-43883280-a4fa-11ea-883f-84bf67a0a629.png)

8) Update the text the same as here. With "." and ":". https://zpl.io/bz63Kll
![image](https://user-images.githubusercontent.com/47353570/83535218-6d415980-a4fa-11ea-8709-b032c877bef2.png)

9) Update the text on restoring screen https://zpl.io/bJ7WOmE
![image](https://user-images.githubusercontent.com/47353570/83535440-9f52bb80-a4fa-11ea-9eba-45d83bc287f8.png)

**Comment by Denis-Asipenko** [comment]
checked
