### ISSUE TITLE
Remove "News" from Notifications (settings+notifications screens)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#389]
Settings: https://zpl.io/V4BmGdN

Also remove from notification screen

**Comment by Denis-Asipenko** [comment]
The "news" switch has not been removed in the settings.
![image](https://user-images.githubusercontent.com/45556620/92392982-ce934d00-f127-11ea-8b05-f1e9fd0659fc.png)
![image](https://user-images.githubusercontent.com/45556620/92393060-ec60b200-f127-11ea-9071-83db83d71267.png)

**Comment by Denis-Asipenko** [comment]
checked
