### ISSUE TITLE
Receive lelantus

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#392]
Please create lelantus flow for Receive https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5ee3512322adbdb5a77b935d

1) Permanent token https://zpl.io/aRJynQe
![image](https://user-images.githubusercontent.com/47353570/84490856-65c54180-acac-11ea-9288-1b223de6aec1.png)

2) One-time use token https://zpl.io/advBdW1
![image](https://user-images.githubusercontent.com/47353570/84491034-a2913880-acac-11ea-96bf-e2aeebccaf22.png)

3) All hide view https://zpl.io/VKZmx1R
![image](https://user-images.githubusercontent.com/47353570/84491099-b3da4500-acac-11ea-8f74-b17f5da1d706.png)

4) Permanent/ One-time use (general) selection https://zpl.io/29xB7vz
![image](https://user-images.githubusercontent.com/47353570/84491162-c81e4200-acac-11ea-8a31-97235791268c.png)

5) Receive from (advanced) selection https://zpl.io/boQ53og
![image](https://user-images.githubusercontent.com/47353570/84491274-f6038680-acac-11ea-84f2-1e21be7f8f9c.png)

6) Show token https://zpl.io/bLl79Ld
![image](https://user-images.githubusercontent.com/47353570/84491342-129fbe80-acad-11ea-9d45-46d4f323d10a.png)

7) Show QR code https://zpl.io/VQXrNom
![image](https://user-images.githubusercontent.com/47353570/84491403-2814e880-acad-11ea-92c7-c8521dc0550e.png)

**Comment by dariatarakanova** [comment]
**UPD:** @DenisDemyanko please follow this instruction

1) Permanent token - General and receive from view https://zpl.io/aRJynQe
![image](https://user-images.githubusercontent.com/47353570/85120168-89980280-b22b-11ea-92f4-85bbbb3c2800.png)

2) One-time use token - General and receive from view https://zpl.io/advBdW1

3) Hidden view https://zpl.io/VKZmx1R
![image](https://user-images.githubusercontent.com/47353570/85120478-f4493e00-b22b-11ea-93d3-b13c66f93914.png)

4) Show token https://zpl.io/bLl79Ld
![image](https://user-images.githubusercontent.com/47353570/85120452-edbac680-b22b-11ea-8584-611009413c3d.png)

5) Share QR https://zpl.io/VQXrNom
![image](https://user-images.githubusercontent.com/47353570/85120434-e85d7c00-b22b-11ea-8d33-08c6218f5cef.png)

**Comment by Denis-Asipenko** [comment]
invalid
