### ISSUE TITLE
Status for downed random node

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#398]
New status for situation when random node is down: https://zpl.io/2p6ppgM
![image](https://user-images.githubusercontent.com/47353570/87050695-4831bc00-c207-11ea-85d6-fc8f9367d230.png)

**Comment by Denis-Asipenko** [comment]
When connecting to a node that was unavailable, the wallet did not reconnect to another random node for more than 2 minutes.

![image](https://user-images.githubusercontent.com/45556620/92491958-80e81480-f1fb-11ea-9f1a-d3a337c5e77c.png)

**Comment by Denis-Asipenko** [comment]
checked
