### ISSUE TITLE
Status + TX details for Max privacy transactions

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#401]
Status flow for max privacy tx: changing - in progress - sent

1) Changing status https://zpl.io/bAow1Ln
![image](https://user-images.githubusercontent.com/47353570/87424564-d4b3f400-c5e4-11ea-861e-e46d866fe81e.png)

2) TX detail for Max privacy transactions https://zpl.io/2GK508Y
![image](https://user-images.githubusercontent.com/47353570/87424636-f8773a00-c5e4-11ea-9a8e-16a10e65c294.png)
![image](https://user-images.githubusercontent.com/47353570/87424666-04fb9280-c5e5-11ea-80c9-2b983f9d7d15.png)

**Comment by dariatarakanova** [comment]
@DenisDemyanko i/ve updated design (adder tx type and token type) https://zpl.io/2GK508Y

**Comment by Denis-Asipenko** [comment]
irrelevant
