### ISSUE TITLE
Send screen - new flow with Max privacy transactions

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#402]
Designs: https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5f1ab75536c1163757c059a3

Types of transactions:
_Regular / One-time use
Regular / Permanent_

_Max privacy (online and offline token) / One-time use
Max privacy (online and offline token) / Permanent_

Offline token - include 20 vouchers that can be updated automatically when they are end. or sender can ask receiver directly to send him new token with new 20 vouchers

1) Regular / one-time use https://zpl.io/a3nNmLx
- Rename Send to to Transaction info.
- Add Max privacy + switcher (here:off)
- Advanced - Outgoing address: add "type" 
- Transaction fee for regular (not max privacy) is 100 GROTH

Screenshot: https://prnt.sc/tntq36

2) Max privacy / one-time use https://zpl.io/aXxQlGE
- Max privacy + switcher (here:on) + comment under "Transaction is slower, fees are higher."
- Transaction fee for max privacy is 1,200,000 GROTH
https://prnt.sc/tntrjw

3) Max privacy / permanent. When token do not saved in to address book display text "Permanent token."  https://zpl.io/bAozeEP

4) Max privacy / permanent. When token SAVED in to address book display text contact name+tags https://zpl.io/agYZlNM
https://prnt.sc/tntsxd

5) Fee error - when user wants to reduce the fee for max privacy transaction.Button "next" is inactive. https://zpl.io/aXxQl3j
https://zpl.io/aXxQl3j

6) Receiver requested max privacy (online token) transaction https://zpl.io/aBxgXWe
https://prnt.sc/tntu3t

7) Receiver requested max privacy (offline token) transaction.  https://zpl.io/boq5w6W 
https://prnt.sc/tnturc

8) Confirmation screen https://zpl.io/a87zgZg
https://prnt.sc/tntzsl

9) Show token https://zpl.io/blqnGxG
https://prnt.sc/tntzi1

**Comment by dariatarakanova** [comment]
@DenisDemyanko please make some updates (transaction type, token type) - https://zpl.io/a87zgZg
![image](https://user-images.githubusercontent.com/47353570/88664796-495b5800-d0e6-11ea-92f6-b587e7dc6088.png)

**Comment by Denis-Asipenko** [comment]
@DenisDemyanko changes were made to the send screen, please implement them.
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5f1ab75536c1163757c059a3

**Comment by Denis-Asipenko** [comment]
Bug.
**To Reproduce**
Steps to reproduce the behavior:
1. Go to the Send screen.
2. Scroll down the screen.
3. Select "edit address".
4. Scroll down the screen.
5. Add tag.
6. Enter a name to address.
![image](https://user-images.githubusercontent.com/45556620/95611639-c30aad00-0a6a-11eb-91d5-f0670da0a276.png)

**Comment by Denis-Asipenko** [comment]
In "CONFIRMATION" screen need to add "Transactions remaining".
![image](https://user-images.githubusercontent.com/45556620/95871159-02d8d980-0d76-11eb-91fc-2e3b8d21fbb2.png)

**Comment by Denis-Asipenko** [comment]
checked
