### ISSUE TITLE
Send screen - choose another currency (equivalent to BEAM)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#403]
1) Add arrow near BEAM/USD/BTC currency https://zpl.io/bPGlwwD
![image](https://user-images.githubusercontent.com/47353570/88388240-cae87880-cdbc-11ea-94c0-2929d295f323.png)

2) Choose currency screen https://zpl.io/aR5ylKp
![image](https://user-images.githubusercontent.com/47353570/88388303-ebb0ce00-cdbc-11ea-8c26-f18e087fb408.png)

**Comment by Denis-Asipenko** [comment]
checked
