### ISSUE TITLE
Receive screen - new flow with max privacy transactions

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#404]
Design: https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5f1ed1f2ab9a393acc565e63
Add "Edit token" setting only for permanent token.

1)Regular / one-time use https://zpl.io/25WN1JW
![image](https://user-images.githubusercontent.com/47353570/88643897-f627dc00-d0ca-11ea-9d76-0cf63da7b1ea.png)

2) Max privacy / one-time use https://zpl.io/VkjKoeg
![image](https://user-images.githubusercontent.com/47353570/88643951-08097f00-d0cb-11ea-9891-1a3333e81a36.png)

3) Regular / permanent https://zpl.io/b6rJmnd
![image](https://user-images.githubusercontent.com/47353570/88644444-a3025900-d0cb-11ea-8e5a-75060ec521ab.png)

4) Max privacy / permanent https://zpl.io/2jGp93m
![image](https://user-images.githubusercontent.com/47353570/88644493-b57c9280-d0cb-11ea-9726-3592e5c47092.png)

5) After click on "share address" display action sheet with different tokens https://zpl.io/aXBK1m8
![image](https://user-images.githubusercontent.com/47353570/88644638-e361d700-d0cb-11ea-9d44-654cd4f53430.png)

6) QR code https://zpl.io/VQwM7g5
![image](https://user-images.githubusercontent.com/47353570/88644669-eeb50280-d0cb-11ea-8886-91b7ef472ce4.png)

7) Show token https://zpl.io/2GK38oY
![image](https://user-images.githubusercontent.com/47353570/88644700-f70d3d80-d0cb-11ea-9f13-64163760c949.png)

**Comment by Denis-Asipenko** [comment]
1. Transaction type: Max privacy.
After tap on "share address"  :
![image](https://user-images.githubusercontent.com/45556620/93575793-bf6f9300-f9a2-11ea-9ffd-3730a0248a93.png)
2.  Need to align and add icon QR code.
![image](https://user-images.githubusercontent.com/45556620/93575884-de6e2500-f9a2-11ea-9bba-d83c5ab64ea6.png)
3. Jumping when entering an amount.
![D7110005-FE67-454F-A4FD-A7E4CC78326F](https://user-images.githubusercontent.com/45556620/93576228-54728c00-f9a3-11ea-9414-364fd8337427.GIF)

**Comment by Denis-Asipenko** [comment]
Bug.
**To Reproduce**
Steps to reproduce the behavior:
1. Go to the Receive screen.
2. Switch the switch to "permanent".
3. Scroll down.
4. Select the edit address.
5.  Scroll down.
6. Add tag.
5. Enter a name to address.
![C8645860-8BCB-4D10-916F-2CD342E70BF8](https://user-images.githubusercontent.com/45556620/95610703-6490ff00-0a69-11eb-94c5-5255ec90e59c.GIF)

**Comment by Denis-Asipenko** [comment]
checked
