### ISSUE TITLE
Add button to wallet status "cannot connect to: (node _address)" when specific node is selected

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#406]
Design: https://zpl.io/bzr15K3

When wallet cannot connect to specific node please show this status + button "change". Button leads to settings/node, so user can change the node manually

![image](https://user-images.githubusercontent.com/47353570/93599060-39fdda00-f9c6-11ea-96e4-cbf131bad9e5.png)

**Comment by Denis-Asipenko** [comment]
checked
