### ISSUE TITLE
Remove the online address and rename max privacy to offline

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/ios-wallet#407]

**Comment by dariatarakanova** [comment]
Receive screen: https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5f1ed1f2ab9a393acc565e63

Send: https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5f1ab75536c1163757c059a3

**Comment by Denis-Asipenko** [comment]
checked
