### ISSUE TITLE
Receive screen - change text about fee for offline transactions

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#411]
https://zpl.io/VkjKoeg

This text only for offline txs.
Please change text about fee to "To spend the received coins the min transaction fee will be ~0.01 BEAM."

![image](https://user-images.githubusercontent.com/47353570/95182043-c54fdb80-07cc-11eb-9b20-35dbff360550.png)

For regular tx the text is old "For the transaction to complete, you should get online during the 12 hours after Beams are sent."

**Comment by Denis-Asipenko** [comment]
checked
