### ISSUE TITLE
Offline transaction status example

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#412]
https://zpl.io/VqWLnGl

all icons here https://zpl.io/b6xJ58q

**Comment by Denis-Asipenko** [comment]
1) Fix icon
2) Fix status
![image](https://user-images.githubusercontent.com/45556620/95198825-862d8480-07e4-11eb-85da-197bb0b35fe0.png)

**Comment by Denis-Asipenko** [comment]
checked
