### ISSUE TITLE
UTXO screen - changes

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#415]
UTXO screens: https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5c90763dd42659058d1efbc2

1) Status and date move below amount  and add type to the right side https://zpl.io/VKj7K18 , https://zpl.io/V0grRxl , https://zpl.io/bz6dA08 , https://zpl.io/bz6dA08
![image](https://user-images.githubusercontent.com/47353570/95303859-6ce01300-088c-11eb-877b-a483d1aac210.png)

2) Please add Maturity and Type to UTXO details https://zpl.io/2jYMBWx

3) Please remove comments from UTXO screen https://zpl.io/2jYMBWx and leave it only on UTXO details screen https://zpl.io/2jYMBWx
![image](https://user-images.githubusercontent.com/47353570/95303959-9305b300-088c-11eb-8789-6d34bdfb4c58.png)

**Comment by Denis-Asipenko** [comment]
checked
