### ISSUE TITLE
Notifications about offline tx's

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#416]
Design: https://zpl.io/2G08e0J

![image](https://user-images.githubusercontent.com/47353570/95306040-8171da80-088f-11eb-9d5d-18cb0ff81705.png)

**Comment by Denis-Asipenko** [comment]
Current:
build 5.1.24
![image](https://user-images.githubusercontent.com/45556620/95330613-74fe7980-08b1-11eb-9dca-5c8692fa06a9.png)

**Comment by Denis-Asipenko** [comment]
checked
