### ISSUE TITLE
Receive screen - Show address: change order of text 

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#419]
Please make it in the same order on receive screen.

For regular tx: https://zpl.io/VQkl8mR
- Transaction type - first
- Address expiration - second

For offline tx: https://zpl.io/bzrKX5X
- Transaction type - first
- Transactions remaining - second
- Address expiration - third

**Comment by Denis-Asipenko** [comment]
@dariatarakanova update the layout. It must match the desktop wallet. After the update assign this issue on @DenisDemyanko  for implementing.

![image](https://user-images.githubusercontent.com/45556620/95569004-9f754180-0a2d-11eb-9a03-c3ceedf26340.png)

> For offline tx: https://zpl.io/bzrKX5X
> 
> * Transaction type - first
> * Transactions remaining - second
> * Address expiration - third

**Comment by Denis-Asipenko** [comment]
@DenisDemyanko implements according to the desktop wallet.
**Screenshots**
![image](https://user-images.githubusercontent.com/45556620/95756835-fdfd2280-0cae-11eb-8524-a6e563a3b880.png)
![image](https://user-images.githubusercontent.com/45556620/95756916-1bca8780-0caf-11eb-955f-dbc36d1a5b0e.png)
![image](https://user-images.githubusercontent.com/45556620/95756936-2258ff00-0caf-11eb-9fcb-36f09bc0ec1d.png)

**Comment by dariatarakanova** [comment]
Do we have address expiration for offline tx? I guess no...  @Denis-Asipenko 

@DenisDemyanko 
1) Offline https://zpl.io/bzrKX5X
2) Regular https://zpl.io/VQkl8mR

also in 5.2 will be changes on this screen

**Comment by Denis-Asipenko** [comment]
@dariatarakanova yes, address expiration: permanent
> Do we have address expiration for offline tx? I guess no... @Denis-Asipenko

**Comment by Denis-Asipenko** [comment]
checked
