### ISSUE TITLE
Addresses screen - Contact tab. Swipe should show "send" action not "receive"

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#420]
We can only send to "contact" https://zpl.io/2pE9Q7j and only receive to my "address" https://zpl.io/2vOGKO7

![image](https://user-images.githubusercontent.com/47353570/95443695-915bee00-0965-11eb-92dd-1235afcd4d1b.png)

**Comment by Denis-Asipenko** [comment]
Build 5.1.27
![image](https://user-images.githubusercontent.com/45556620/95462860-ba3dac80-0980-11eb-8d9e-18ed615ff71d.png)

**Comment by Denis-Asipenko** [comment]
checked
