### ISSUE TITLE
Send - Max privacy flow

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#425]
Send screens https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5f8d8d429ca8de6081c4976a

1) Offline address - https://zpl.io/bzrDvZl
2) Max privacy address - https://zpl.io/2jDBenm
3) Permanent - https://zpl.io/VOez9ZY
4) One-time use - https://zpl.io/agjMyPQ

5) Rename "Transaction comment" to "Comment"
6) Rename "show address" to "more details" 
![image](https://user-images.githubusercontent.com/47353570/96455767-550e7480-1226-11eb-998e-a5dacb5f1c15.png)

7) Send to contact. First address type, below contact https://zpl.io/a3LY7Gx
![image](https://user-images.githubusercontent.com/47353570/96456658-77ed5880-1227-11eb-8a75-4a6b005267df.png)

8) Please add descriptions for all empty fields (address, amount, comment) https://zpl.io/VYey6QJ Please display it from the beginning, not only after tap on field

**Comment by Denis-Asipenko** [comment]
2.
![image](https://user-images.githubusercontent.com/45556620/101477427-3f811580-3960-11eb-804b-576e4b9ea6c3.png)

![image](https://user-images.githubusercontent.com/45556620/101477362-2bd5af00-3960-11eb-80d6-680c4685e1dd.png)

**Comment by Denis-Asipenko** [comment]
checked

**Comment by Denis-Asipenko** [comment]
checked
