### ISSUE TITLE
Receive screen - Max privacy flow

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#426]
Screens: https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5f8d8eee9ca8de6081c4a2c7

1) Regular / one-time use - 3 addresses https://zpl.io/agjMLxD
2) Regular / permanent -  https://zpl.io/anxWA1r
3) Max privacy address - https://zpl.io/b6LY94N
4) Address details (after tap on "more details")
https://zpl.io/2ZeoGr4 , https://zpl.io/V4L3D5X , https://zpl.io/aMeYZpz , https://zpl.io/amoYKP6
5) Share address - https://zpl.io/Vx75yw3
6) Please add description for all empty fields (name/comment/amount) https://zpl.io/agjMLxD
7) Name and tag for address will be applied to used addresses after successful transaction.

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/101476870-7571ca00-395f-11eb-832e-3c251abc13f4.png)

**Comment by Denis-Asipenko** [comment]
When a user doesn't have a connection to a node with the owner key is the option to share an offline address
> 5. Share address - https://zpl.io/Vx75yw3

**Comment by Denis-Asipenko** [comment]
checked
