### ISSUE TITLE
Display Max privacy coins in AVAILABLE  block

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#427]
1) Create tab "Max privacy" https://zpl.io/VqWLnGl
2) Display there max privacy coins https://zpl.io/25LYNQ3
![image](https://user-images.githubusercontent.com/47353570/96574224-d6720f80-12d7-11eb-84d1-9a5d72e89173.png)

**Comment by Denis-Asipenko** [comment]
@dariatarakanova need to think through the design so that the user can track the time when the coin becomes available as it is implemented in the desktop wallet
![image](https://user-images.githubusercontent.com/45556620/101377970-8e2ca200-38c3-11eb-8156-d0f2d9bd21f5.png)

**Comment by dariatarakanova** [comment]
1) Please add tab "Max Privacy" to Available block https://zpl.io/25LYNQ3
![image](https://user-images.githubusercontent.com/47353570/101760938-39b43d00-3ae4-11eb-80c5-5820fd0e3626.png)

2) Please add button "more details" https://zpl.io/25LYNQ3
![image](https://user-images.githubusercontent.com/47353570/101760884-26a16d00-3ae4-11eb-8559-acf17c68d458.png)

3) More details screen https://zpl.io/VYlJgge
![image](https://user-images.githubusercontent.com/47353570/101761000-4df83a00-3ae4-11eb-92f1-245ab1dad7b8.png)

3.1) Create table with Amount and Latest unlocked time 
![image](https://user-images.githubusercontent.com/47353570/101761149-797b2480-3ae4-11eb-8192-919f19cc3454.png)

3.2) Add sort icon 
![image](https://user-images.githubusercontent.com/47353570/101761033-59e3fc00-3ae4-11eb-9608-97d275b94957.png)

3.3) Sort view https://zpl.io/aMy4OAz
![image](https://user-images.githubusercontent.com/47353570/101761084-67998180-3ae4-11eb-88a2-199e4bab457e.png)

**Comment by Denis-Asipenko** [comment]
The time calculation will be corrected in this task https://github.com/BeamMW/beam/issues/1672 and then checked.
Time sorting doesn't work
![image](https://user-images.githubusercontent.com/45556620/102877386-b7b70300-4457-11eb-9fe2-b4df16f07532.png)

**Comment by Denis-Asipenko** [comment]
will be closed after checking this task https://github.com/BeamMW/beam/issues/1672

**Comment by Denis-Asipenko** [comment]
checked
