### ISSUE TITLE
Wallet offline when device screen locked.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/ios-wallet#43]
Steps to reproduce the behaviour:
1. Go to wallet.
2. Check status wallet. Wallet status is online.  
3. Lock screen device.
4. Unlock screen device.
5. Check status wallet.
Expected: status online.
Actual: status offline.

**Comment by Denis-Asipenko** [comment]
Pop up doesn't come if the wallet is minimized and the device screen locked.

**Comment by kaminskyelina** [comment]
Close due to Push Notifications - Research #119
