### ISSUE TITLE
Send - confirmation screen (redesign)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#432]
Design with changes https://zpl.io/a8rPYyE , https://zpl.io/2jzPBkm

Information is placed more compact now
![image](https://user-images.githubusercontent.com/47353570/98252454-a33fa980-1f82-11eb-977a-96bcdcf53ed7.png)

**Comment by Denis-Asipenko** [comment]
Need add "payments left: x"
![image](https://user-images.githubusercontent.com/45556620/101457486-a691d080-3946-11eb-91eb-fc350d615b3e.png)

**Comment by Denis-Asipenko** [comment]
checked
