### ISSUE TITLE
Changes to the Receive screen

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/ios-wallet#439]
We need to come up with something with this switch. because it is essentially only for one address  "Online address (for wallet)". the other two should always be permanent by default. After the design is ready, please assigned this task to @DenisDemyanko to implement changes in the wallet.
 
Current:
![image](https://user-images.githubusercontent.com/45556620/101739671-ebe60780-3ad8-11eb-8aef-e01a26cf6aa4.png)

An example solution that is implemented on a desktop wallet:
![image](https://user-images.githubusercontent.com/45556620/101739507-a9242f80-3ad8-11eb-8505-7bc43887ed07.png)

**Comment by dariatarakanova** [comment]
1) Remove "Address Expiration" as a title 
![image](https://user-images.githubusercontent.com/47353570/101770217-d11f8d00-3af0-11eb-893a-be49c2c43732.png)

2) Create united block "Online address (for wallet)" that include address expiration switcher and address itself - https://zpl.io/29X5mpY
![image](https://user-images.githubusercontent.com/47353570/101770246-df6da900-3af0-11eb-94b2-e583459d1119.png)

**Comment by Denis-Asipenko** [comment]
checked
