### ISSUE TITLE
Add to Settings "Max privacy lock time limit"

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#440]
1) Please add "Max privacy lock time limit" to Privacy settings https://zpl.io/blkg88X
![image](https://user-images.githubusercontent.com/47353570/101764518-d4af1600-3ae8-11eb-9438-a8009146e2b5.png)

2) "Max privacy lock time limit" page https://zpl.io/VxNBE5g
![image](https://user-images.githubusercontent.com/47353570/101764606-e7294f80-3ae8-11eb-925a-8ca1e0fb5ab4.png)

**Comment by Denis-Asipenko** [comment]
checked
