### ISSUE TITLE
Receive Max privacy. Comment "can take up to XX days"

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#442]
Please add comment to Max privacy tx: "Max Privacy transaction can last at most 72 hours." https://zpl.io/b6LY94N

![image](https://user-images.githubusercontent.com/47353570/101772502-1abda700-3af4-11eb-84b3-dc804735cf9d.png)

**Comment by Denis-Asipenko** [comment]
checked
