### ISSUE TITLE
Display app version as "v 5.2.00" (the same as on desktop)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#445]
Current implementation:
![image](https://user-images.githubusercontent.com/47353570/102077998-d5121e80-3e12-11eb-917b-d480761e4d64.png)

Login screen (updated) https://zpl.io/aXP3K3p
![image](https://user-images.githubusercontent.com/47353570/102077812-8cf2fc00-3e12-11eb-85a1-67fdedb7f489.png)

Settings screen (updated) https://zpl.io/agOj879
![image](https://user-images.githubusercontent.com/47353570/102077867-a4ca8000-3e12-11eb-8e62-ef8912795c10.png)

**Comment by Denis-Asipenko** [comment]
checked
