### ISSUE TITLE
Send confirmation screen - text fixes

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#451]
Change "." to "," between "Regular, permanent" 

Current implementation (testnet)
![image](https://user-images.githubusercontent.com/47353570/103759082-d1da0f00-501b-11eb-8137-f0405bb1070a.png)

Design: https://zpl.io/2jzPBkm
![image](https://user-images.githubusercontent.com/47353570/103759193-0221ad80-501c-11eb-9a22-68b5f7d5f1b9.png)

**Comment by Denis-Asipenko** [comment]
checked
