### ISSUE TITLE
Fix spaces between "AVAILABLE" AND "MAX PRIVACY" tabs

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#452]
1) Current implementation
![image](https://user-images.githubusercontent.com/47353570/103759424-604e9080-501c-11eb-9310-b4ff6c5111f9.png)

Design: https://zpl.io/VqWLnGl and https://zpl.io/25LYNQ3
![image](https://user-images.githubusercontent.com/47353570/103759458-6fcdd980-501c-11eb-83e5-d56ded1ce49a.png)

2) Please make changing tab animation smoother
[RPReplay_Final1609929284.MP4.zip](https://github.com/BeamMW/ios-wallet/files/5775291/RPReplay_Final1609929284.MP4.zip)

**Comment by Denis-Asipenko** [comment]
don't fixed

**Comment by kazaryan-t** [comment]
№ 2 not fixed.
Please make changing tab animation smoother (between **Available** and **Max privacy**)


https://user-images.githubusercontent.com/68247034/120313052-2f7c3a00-c2e2-11eb-9adb-7cdc520f1c64.MP4

**Comment by Denis-Asipenko** [comment]
irrelevant
