### ISSUE TITLE
Make title "Comment" in CAPS on send screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#453]
Current implementation 

![image](https://user-images.githubusercontent.com/47353570/103759682-c89d7200-501c-11eb-8256-eb809333b49a.png)

Design: https://zpl.io/VYey6QJ
![image](https://user-images.githubusercontent.com/47353570/103759817-f387c600-501c-11eb-88c7-266880ba99b7.png)

**Comment by Denis-Asipenko** [comment]
checked
