### ISSUE TITLE
Change color from pink to white for UTXO and Change amount on send confirmation screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#454]
Please make amounts of "Total UTXO value" and "Change" in white color. Pink color only for send amount. On previous screen (send) available in white color, so UTXO and Change also should be in white

![image](https://user-images.githubusercontent.com/47353570/103760006-2d58cc80-501d-11eb-879b-22ab26d6942b.png)

Design: https://zpl.io/2jzPBkm
![image](https://user-images.githubusercontent.com/47353570/103760028-377acb00-501d-11eb-8a2c-7e85cab3e9fd.png)

**Comment by Denis-Asipenko** [comment]
checked
