### ISSUE TITLE
Fix top and bottom paddings on send screen (address field)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#455]
Top and bottom paddings on plaques should be equal.

![image](https://user-images.githubusercontent.com/47353570/103760701-24b4c600-501e-11eb-851d-5cec87b45c73.png)

Current implementation

![image](https://user-images.githubusercontent.com/47353570/103760452-cee01e00-501d-11eb-992a-d243fb66d7c4.png)

Design: https://zpl.io/2Zll8eq

![image](https://user-images.githubusercontent.com/47353570/103760497-dd2e3a00-501d-11eb-9d37-5f9a6ff139ef.png)

**Comment by Denis-Asipenko** [comment]
checked
