### ISSUE TITLE
Fix top and bottom paddings on plaques on receive screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#456]
Top and bottom paddings should be 20 px from closest element (icons, text)

Current implementation

![image](https://user-images.githubusercontent.com/47353570/103760907-778e7d80-501e-11eb-8f11-69df510dcd1f.png)

Design: https://zpl.io/adlMEgl

![image](https://user-images.githubusercontent.com/47353570/103761007-a278d180-501e-11eb-962d-30b5c2972c2a.png)

**Comment by Denis-Asipenko** [comment]
checked
