### ISSUE TITLE
Comment "Offline address" isn't displaying when paste offline address

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#457]
Current implementation. When paste offline address there should be comment "Offline address. Payments left: 9"
![image](https://user-images.githubusercontent.com/47353570/103762403-e79e0300-5020-11eb-8a73-33998441b7fe.png)

Design: https://zpl.io/2Zll8eq
![image](https://user-images.githubusercontent.com/47353570/103762532-1d42ec00-5021-11eb-8459-3deb16ad29f6.png)

**Comment by sasha-abramovich** [comment]
wrong UX, sets the user expectations in a wrong way

**Comment by Denis-Asipenko** [comment]
сhecked
