### ISSUE TITLE
Make similar text for all copy "toasts" - Address copied to clipboard

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#458]
[RPReplay_Final1609928105.MP4.zip](https://github.com/BeamMW/ios-wallet/files/5775516/RPReplay_Final1609928105.MP4.zip)

If copy address by tapping the "copy" icon - text "Address copied to clipboard"
if copy address by using button "copy" on more details screen - text "Copied to clipboard"

Current implementation
![image](https://user-images.githubusercontent.com/47353570/103764562-5df03480-5024-11eb-87e6-04556ab42470.png)

![image](https://user-images.githubusercontent.com/47353570/103764591-68123300-5024-11eb-8b5f-5d32040af749.png)

**Comment by Denis-Asipenko** [comment]
checked
