### ISSUE TITLE
Add more info to log file

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/ios-wallet#46]
We need to add the following info to the logs:
- app version,
- iOS verson,
- device model.

**Comment by jurijakimuk** [comment]
@DenisDemyanko Contact me or other tester when you start working with this to agree on the display format of the data above. Thank you.

**Comment by kaminskyelina** [comment]
This is OK for QA - but should be removed from the builds that sent to Apple @Denis-Asipenko

**Comment by Denis-Asipenko** [comment]
Change text in logs:
- APP RUNNING
- iOS: 12.1.4
- MODEL: iPhone
- MODEL ID: iPhone10,4
- APP VERSION: 1.0.1
- BUILD NUMBER: 3
Change to:
- OS VERSION: iOS 12.1.4
- DEVICE TYPE: iPhone
- DEVICE MODEL ID: iPhone 10,4
- APP VERSION: 1.0.1 Build 3

**Comment by Denis-Asipenko** [comment]
checked
