### ISSUE TITLE
Fix text on "show QR code" for max privacy (receive)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#460]
Current implementation
![image](https://user-images.githubusercontent.com/47353570/106120214-c5e6f600-615e-11eb-9c79-4dc1afb2d473.png)

Correct text https://zpl.io/2EneP1v
![image](https://user-images.githubusercontent.com/47353570/106119923-6983d680-615e-11eb-9025-b70354b35a37.png)

**Comment by Denis-Asipenko** [comment]
Please change the text for Max Privacy tx to "Max Privacy transaction can last at most 72 hours."
![image](https://user-images.githubusercontent.com/45556620/120194656-8ae8f200-c226-11eb-9e36-0bc8dc0bcec0.png)

**Comment by Denis-Asipenko** [comment]
checked
