### ISSUE TITLE
Wallet crashing with firebase

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/ios-wallet#461]
We need to investigate the cause of the crashing of the wallet with firebase
device iPhone 6

**Comment by Rein2005** [comment]
Hello, i have Beam wallet version v.5.2.1 
I have friend have mined in Leafpool Beam coins for me about year ago, now I have try to pull coins out from pool but no success. I know how to do, request payout and wallet have to be synced, have try many times. 
we have also test is everything ok with wallet and mined some extra beam to my address and these coins have arrived to the wallet, so for me is not understandable why other (old mined) coins from leafpool not moving in to my wallet

Thank you in advance 
Rein

**Comment by Denis-Asipenko** [comment]
Hello. Please contact the support channel in telegram https://t.me/BeamSupport or by email support@beam.mw because your comment doesn't apply to this task.
> Hello, i have Beam wallet version v.5.2.1
> I have friend have mined in Leafpool Beam coins for me about year ago, now I have try to pull coins out from pool but no success. I know how to do, request payout and wallet have to be synced, have try many times.
> we have also test is everything ok with wallet and mined some extra beam to my address and these coins have arrived to the wallet, so for me is not understandable why other (old mined) coins from leafpool not moving in to my wallet
> 
> Thank you in advance
> Rein
