### ISSUE TITLE
iOS receive screen with address book

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#463]
Updated design: https://zpl.io/bzQxL08

1) Regular empty screen https://zpl.io/V0vvypR
![image](https://user-images.githubusercontent.com/47353570/113147028-0c2d0400-9239-11eb-9874-f60672b968d3.png)

2) Empty max privacy screen https://zpl.io/V1EEqDQ
![image](https://user-images.githubusercontent.com/47353570/113147237-3f6f9300-9239-11eb-90c8-1891cf9e5856.png)

3) Give a name to new contact https://zpl.io/be99YWD
![image](https://user-images.githubusercontent.com/47353570/113147304-51e9cc80-9239-11eb-8623-ed2bee8d896d.png)

4) Search existing contact https://zpl.io/brqqNPr
![image](https://user-images.githubusercontent.com/47353570/113147485-7e9de400-9239-11eb-9b95-ffec6d3db3fa.png)

5) Receive from contact https://zpl.io/bWMMYX1
![image](https://user-images.githubusercontent.com/47353570/113147532-89587900-9239-11eb-838f-b31d25b3c70b.png)

6) "Create new address" - creates new address for current contact (that chose) https://zpl.io/bWMMYX1
![image](https://user-images.githubusercontent.com/47353570/113147889-ece2a680-9239-11eb-9b85-d891c59a8a1d.png)

After creating new address for current contact  - display toast bar and text "new" on address tile https://zpl.io/2ZRRJXJ 
![image](https://user-images.githubusercontent.com/47353570/113148057-1a2f5480-923a-11eb-8be7-e7cb7e573f2a.png)

7) Address details https://zpl.io/blKKp61
![image](https://user-images.githubusercontent.com/47353570/113148182-3af7aa00-923a-11eb-9108-347ee62bb5b4.png)

8) Contact field is not required field

**Comment by DenisDemyanko** [comment]
Hello everyone. I have a question:
1. Are we removing the tag functionality? Now addresses won't have tags?
