### ISSUE TITLE
Mobile node flow

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#465]
We need to differentiate 3 nodes: random, mobile and specific

1) Node menu https://zpl.io/2vRjNAn
![image](https://user-images.githubusercontent.com/47353570/115063215-f2a3e180-9ef3-11eb-961b-f1cc26853a91.png)

2) Random node 
2.1) Connection to Random node is fast and no need any loading screen. Just click "connect" button. 
2.2) When wallet connect to Random node - status is "circle" with text "online"
![image](https://user-images.githubusercontent.com/47353570/113155577-d6d8e400-9241-11eb-832b-0cd785235095.png)

3) Mobile node
3.1) Connection will take some time and after tap on "connection" button show loading screen https://zpl.io/bPKBvnp
![image](https://user-images.githubusercontent.com/47353570/115063374-2848ca80-9ef4-11eb-993b-ce03ebc0aafc.png)

3.2) After loading screen open Wallet screen with toaster https://zpl.io/annzgrA
![image](https://user-images.githubusercontent.com/47353570/115063525-5c23f000-9ef4-11eb-9485-9c01860846db.png)

3.3) When wallet connect to Mobile node - status is "circle" with text "online: mobile node"
![image](https://user-images.githubusercontent.com/47353570/115063560-67771b80-9ef4-11eb-8ee5-4bf91b743e6e.png)

4) Own node
4.1) Connection to Random node is advanced feature and requests ip:port that appears only after choosing this node (with "v") https://zpl.io/b6n5m1P
![image](https://user-images.githubusercontent.com/47353570/115063676-8b3a6180-9ef4-11eb-8dc6-9f8551c50f85.png)

4.2) When wallet connect to Specific node - status is "lock" with text "online"

**Comment by dariatarakanova** [comment]
@sasha-abramovich there is some questions:

1) What icon should we use for Mobile node? Lock or circle?
![image](https://user-images.githubusercontent.com/47353570/114785235-0977f600-9d85-11eb-948b-6e18b28eeea4.png)

2) Does Mobile node more secure than specific or random?
![image](https://user-images.githubusercontent.com/47353570/114785304-2f9d9600-9d85-11eb-9c26-4fcd0bc33078.png)

**Comment by gingervik** [comment]
4.2 - lock icon should be displayed only if we connected to the node with the same owner key (as it works now)

**Comment by dariatarakanova** [comment]
the same as for android - https://github.com/BeamMW/android-wallet/issues/529 

Own node (or other node) connected https://zpl.io/2GjBErE

1) make another node inactive
2) make IP address non-editable
3) button should be "disconnect"
4) only after tap on button "disconnect" used can change IP and connect to another node. and status should be "cannot connect to ..." https://zpl.io/bAR8O1e

![image](https://user-images.githubusercontent.com/47353570/119566251-9ade7d00-bdb3-11eb-8845-aecc1e7c83c5.png)

**Comment by Denis-Asipenko** [comment]
1. if the address field is empty when connecting to your node, you need to display the corresponding error. For example, "the address field is empty, please enter the address".
2. if the address field was empty when you clicked connect, then after closing the pop-up window, then the disconnect button should not be there.
3. when connecting to own node, in the node does not specify the owner's key in this case, the indicator should be the circle. If the owner's key is specified in the node, then the indicator must be a lock.

https://user-images.githubusercontent.com/45556620/120438414-03b48f00-c38a-11eb-911c-7a497c23884b.mp4

**Comment by Denis-Asipenko** [comment]
Bugs:
1. prevent editing the node address field when connecting
![image](https://user-images.githubusercontent.com/45556620/120500926-df78a280-c3c9-11eb-9bf8-de142c644445.png)
2. after connecting to own node, for some reason it is indicated in the settings that the wallet is connected to the mobile node
![image](https://user-images.githubusercontent.com/45556620/120501220-1cdd3000-c3ca-11eb-9d5e-b40c8cfc7b18.png)
https://user-images.githubusercontent.com/45556620/120501384-40a07600-c3ca-11eb-9c51-3193b2696da3.mp4

**Comment by Denis-Asipenko** [comment]
checked
