### ISSUE TITLE
Connection to nodes before install wallet

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#466]
Please add Node connectivity screen to install process after Seed phrase and Password, but before Creating wallet https://zpl.io/2p3drME

If user select Mobile node and wallet creation will take some time please show comment as here https://zpl.io/2p3drME  
![image](https://user-images.githubusercontent.com/47353570/115298567-4ae21a00-a166-11eb-998d-a26a71441b91.png)

Node screens are here: https://zpl.io/be348qW and https://zpl.io/a3Evknd (Please pay attention on button name, it's different then on settings screen)

Flow:
![image](https://user-images.githubusercontent.com/47353570/115299312-4f5b0280-a167-11eb-8011-b03537daac7e.png)

This task continues #465

**Comment by Denis-Asipenko** [comment]
1. when creating a wallet with a mobile node, there is no text on the sync screen
![image](https://user-images.githubusercontent.com/45556620/120437414-b5eb5700-c388-11eb-9946-9cf137a98ca7.png)
2. when creating a wallet with a random node, the wallet should open quickly without a sync screen. at the moment, the sync screen is there
3. there must be an address template
![image](https://user-images.githubusercontent.com/45556620/120437782-2c885480-c389-11eb-8b2c-b5aa33f50f52.png)

**Comment by Denis-Asipenko** [comment]
the elements are shifted when the keyboard appears.

https://user-images.githubusercontent.com/45556620/120499623-e357f500-c3c8-11eb-8960-9414fe5e24c7.mp4

**Comment by Denis-Asipenko** [comment]
checked
