### ISSUE TITLE
Receive screen - 6.0

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#468]
Designs https://zpl.io/aBz1pdL

1) Make all title in white color https://zpl.io/aNxwn5D
![image](https://user-images.githubusercontent.com/47353570/114766297-e3475b80-9d6e-11eb-8c97-a3d1bf667698.png)

2) Rename "Address type" to "Transaction type"
![image](https://user-images.githubusercontent.com/47353570/114766358-fa864900-9d6e-11eb-83cc-d5db80833f96.png)

3) Change "more details" to "address details" 
![image](https://user-images.githubusercontent.com/47353570/114766407-0a9e2880-9d6f-11eb-8d7a-53bd2157c4e8.png)

4) Regular TX https://zpl.io/aNxwn5D
![image](https://user-images.githubusercontent.com/47353570/114766506-25709d00-9d6f-11eb-9604-63fc19e55790.png)

5) Max privacy TX https://zpl.io/VKdGLQ6
![image](https://user-images.githubusercontent.com/47353570/114766561-38836d00-9d6f-11eb-92c0-931064081f43.png)

6) Address details. Add "copy" icon and rename button to "copy and close"
![image](https://user-images.githubusercontent.com/47353570/114766623-4d600080-9d6f-11eb-80de-8c87178292c6.png)

7) QR for regular tx https://zpl.io/an3oQ7Q
QR for max privacy https://zpl.io/am3Dw7v
![image](https://user-images.githubusercontent.com/47353570/114766717-6a94cf00-9d6f-11eb-869d-53d1aea37bbe.png)

8) Make buttons the same wight
![image](https://user-images.githubusercontent.com/47353570/114766834-92843280-9d6f-11eb-8519-511dc0a823d2.png)

**Comment by kazaryan-t** [comment]
1. Change the text for max privacy transactions to **"Max privacy transaction can last at most 72 hours."**
2. Place the text "Max privacy transaction..." and "Min transaction fee.." as in the design.

![IMG_0171](https://user-images.githubusercontent.com/68247034/120441788-9b67ac80-c38d-11eb-9403-506f368e5d2d.PNG)
![6 0_receive-max-privacy - 02 iOS Wallet - Zeplin -](https://user-images.githubusercontent.com/68247034/120441811-a02c6080-c38d-11eb-8270-f735e191434a.png)

![IMG_0172](https://user-images.githubusercontent.com/68247034/120442314-2183f300-c38e-11eb-8a83-1bb1672e969e.PNG)
![6 0_receive-show-qr-max-privacy - 02 iOS Wallet - ](https://user-images.githubusercontent.com/68247034/120442342-29439780-c38e-11eb-9cd3-9631a5957ea8.png)

3. For regular transactions add the text **"Sender will be given a choice between regular and offline payment."**
4. Place text for regular transactions as in the design:

![IMG_0173](https://user-images.githubusercontent.com/68247034/120443427-4c227b80-c38f-11eb-9ee4-7e1b0c441987.PNG)
![6 0_receive-show-qr - 02 iOS Wallet - Zeplin - Goo](https://user-images.githubusercontent.com/68247034/120445849-b3d9c600-c391-11eb-8556-e68cae1192d0.png)

![IMG_0174 (2)](https://user-images.githubusercontent.com/68247034/120446081-ea174580-c391-11eb-91c3-913872a47c9e.PNG)
![6 0_receive-regular - 02 iOS Wallet - Zeplin - Goo](https://user-images.githubusercontent.com/68247034/120445845-b2100280-c391-11eb-9d45-a4a1025e4529.png)


5. Swap the buttons **show QR code** and **copy address** as in the design

![IMG_0171 (2)](https://user-images.githubusercontent.com/68247034/120443717-99065200-c38f-11eb-893b-aba14c6dd84b.PNG)
![6 0_receive-regular - 02 iOS Wallet - Zeplin - Goo](https://user-images.githubusercontent.com/68247034/120443880-c3580f80-c38f-11eb-8401-7923e8a83510.png)

**Comment by kazaryan-t** [comment]
Checked.
