### ISSUE TITLE
Main screen with CA

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#469]
Designs: https://zpl.io/VDgjAEq

1) Add "Asset" title and arrow ">" (the same as with transactions >). Display 4 recently used assets https://zpl.io/ag3xQY9
2) Locked amount displays under the total amount
3) Display USD/BTC amount on the right side of asset's tile
![image](https://user-images.githubusercontent.com/47353570/117874127-49a99600-b2a9-11eb-97ef-b70e2147d7fe.png)

4) All assets list. Assets can be sorted https://zpl.io/Vk14p0v 
![image](https://user-images.githubusercontent.com/47353570/118929826-aeba5700-b94d-11eb-86e7-0484961e4fd8.png)

5) Asset screen: display asset amount and asset's transactions https://zpl.io/br3qvQW
![image](https://user-images.githubusercontent.com/47353570/117875196-8c1fa280-b2aa-11eb-87b2-925386fe4a9c.png)

6) "Info" icon opens detailed balance https://zpl.io/bARg7oO asset's info https://zpl.io/VQNPvjW
![image](https://user-images.githubusercontent.com/47353570/117875351-ba04e700-b2aa-11eb-98ad-b8395d1e9087.png)

**Comment by Denis-Asipenko** [comment]
need fix:
1. 
![image](https://user-images.githubusercontent.com/45556620/123933621-38246680-d99b-11eb-8b12-4e1fd8e1f229.png)

2. The BEAM coin should not be displayed on the asset screen
![image](https://user-images.githubusercontent.com/45556620/123934185-b41eae80-d99b-11eb-86e6-8e45b000b4ab.png)

3.
![image](https://user-images.githubusercontent.com/45556620/123934318-d7495e00-d99b-11eb-832d-727fdd57b8eb.png)

4.
![image](https://user-images.githubusercontent.com/45556620/123934397-e9c39780-d99b-11eb-8c85-19d1d871b360.png)

5.
![image](https://user-images.githubusercontent.com/45556620/123934440-f3e59600-d99b-11eb-8ed0-d402d923397d.png)

**Comment by AndreyDyakonov** [comment]
Checked
