### ISSUE TITLE
Remove "Off" from second currency in settings

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#470]
Leave only 2 options: USD (Default) and BTC.

https://zpl.io/VYg5RpE
![image](https://user-images.githubusercontent.com/47353570/115450841-15e8cc80-a225-11eb-9784-2f84d5713f1d.png)

Current implementation
![image](https://user-images.githubusercontent.com/47353570/115450985-43357a80-a225-11eb-8f8d-2ceddb14bbcf.png)

**Comment by Denis-Asipenko** [comment]
checked
