### ISSUE TITLE
Update Transactions list layout

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#472]
Changes:
1) Add asset coin icon

2) Make amount in white color and place near assets icon

3) Remove Text "Send" and "'Receive. Leave only colored status+icon

4) Make USD/BTC amount 80% white color.

![image](https://user-images.githubusercontent.com/47353570/117876643-495eca00-b2ac-11eb-8329-cdb02df2fdc5.png)

5) DAPPS/Contracts transactions. 

If there are only 2 assets - display BEAM (as default coin) and "+1" (as second example on screenshot)
If there 3+ assets - display BEAM (as default coin) and "+2" (as first example on screenshot). If there is no BEAM - display biggest amount first.
![image](https://user-images.githubusercontent.com/47353570/117876278-dbb29e00-b2ab-11eb-866b-dc113b30555f.png)

6) Transaction details https://zpl.io/2GjDGKm
![image](https://user-images.githubusercontent.com/47353570/117876892-8dea6580-b2ac-11eb-8219-80af57b19471.png)

7) Updated statuses for MULTIPLY ASSETS https://zpl.io/b6xJ58q

Current design:
![image](https://user-images.githubusercontent.com/47353570/117875868-58914800-b2ab-11eb-9c7d-10aa451673a3.png)

Updated design: 
![image](https://user-images.githubusercontent.com/47353570/117875799-44e5e180-b2ab-11eb-9d4d-b59cff1114a5.png)

**Comment by kazaryan-t** [comment]
Checked.
