### ISSUE TITLE
Dapps notifications

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#473]
Notifications: https://zpl.io/ag3xkL0

![image](https://user-images.githubusercontent.com/47353570/117880200-8200a280-b2b0-11eb-82d0-c2ae3dbe5760.png)

Tap on DAPPs notification - open Dapp's transactions screen with unfolded transactions details 
![image](https://user-images.githubusercontent.com/47353570/117880381-b83e2200-b2b0-11eb-8296-1250983c5de8.png)

**Comment by AndreyDyakonov** [comment]
- Dapps notification transaction icon same as usual transactions
- missing description of Dapps transaction

![photo_2021-10-05_11-53-14](https://user-images.githubusercontent.com/85252690/135992245-00870316-7773-4f3b-b428-ac904fc8c93f.jpg)

**Comment by AndreyDyakonov** [comment]
Checked
