### ISSUE TITLE
Assets colors palette

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#483]
The color palette here: https://zpl.io/V4gl8Zy

For the first 20 assets, you can use these colors.
![image](https://user-images.githubusercontent.com/47353570/122907923-48659180-d35c-11eb-8f85-03746ce6c20a.png)

**Comment by AndreyDyakonov** [comment]
Please change 3 colors, look like UI :

![2021-08-10_14-10-56](https://user-images.githubusercontent.com/85252690/128857574-648f03b8-d6b1-42a1-b788-46027e584c75.png)

In design : 

![2021-08-10_14-11-59](https://user-images.githubusercontent.com/85252690/128857649-f89c99b6-c65f-404a-8c97-7821f4fb5f8f.png)
![2021-08-10_14-13-26](https://user-images.githubusercontent.com/85252690/128857656-9193fbf6-3b61-44b4-8faa-5900c2b5cb0d.png)
![2021-08-10_14-14-40](https://user-images.githubusercontent.com/85252690/128857664-4014f951-31eb-433d-970b-a6a9abd1a5ed.png)

**Comment by AndreyDyakonov** [comment]
Checked
