### ISSUE TITLE
Update design of input fields

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#484]
Please update the design of all input fields in the app. Please work only with fields design, no need to change any titles, comments etc.

1) All the states for input fields are here https://zpl.io/Vk9v1e8
![image](https://user-images.githubusercontent.com/47353570/134175719-629c84f2-5272-4f85-a5b4-111e1df7fa4c.png)

2) Login/authorization https://zpl.io/VqYYZ3Z

![image](https://user-images.githubusercontent.com/47353570/134175842-33280906-f70b-4853-a1ff-2e9823105303.png)

Incorrect - https://zpl.io/bLPWBl7 
![image](https://user-images.githubusercontent.com/47353570/134176013-ed929a55-5652-426c-88b9-ec91f9a6876e.png)

3) Seed phrase confirmation https://zpl.io/V4oYzD8
![image](https://user-images.githubusercontent.com/47353570/134177313-b934e62c-d6f8-48d5-b52a-18a82895ebc2.png)

4) Restore wallet. Seed phrase https://zpl.io/VDKjQn3
![image](https://user-images.githubusercontent.com/47353570/134177398-18fc29a6-2aeb-4a21-898a-c289924f38ac.png)

4.1)  Restore wallet. ID:port error. https://zpl.io/aRzLPgg
![image](https://user-images.githubusercontent.com/47353570/134177484-929e9fdf-f040-4f1e-b256-ac485baba5d8.png)

4.2) Restore wallet. ID:port empty https://zpl.io/bJGod5x
![image](https://user-images.githubusercontent.com/47353570/134177768-0cef6572-2a4c-4b66-af00-570929b69f74.png)

5) Send screens empty https://zpl.io/bAwpR8n
![image](https://user-images.githubusercontent.com/47353570/134178007-91610afb-5c60-49a2-8d22-33862fd6e355.png)

5.1) Send screens filled https://zpl.io/aRK84ye
![image](https://user-images.githubusercontent.com/47353570/134178061-71f46351-5f4f-42cc-a8cf-e57e9605d48a.png)

6) Receive screen empty https://zpl.io/a77Bngj
![image](https://user-images.githubusercontent.com/47353570/134178164-de645345-8b67-423e-9db1-5df77dd187c5.png)

6.1) Focus https://zpl.io/aMxNzwo
![image](https://user-images.githubusercontent.com/47353570/134178298-0760557d-b7a9-43b8-b983-ae9032491f2a.png)

6.2) Filled https://zpl.io/Vq4X0z7
![image](https://user-images.githubusercontent.com/47353570/134178337-c078796a-699f-44f9-aed1-dd32e0f014f5.png)

7) Address. Edit https://zpl.io/bAWOkgO
![image](https://user-images.githubusercontent.com/47353570/134178617-156c2135-27ce-4019-88c9-dd953c219a91.png)

7.1) Address. Add contact https://zpl.io/b6gZD6W
![image](https://user-images.githubusercontent.com/47353570/134178709-9f0c9827-af8d-446e-aea1-c9dec4a35b92.png)

8) Settings. Payment proof. https://zpl.io/b6xM6jW
![image](https://user-images.githubusercontent.com/47353570/134178918-cf20b320-b0fa-4465-a182-4f08fd7e977b.png)

8.1) Node https://zpl.io/bAR8O1e
![image](https://user-images.githubusercontent.com/47353570/134179071-6bea51b0-fe9f-4745-a63e-023edf238faa.png)

8.2) Seed verification https://zpl.io/a8vXM6E
![image](https://user-images.githubusercontent.com/47353570/134179196-f5598a48-ee12-4554-b7e0-1c00dcfe8a92.png)

8.3) Chnage pass. https://zpl.io/ad1vBwL
![image](https://user-images.githubusercontent.com/47353570/134399736-606fe9f8-a548-46aa-af24-a7f2c9628515.png)

9) Popup dialog with input field https://zpl.io/bADnlvo
![image](https://user-images.githubusercontent.com/47353570/134179755-ba148b2d-da8c-47ea-a1af-e9d1b4b5bfe6.png)

**Comment by AndreyDyakonov** [comment]
Checked
