### ISSUE TITLE
Remove UTXO screen from sidemenu and add it to settings

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#485]
1) Please remove UTXO from Menu

2) Add UTXO to Utilities in Settings https://zpl.io/2p75y1M

3) Add Blockchain height to Utilities and remove Remove "Last block hash" https://zpl.io/2p75y1M

![image](https://user-images.githubusercontent.com/47353570/124452387-03dfea00-dd8f-11eb-8b82-d0803b4c3afc.png)

4) Add asset icon to ITXO list. Available tab https://zpl.io/aRRwe0g

5) In progress tab https://zpl.io/boJAvNG

6) Spent tab https://zpl.io/a3rQLON
 
7) Unavailable tab https://zpl.io/V4RGLxp

![image](https://user-images.githubusercontent.com/47353570/124452657-40134a80-dd8f-11eb-8b17-3b37e61c3480.png)

8) UTXO details. Please remove transaction history from this screen  https://zpl.io/V13AXnJ
![image](https://user-images.githubusercontent.com/47353570/123703645-51c79000-d86d-11eb-9b18-bdaf8cfbe5ee.png)

9) UTXO empty https://zpl.io/a3rQLoN
![image](https://user-images.githubusercontent.com/47353570/123696936-fdb8ad80-d864-11eb-9a3f-82c1c7aaa591.png)

10) Security mode is On https://zpl.io/V13AXBQ
![image](https://user-images.githubusercontent.com/47353570/123697092-2ccf1f00-d865-11eb-9ce3-9e29960a13e5.png)

**Comment by AndreyDyakonov** [comment]
Checked
