### ISSUE TITLE
The wallet isn't sync after switching to the mobile node

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/ios-wallet#486]
**Bug description**
When a user has created a new wallet with a connection to a random node, the wallet is not synchronized after switching to a mobile node
**To Reproduce**
1. Created a new wallet with a connection to a random node.
2.  Go to the Settings screen and switch to the mobile node.
 **Current behavior:**
the wallet gets stuck on the sync screen with 0% . there is an error in the logs:
`12:04:41.772 broadcast rate message processing exception: /Users/denis/Documents/Projects/Xcode/beam/include/3rdparty/yas/detail/io/binary_streams.hpp(316): can't read requested bytes`

**Expected behavior:**
 synchronized with the blockchain and the wallet is opened

**Comment by AndreyDyakonov** [comment]
Checked
