### ISSUE TITLE
Transaction details (updated version after desktop changes)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#488]
**1. Wallet transactions with payment proof. Show info into 2 separate tabs.**

1.1. General info https://zpl.io/brKmrXD
- add coin icons to Amount and Fee
- add copy icon to sending address, receiving address, and transaction ID.
- text next to USD amount  "(calculated with the exchange rate at the time of transaction)" - if the rate was successfully calculated 
- text instead of USD amount  "(exchange rate was not available at the time of transaction)" - if rate was not available. And do not show USD rate https://zpl.io/2jdk8xQ
- remove text-link "Open in blockchain Explorer" and leave only the green icon. Place it in one line with Kernel ID.
![image](https://user-images.githubusercontent.com/7249484/131826240-c62f8ff1-3b74-46d0-abe3-ec3ae6bae000.png)
![image](https://user-images.githubusercontent.com/7249484/131826247-34bc743b-6a65-4d12-8635-d916f4c2bacf.png)

1.2 Details for maximum anonymity transaction https://zpl.io/aNvBp8Q
![image](https://user-images.githubusercontent.com/7249484/131826740-34a326e0-bf55-4fd2-adf3-33adfca944ab.png)

1.3. Payment proof. Works only for sending transactions https://zpl.io/a77KyNj
- add copy icon to sender's and receivers wallet signature and Code.
- text next USD amount  "(calculated with the exchange rate at the time of transaction)" - if the rate was successfully calculated 
- text instead of USD amount  "(exchange rate was not available at the time of transaction)" - if rate was not available. And do not show USD rate
- remove text-link "Open in blockchain Explorer" and leave only the green icon. Place it in one line with Kernel ID.
![image](https://user-images.githubusercontent.com/7249484/131795769-9a4a7d02-6e63-4afa-9255-b0993aa87162.png)

**2. Contract transactions (without payment proof)** https://zpl.io/awwnrDn 
- add Confidential asset ID next to CA amounts and "link" icons that lead to the asset in blockchain explorer (example https://explorer.beam.mw/assets/details/2)
- add Dapp name, Application shader, Description (not Comment)
- place a comment about the exchange rate under amounts (title).
- If more than 1 coin - AMOUNTS should be in plural
- - text under amounts  "(calculated with the exchange rate at the time of transaction)" - if the rate was successfully calculated 
- text under amounts "(exchange rate was not available at the time of transaction)" - if rate was not available. And do not show USD rate https://zpl.io/2G5pml9
![image](https://user-images.githubusercontent.com/7249484/131826765-92d004cf-f5c9-4cc1-8ea5-be0fe19fa0dd.png)
![image](https://user-images.githubusercontent.com/7249484/131826773-011ebac6-e2c2-4123-b81e-f751264a059a.png)

**Comment by AndreyDyakonov** [comment]
Contract transactions:
- remove the tab "payment proof" in contract transactions  
- move "DAPP NAME" and "APPLICATION SHADER ID" below "FEE"
- text "(calculated with the exchange rate at the time of transaction)" and "(exchange rate was not available at the time of transaction)" below "AMOUNT(S)" title
- change "COMMENT" to "DESCRIPTION"

![2021-10-05_10-57-41](https://user-images.githubusercontent.com/85252690/135986202-6b14e8a8-21c9-409f-b5fb-539a1b1baffb.png)

**Comment by AndreyDyakonov** [comment]
Checked

**Comment by AndreyDyakonov** [comment]
Checked
