### ISSUE TITLE
Send screen: changes in address flow (with max. anon set)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#490]
Please work only on points mentioned below.

1) If receiver sends to sender regular address (maximum anonymity set OFF)

- Sender can choose the transaction type: Online or Offline  https://zpl.io/VDmAg7J
![image](https://user-images.githubusercontent.com/47353570/126788605-d45199cb-d419-470c-bd68-d2581844d079.png)

- Online (name was changed from "regular") transaction - add comment below address "Online address." And comment above "next" button - "The recipient must get online within the next 12 hours and you should get online within 2 hours afterwards."  https://zpl.io/VDmAg7J
![image](https://user-images.githubusercontent.com/47353570/126788796-985d86d9-d624-40a6-81a5-6f7c3612f839.png)

- Offline tx - comment "Offline address: Х transactions left." And comment above "next" button -  "Make sure the address is correct as offline transactions cannot be canceled." https://zpl.io/2pgv3xJ
![image](https://user-images.githubusercontent.com/47353570/126788925-fa1b85aa-14a5-4a3f-bf20-4c3b16a7e90c.png)

- Show warning comment "Ask receiver to come online to support more offline transactions." when 3 or fewer transactions left. https://zpl.io/adyz39e
![image](https://user-images.githubusercontent.com/47353570/126789094-7b758e1e-773a-43ab-9417-ed1679e1f796.png)

2) If receiver sends to sender Online address https://zpl.io/29dwmlW (receiver can copy SBBS address from address details on receive screen)

- No need block "Transaction Type"
- Add comment "Online address. The recipient must get online within the next 12 hours and you should get online within 2 hours afterwards."
![image](https://user-images.githubusercontent.com/47353570/126789164-0c8df9f2-ebe7-4252-8c96-c00f582e8838.png)

3) If receiver sends to sender Maximum anonymity set address https://zpl.io/25jJ4e8

- Add a comment about transaction's amount "Guarantees maximum anonymity set of up to 64K." And comment above "next" button - "Transaction can take up to 72 hours." 
![image](https://user-images.githubusercontent.com/47353570/126789204-49e3cdca-d0ea-4a56-9bf9-2e6c64510fe1.png)

**Comment by AndreyDyakonov** [comment]
Need fix 
1. 
Actually: 
Comment above "next" button - "Max Privacy transaction can take up to 72 hours" and "Min transaction fee to send maximum anonymity coins is 0.01 BEAM" in Masternet
 
 ![photo_2021-07-30_10-16-48](https://user-images.githubusercontent.com/85252690/127649342-080e41d4-c5ce-4820-b018-4bc92fbef5c7.jpg)

Expected: 
Comment above "next" button - "Transaction can take up to 72 hours" in design 
  
![4](https://user-images.githubusercontent.com/85252690/127650638-8d38462f-5d54-41c9-ac8c-b87d3f729df2.png)

2.
Actually:
Comment under the address bar in 2 line in Masternet

![photo_2021-07-30_10-16-48 — копия](https://user-images.githubusercontent.com/85252690/127651169-5b7d0392-83cf-40e1-9b9d-46eb5671c2b9.jpg)

Expected:
Comment under the address bar in 1 line in design
 
![4 — копия](https://user-images.githubusercontent.com/85252690/127651266-7b66d234-1089-426c-9181-9d62b69e8010.png)

**Comment by AndreyDyakonov** [comment]
Checked
