### ISSUE TITLE
Receive screen: changes in address flow (with max. anon set)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#491]
Please work only on points mentioned below. 

1) Add block "Advanced" (minimized by default) and place there Maximum anonymity switcher. https://zpl.io/V0vvypR
![image](https://user-images.githubusercontent.com/47353570/126783088-7364b3cc-ed00-44d5-af74-93a9e679e34f.png)

2) Switcher default position is OFF.
Off = tx will be Regular (it is combined address - online + offline addresses)
On = tx will be Maximum anonymity set

3) When Switcher is OFF. The comment was also updated. https://zpl.io/V0vvypR
![image](https://user-images.githubusercontent.com/47353570/126783063-2c43ddbd-e727-4d6d-a146-82798f4d22a6.png)

4) When Switcher is ON - place the comment "Transaction can last at most 72 hours. Min transaction fee to send maximum anonymity coins is 0.01 BEAM." 
Add "(Maximum anonymity)" next to the ADDRESS https://zpl.io/bAK7e8p
![image](https://user-images.githubusercontent.com/47353570/126783168-3d744fc0-f0f3-4bde-9fdf-fee0bf2c0a82.png)

5) When Switcher is ON - place the comment "Transaction can last indefinitely. Min transaction fee to send maximum anonymity coins is 0.01 BEAM." Comment was updated a bit. https://zpl.io/ag1QlK0
"Can last indefinitely" -  depends on Lock time setting in Utilities (https://zpl.io/VxNBE5g)  
![image](https://user-images.githubusercontent.com/47353570/126783418-95eb3b00-a160-4082-a5bb-3f58dd77fc68.png)

6) Regular address details. Show full only address itself. Online (SBBS) address - always show begin and end of the address. https://zpl.io/25jJXdW
 ![image](https://user-images.githubusercontent.com/47353570/126784513-2b429062-d637-471a-b7d1-6463b154bcae.png)

7) Address details with max anonymity set https://zpl.io/2pgvpLE
![image](https://user-images.githubusercontent.com/47353570/126784580-7d6ee8c1-2cc5-4d03-874d-187a25498307.png)

8) QR regular. Comment was updated. https://zpl.io/2jy5Am6
![image](https://user-images.githubusercontent.com/47353570/126784605-d5f9f3d7-2ae5-42f6-8497-b79b096db010.png)

9) QR max anonymity. https://zpl.io/2GqGXBJ
![image](https://user-images.githubusercontent.com/47353570/126784629-6861115d-bad6-4c4c-84f9-676e33857a7b.png)

**Comment by AndreyDyakonov** [comment]
If we click address details with max anonymity set then we see comment under address

![photo_2021-07-28_11-02-49](https://user-images.githubusercontent.com/85252690/127287962-5370ee59-2866-4001-9746-170b98e66aa5.jpg)

**Comment by AndreyDyakonov** [comment]
Checked
