### ISSUE TITLE
Send screen- reset the amount to 0 if the user enter amount one coin and then selects another coin

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/ios-wallet#492]
Bug description
if the user entered the amount, and then changed the asset, the amount is reset to 0.

To Reproduce

1. Go to the Send screen. The BEAM coin is selected by default
2. Tap enter amount.
3. Select another coin.
Current behavior:
the amount doesn't reset.

Expected behavior:

the amount resets to 0.

Note:
the wallet has some assets.

**Comment by AndreyDyakonov** [comment]
Checked
