### ISSUE TITLE
Change "max privacy" to "max anon. set" in status and comments when random node connected

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#494]
1) When not own node is connected please display status "online: conected node supports online transactions only" and button "change" that leads to node settings  https://zpl.io/bzxZJPA
![image](https://user-images.githubusercontent.com/47353570/128146542-ed126472-a225-468f-8c42-95bc73fd3b1f.png)

2) In Settings update comment to "To support maximum anonymity set and offline transactions please connect to own node configured with your owner key." when user connects to remote node. https://zpl.io/bAK1zNB
![image](https://user-images.githubusercontent.com/47353570/128146569-785f4e45-aa45-4dff-ac86-ddafa5ced08e.png)

3) On Receive screen please disable Max anonymity set switcher. Remove comment "sender will be given a choice.." https://zpl.io/ag1JZRQ
![image](https://user-images.githubusercontent.com/47353570/128146609-1a0caf07-3620-4450-8826-d7b1e21cedaa.png)

4) In address details show onIy online address + comment "You are currently connected to the node that supports only online transactions." Make title just "Online Address". https://zpl.io/VQy5r6R
![image](https://user-images.githubusercontent.com/47353570/128146637-8a2ff014-4de7-4081-a509-440eff9cd103.png)

**Comment by dariatarakanova** [comment]
UPD:

1) Remove button "change" when on Node settings screen https://zpl.io/2GqKn9W

2) Update text to "To support maximum anonymity set and offline transactions please connect to mobile node or own node configured with your owner key.".
Mobile node also can be used for max anon transactions.

![image](https://user-images.githubusercontent.com/47353570/128193686-060c5478-5563-49d3-93d6-fe4497999bb2.png)

**Comment by AndreyDyakonov** [comment]
Checked
