### ISSUE TITLE
Transaction Details - repeat, save address

### ISSUE THREAD

**Issue by DenisDemyanko** [BeamMW/ios-wallet#50]

**Comment by Denis-Asipenko** [comment]
The additional menu doesn't correspond to design.
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5c9a0687c54bff583f0539c9
![image](https://user-images.githubusercontent.com/45556620/55157009-6ab3d900-516c-11e9-8158-970f1749476c.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/55146469-b313cc80-5155-11e9-8550-733fd5dd9840.png)

**Comment by kaminskyelina** [comment]
No need in Repeat
