### ISSUE TITLE
Do not show assets in the drop-down list if they aren't in the wallet

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/ios-wallet#503]
![image](https://user-images.githubusercontent.com/45556620/129754857-2ff10cf1-5f63-4386-8a0b-e88d403050c4.png)
![image](https://user-images.githubusercontent.com/45556620/129754880-cd2787e6-6414-4b0a-9b10-7057267e689a.png)

**Comment by Denis-Asipenko** [comment]
checked

**Comment by Denis-Asipenko** [comment]
if there are no assets in the wallet, you do not need to display a drop-down list. display only the beam without a drop-down list
![image](https://user-images.githubusercontent.com/45556620/130413688-91269929-dad3-49f3-a9df-d0e7616c61ae.png)

**Comment by AndreyDyakonov** [comment]
We don't have any assets, but drop-list with a choice of assets - remained

https://user-images.githubusercontent.com/85252690/130574899-3cd3450c-d5d0-45a0-93a9-525f09e9d875.mp4

**Comment by AndreyDyakonov** [comment]
If we have assets more than 1 - drop-list displayed correctly
If we have only BEAM and 1 asset - drop-list disappears and we can send only BEAM 

https://user-images.githubusercontent.com/85252690/130820637-ceacc608-1330-4355-87eb-c1dd05d7f898.mp4

**Comment by AndreyDyakonov** [comment]
Checked
