### ISSUE TITLE
Incorrect balance display

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/ios-wallet#504]
![image](https://user-images.githubusercontent.com/45556620/129755312-7fb23162-d1bd-40ef-a10f-8f206ae96f14.png)

**Comment by AndreyDyakonov** [comment]
1) In balance window doesn't display locked amount
2) When we send small amount assets - balance window doesn't display locked amount and the window disappears before the transaction is completed


https://user-images.githubusercontent.com/85252690/130598868-cda99af2-432a-4724-899f-465ed9287393.mp4

<img width="250" src="https://user-images.githubusercontent.com/85252690/130598892-1319dee6-9f36-431f-80fb-c5d8dcddaeab.jpg">

<img width="250" src="https://user-images.githubusercontent.com/85252690/130598903-4f71e877-7168-4ada-b3d1-959e78910e0f.jpg">

**Comment by AndreyDyakonov** [comment]
If we have active transaction  - in balance window doesn't display locked amount  

<img width="250" src="https://user-images.githubusercontent.com/85252690/130821417-a68a165b-4674-404b-9362-9ca87421f06b.jpg">

**Comment by AndreyDyakonov** [comment]
Checked
