### ISSUE TITLE
Sync time implementation for Mobile node

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#505]
1) Please implement calculating the synchronization time with the blockchain for Mobile node.

2) Remove the additional header line "Loading wallet", leave only secondary text. (see the lowest screenshot with current implementation)

3) Secondary ext: "Syncing with the blockchain: calculating estimated time"
"Syncing with the blockchain: X mins to completion"
"Syncing with the blockchain: less than a minute to completion"
Important: percents should be displayed only in whole numbers (5%, no 5.5%)

New design 
https://zpl.io/a3QpZrA
https://zpl.io/V1AjW3E

![image](https://user-images.githubusercontent.com/7249484/131185137-85c70b75-2a6a-4d95-ac95-58af2b44c8a7.png)
![image](https://user-images.githubusercontent.com/7249484/131185151-057c0625-f605-441f-ba99-e3ae037dc1cf.png)

Current implementation
![image](https://user-images.githubusercontent.com/47353570/134405548-c2da8513-aa29-484d-9342-7dd292bdb989.png)

4) Please use such text suggestions for all node types connection

**Comment by AndreyDyakonov** [comment]
When we create a new wallet and start syncing with a mobile  or  own node, the syncing description is not displayed

<img width="350" src="https://user-images.githubusercontent.com/85252690/155271358-3f2ea0a4-3c6e-4518-a559-cf81263060bc.jpg">

**Comment by AndreyDyakonov** [comment]
Not fixed with **own** node
When we create a new wallet and start syncing with **own node**, the syncing description is not displayed

<img width="350" src="https://user-images.githubusercontent.com/85252690/158167774-c8311e8d-85ba-4877-8e71-21f8ad4c8daa.jpg">

**Comment by AndreyDyakonov** [comment]
Checked

**Comment by AndreyDyakonov** [comment]
Please change the description as in the design

<img width="450" src="https://user-images.githubusercontent.com/85252690/159928672-20776dea-e74d-4291-9173-a3bac87300f7.jpg">

**Comment by AndreyDyakonov** [comment]
Checked
