### ISSUE TITLE
Rework Create Password screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#506]
The layout is updated to eliminate user's confusion. The nicer input fields are aligned with those on Send/Receive screens.

1. Empty password fields https://zpl.io/aMxLBgm
- replace line input field with box input field
- place the password requirement below the password and it's confirmation.
- button inactive
- make 10% opacity (instead of 5%) on selected field (as on "Password" field)
- eye icon should be shown only on focused fields
![image](https://user-images.githubusercontent.com/7249484/131705074-c1a13236-4312-44f3-b113-2daaeab9a079.png)

2. Password filled, confirmation - error https://zpl.io/adQR4vn
- make box in red color (oppacity 15%)
- button inactive because of error
- add error text
![image](https://user-images.githubusercontent.com/7249484/131827541-1610fd13-3072-4c60-a7d7-6854da652dd8.png)

3. Password filled and confirmation correct https://zpl.io/aNvEZg9
- button active
![image](https://user-images.githubusercontent.com/7249484/131705153-46742c84-9598-4510-991b-be95825d01d2.png)

Text for all password states here https://zpl.io/2G5n7KY
![image](https://user-images.githubusercontent.com/7249484/131827565-2aacd66b-0b47-4dbb-a045-9877ddf44f50.png)

**Comment by AndreyDyakonov** [comment]
Checked
