### ISSUE TITLE
Receive screen: Change comment for Max Anon transactions to "Min transaction fee is X.XX BEAM"

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#508]
Comment in the current implementation is "Min transaction fee to send maximum anonymity coins is 0.01 BEAM."
New comment "Min transaction fee is 0.01 BEAM."

Change on screens:
https://zpl.io/bAK7e8p
https://zpl.io/ag1QlK0
https://zpl.io/ble77gk
https://zpl.io/2jy1ox6

![image](https://user-images.githubusercontent.com/47353570/131342185-bbc784a1-d104-4883-9a8b-d8060b54c047.png)

![image](https://user-images.githubusercontent.com/47353570/131342231-060871b9-37fc-448a-8abd-0865d4645439.png)

![image](https://user-images.githubusercontent.com/47353570/131342269-93158cc4-47bf-48c0-b133-cb90d32a7d5c.png)

![image](https://user-images.githubusercontent.com/47353570/131342496-97d961c2-c4ee-47b6-a797-16880fc87b68.png)

**Comment by AndreyDyakonov** [comment]
Checked
