### ISSUE TITLE
Change statuses text " ... max privacy" to "... maximum anonymity" and "... max privacy (offline)" to "... (offline)"

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#509]
Updated statuses https://zpl.io/b6xJ58q

1) All statuses with "... max privacy" should be with "... (maximum anonymity)" in brackets!
_E.g., status "in progress max privacy" become "in progress (maximum anonymity)"_

2) All statuses with "... offline" should be just "... (offline)"
_E.g., status "in progress offline" become "in progress (offline)"_

3) Update icons for all offline transactions. Now icons have a single line, not double as on maximum anonymity icons.

![image](https://user-images.githubusercontent.com/47353570/131500668-15a0bd72-e708-46a9-aa29-71b4cfbd60e2.png)

**Comment by AndreyDyakonov** [comment]
1. When we do maximum anonymity transaction to own address - status display incorrectly

in masternet:

https://user-images.githubusercontent.com/85252690/134469266-2d691915-f439-4f7a-9b5d-c7f42b477213.mp4

<img width="350" src="https://user-images.githubusercontent.com/85252690/134469298-d5e28a09-d490-46b1-9dc2-576c86536019.jpg">
<img width="350" src="https://user-images.githubusercontent.com/85252690/134469303-7176d2c4-1f23-4d83-a82d-9e9cb1442a59.jpg">

in design:


![2021-09-23_10-24-23](https://user-images.githubusercontent.com/85252690/134469389-5785b48b-ff18-4aa5-ac3f-d4801c277491.png)


2. When we do offline transaction to own address - arrow display incorrectly

in masternet:

<img width="350" src="https://user-images.githubusercontent.com/85252690/134469644-4fccf5cf-adab-4476-ac54-dcfcd0de5478.jpg">
<img width="350" src="https://user-images.githubusercontent.com/85252690/134469652-1857772e-53ae-4a02-b0b4-fb9206e34673.jpg">

in design:

![2021-09-23_10-24-58](https://user-images.githubusercontent.com/85252690/134469749-5ad04b49-da6b-4f6a-8c42-dc1ee4bd11a2.png)

3. Please rename status "cancelled" to "canceled" 

<img width="350" src="https://user-images.githubusercontent.com/85252690/134469970-9bd3ab6a-f71b-47fe-9dcd-244b17cea93d.jpg">

**Comment by AndreyDyakonov** [comment]
When we do maximum anonymity transaction to own address and transaction is failed - arrow display incorrectly

in masternet:
<img width="350" src="https://user-images.githubusercontent.com/85252690/135090990-82ef814c-9bad-459d-af99-9450f6ad92e1.jpg">

in design:
<img width="350" src="https://user-images.githubusercontent.com/85252690/135091113-f249d0a7-edc6-4f9f-a957-c1a8bf85c78a.jpg">

**Comment by AndreyDyakonov** [comment]
Checked
