### ISSUE TITLE
Able to create a password containing white spaces

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/ios-wallet#51]
**Bug description**
User can create a password containing white spaces.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start creating a new wallet.
2. Create and confirm the password: " " (a single white space).

**Current behaviour**
User gets no warnings. User is able to proceed to the next screen. 

**Expected behaviour**
User is not allowed to provide white space(s) as a password.

**Comment by Denis-Asipenko** [comment]
When entering current password in "Change password" screen user can enter a password containing white spaces.

**Comment by Denis-Asipenko** [comment]
checked
