### ISSUE TITLE
Update splash screen with new logo and graphics 

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#511]
**1. Splash screen**
Design: https://zpl.io/VDQlky3
https://zpl.io/bAwmkr6

**Changes:**
- Update logo to a new version
- Update background

![image](https://user-images.githubusercontent.com/7249484/131697428-7fbd758f-48ad-4a9a-b950-8677bf932791.png)
![image](https://user-images.githubusercontent.com/7249484/131697415-2f75d0a0-f8c2-4dc9-80e2-816531523916.png)

**2. Loading, syncing, creating wallet screens**
(goes after this task https://github.com/BeamMW/ios-wallet/issues/505)
Design: https://zpl.io/Vq4yZ0Y

**Changes:**
- Update logo to a new version

![image](https://user-images.githubusercontent.com/7249484/131624681-c26da4b3-7cc0-46e4-986e-17b4ba974ff5.png)

**Comment by AndreyDyakonov** [comment]
Need change background

in masternet:
<img width="350" src="https://user-images.githubusercontent.com/85252690/134473619-d67eea3b-7592-4d5e-91f0-35379c2b1c42.jpg">

in design:
<img width="350" src="https://user-images.githubusercontent.com/85252690/134473662-5f445b4c-02aa-4ce3-94f8-29c1fd0df326.jpg">

**Comment by AndreyDyakonov** [comment]
Checked
