### ISSUE TITLE
Change comment about exchange rate to USD

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#513]
In CA transaction details add secondary currency name in the comment about exchange rate to "USD exchange rate..." (or "BTC/ETH rate" depending on selected secondary currency).
The full text should be:
"(USD exchange rate was not available at the time of transaction)" or "(USD rate calculated with the exchange rate at the time of transaction)"
https://zpl.io/awwnrDn
https://zpl.io/2G5pml9

![image](https://user-images.githubusercontent.com/7249484/132647484-0a97a2d5-aff7-4347-9965-1f1e2307b133.png)

**Comment by Denis-Asipenko** [comment]
checked
