### ISSUE TITLE
DAPP Store

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#514]
DAPP Store screen 
https://zpl.io/aRKx4vr

There should be no "Add Dapp from a file/Uninstall Dapp" functionality on mobile yet.
![image](https://user-images.githubusercontent.com/7249484/133070953-555272ed-1e77-49f1-ae64-79f9a334c0f2.png)

**Comment by AndreyDyakonov** [comment]
Please change icon BeamX DAO and change signature  "LOCK SOME BEAM" to "Governance, staking and voting"

in masternet:
<img width="350" src="https://user-images.githubusercontent.com/85252690/134872632-61fc53b6-4e11-4653-b192-163d69725646.jpg">

in design:
<img width="350" src="https://user-images.githubusercontent.com/85252690/134872652-20c41805-53a7-4b65-a62a-4b88ba453c5b.jpg">

**Comment by AndreyDyakonov** [comment]
Checked
