### ISSUE TITLE
Rework side menu

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#515]
https://zpl.io/bLodq9Q

1. Update the logo
2. Move Setting to the bottom of the screen
3. Add separator line under Notifications

![image](https://user-images.githubusercontent.com/7249484/133067745-bc695b82-c955-4dec-8d6a-4defa4d2f8a6.png)

**Comment by Denis-Asipenko** [comment]
I think we need to make the placement of icons in the side menu the same as in the desktop wallet. This will simplify the work with the wallet, the user will intuitively understand where the icon is located that you need to tap to go to the screen he needs.
![image](https://user-images.githubusercontent.com/45556620/134341737-f836fbff-41a4-4103-8ca8-bc6a1c3e49ba.png)

**Comment by sasha-abramovich** [comment]
@Denis-Asipenko Consistency is important indeed, however, this is how the side menu looks in my Mainnet 6.1 wallet, which is fairly similar to the Mobile menu in this task (the Dao Core adding deserves a separate task):

<img width="97" alt="Screen Shot 2564-09-22 at 19 41 02" src="https://user-images.githubusercontent.com/44961099/134345294-074accb3-a0bc-4f12-8ff9-b0df3ce5a786.png">

**Comment by Denis-Asipenko** [comment]
@sasha-abramovich but this is a task for the wallet version 6.2. In the mobile wallet version 6.1, the side menu looks completely different than in the desktop wallet of the same version. I think if we have an intermediate version, for example 6.1.1, it makes sense to make a side menu like in the desktop wallet 6.1. But if we implement this task in 6.2, it will look like the mobile wallet is lagging behind the desktop one. I think that we can change a couple of icons if this task is implemented in version 6.2 for the mobile wallet.

**Comment by Denis-Asipenko** [comment]
Discussed with @sasha-abramovich and it was decided in 6.2 to make the placement of icons in the side menu, as in the desktop wallet 6.2

**Comment by AndreyDyakonov** [comment]
Checked
