### ISSUE TITLE
Add DAPP Store icon to sidemenu

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#516]
Add Dapp Store icon https://zpl.io/bW7NG31
The inactive state of the icon is here https://zpl.io/25mJzmW
![image](https://user-images.githubusercontent.com/7249484/133068185-dfbb1fe0-a87e-4306-bfeb-2213b1496cc4.png)

**Comment by AndreyDyakonov** [comment]
Checked
