### ISSUE TITLE
Add BeamX DAO icon to sidemenu

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/ios-wallet#517]
Add BeamX DAO icon https://zpl.io/25mJzmW 
The inactive state of the icon is here https://zpl.io/bW7NG31
![image](https://user-images.githubusercontent.com/7249484/133068100-97a9b963-5677-4b3a-a3d1-17d624f3ac33.png)

**Comment by AndreyDyakonov** [comment]
Checked
