### ISSUE TITLE
Rework set password  screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#527]
Currently, the order and the grouping of fields when setting the password is not very intuitive. Therefore, let's make it better:

1) Empty password fields https://zpl.io/bJd48e9

- replace line input field with box input field
- place the password requirement below the password and it's confirmation.
- button inactive
- make 10% opacity (instead of 5%) on focused field (as on "Password" field)
- make title in caps
![image](https://user-images.githubusercontent.com/47353570/134180203-bf70ef92-4b2b-409e-8d87-3c35f43b61ca.png)

2) Password filled, confirmation - error https://zpl.io/bAwpxre

- make box in red color (oppacity 15%)
- button inactive because of error
- add error text
![image](https://user-images.githubusercontent.com/47353570/134180362-5e759cec-95fa-4eb4-88e8-694eeb1f0f83.png)

3) Password filled and confirmation correct https://zpl.io/VDQ9Njl
- button active
- add "eye" icon only on the focused field.
![image](https://user-images.githubusercontent.com/47353570/134180423-1b1603e2-410f-4c3f-bdd3-ca34638b5361.png)

- show password "eye" icon https://zpl.io/amxNLLK
![image](https://user-images.githubusercontent.com/47353570/134180624-3f60077e-e804-4195-a514-105f36d2518d.png)

**Comment by AndreyDyakonov** [comment]
Checked
