### ISSUE TITLE
Rework "Change password" in Settings

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#528]
1)  Place fields "Current password", "New password" and "Password confirmation" on one screen. https://zpl.io/boDgkdW
![image](https://user-images.githubusercontent.com/47353570/134400804-4bc3fc6b-2bc5-46ca-b3a0-9c03ca962631.png)

2) Make titles in CAPS. 
![image](https://user-images.githubusercontent.com/47353570/134399059-6b17441a-1e08-4d77-829d-9ad34235db76.png)

3) Filled and focused fields https://zpl.io/ad1vBwL
Show "eye" icon only on focused field.
![image](https://user-images.githubusercontent.com/47353570/134399111-393b87c9-bfd9-40ea-abe6-0dfd3d8ab7b2.png)

4) Confirmation error https://zpl.io/Vxqe9ZW
![image](https://user-images.githubusercontent.com/47353570/134399279-65fea35c-278a-4e6a-b7fa-0c295fadc7fd.png)

5) Password strength should be displayed after password's fields

Current implementation.
![IMG_3212](https://user-images.githubusercontent.com/47353570/134183608-bef20614-c428-458e-8350-a69a872ecb78.PNG)
![IMG_3213](https://user-images.githubusercontent.com/47353570/134183621-85b6b7b4-c2cb-4402-8710-33202ccd9cd8.PNG)

**Comment by AndreyDyakonov** [comment]
1. Please change "OLD PASSWORD" to "CURRENT PASSWORD"

in masternet:
<img width="350" src="https://user-images.githubusercontent.com/85252690/135268673-40d68f0c-af2e-4cea-af90-9a29249fb44c.jpg">

in design:
<img width="350" src="https://user-images.githubusercontent.com/85252690/135268790-e4274354-7d03-45ce-80f8-14a5611a3b5a.png">

2. Showed "eye" icon only on "NEW PASSWORD" field, not in all focused field

https://user-images.githubusercontent.com/85252690/135269250-1bfe0687-a8bc-47e4-a93f-8fb570792cfa.mp4

**Comment by AndreyDyakonov** [comment]
Checked
