### ISSUE TITLE
Move "Remove current wallet" to Utilities

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#529]
1) Remove "remove current wallet" from main Settings screen https://zpl.io/agOj879
![image](https://user-images.githubusercontent.com/47353570/135055596-7c086bb0-e2bd-44c5-8088-29434c1d187e.png)

2) Place "remove current wallet" in Utilities settings https://zpl.io/2p75y1M
![image](https://user-images.githubusercontent.com/47353570/135301245-0c26315f-8dd7-45c9-8b70-e2c24458edfc.png)

Dialogs with confirmation and password leave as they are. https://zpl.io/a3dx6mW and https://zpl.io/bADnlvo

**Comment by AndreyDyakonov** [comment]
Checked
