### ISSUE TITLE
Blockchain status - not friendly view

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#53]

**Comment by kaminskyelina** [comment]
![IMAGE 2019-03-21 11:19:47](https://user-images.githubusercontent.com/45590119/54742878-3cae2200-4bcb-11e9-9b94-b3b7888cc569.jpg)

**Comment by kaminskyelina** [comment]
Alexandra would like to change to the following:

![Uploading IMAGE 2019-03-21 11:22:56.jpg…]()

**Comment by Denis-Asipenko** [comment]
checked
