### ISSUE TITLE
Add search to Settings

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#530]
1) Add Search field only to main Settings screen https://zpl.io/anvvwBA
![image](https://user-images.githubusercontent.com/47353570/136403485-231a7653-de19-4a1d-b48d-53b756fb05eb.png)

2) Search result highlight with blue color https://zpl.io/VDQQeQg
![image](https://user-images.githubusercontent.com/47353570/136403591-f37590f7-27bf-44ea-950a-28731c92003e.png)

3) Search by 

3.1) setting title (notifications, privacy, utilities,. etc - I guess this is relevant only for node.. but if user wants to search "privacy" let's show it as result also)
![image](https://user-images.githubusercontent.com/47353570/136404520-9f46aaf7-74ab-4816-a59e-f547fcca0ec9.png)

3.2) parameters titles (show amounts in, minimum confirmations, ask for password, show utxo etc)
![image](https://user-images.githubusercontent.com/47353570/136404455-fe9f2f91-fbf5-4a6b-8042-cffd478f421d.png)

3.3) parameters value that set 
![image](https://user-images.githubusercontent.com/47353570/136404392-23197c78-e46b-4bf9-85c5-e80009a607ab.png)

4) Search by setting title and parameter https://zpl.io/brKKdmr
![image](https://user-images.githubusercontent.com/47353570/136405111-a6f9ef92-8a3c-47ed-97f2-50f6ed1719ef.png)

5) Search by parameter https://zpl.io/VDQQeQg
![image](https://user-images.githubusercontent.com/47353570/136405184-edc7750b-7f93-4c5b-a392-146570dcab60.png)

6) Search by parameter value https://zpl.io/bPNNwrA
![image](https://user-images.githubusercontent.com/47353570/136405337-d0a806d4-a3e0-48bc-8b41-e3a2dcf31352.png)

7) No results. If user search by parameter value that not set https://zpl.io/bAwweqx
![image](https://user-images.githubusercontent.com/47353570/136405462-004dc2c8-87a1-41bd-8fbd-0c93997733e5.png)

8) From the search results screen user go to the inner screen (in this case it is a node). Then when he wants to get back and click the arrow it goes to the search results screen back. This is the original iOS flow.
![image](https://user-images.githubusercontent.com/47353570/136405947-ad66520f-167d-472d-b3ba-a0491c8fb350.png)

**Comment by AndreyDyakonov** [comment]
1. If the search did not give results, please add a picture with a description as in the design

![photo_2022-03-23_14-54-55](https://user-images.githubusercontent.com/85252690/159694241-7df536fa-8e8f-4618-b997-ed765dc83722.jpg)

2. This does not apply to this task, but please move the version number in "settings" to the bottom edge

![photo_2022-03-23_14-54-52](https://user-images.githubusercontent.com/85252690/159696650-decadf83-ff18-434e-a978-a49898ebf1d0.jpg)

**Comment by AndreyDyakonov** [comment]
Checked
