### ISSUE TITLE
Add "Open the DAPP" action for transaction

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#536]
1) Add "open the DAPP" to actions https://zpl.io/25mL8Bn
![image](https://user-images.githubusercontent.com/47353570/135298061-6f64f8b1-32ec-47a9-8a28-d2fa8910eae7.png)

2) Action leads to the DAPP itseld (e.g fauset https://zpl.io/bzOro3G )

3) If DAPP was removed display popup https://zpl.io/bzOro3G
![image](https://user-images.githubusercontent.com/47353570/135098843-72d86166-48cc-4ac1-a111-2c6e9143ea52.png)

4) Also add "open the DAPP" to long tap actions https://zpl.io/ag5j07M
![image](https://user-images.githubusercontent.com/47353570/135298119-6169b5f8-ffa2-4b17-a13b-84e434d70e8c.png)

**Comment by AndreyDyakonov** [comment]
Checked
