### ISSUE TITLE
Addresses - display addresses in a new format

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/ios-wallet#539]
Сurrently SBBS addresses are displayed in the address book in the address field. We need to display addresses in a new format like it is in a desktop wallet.
- **Addresses of the new format are used and saved if the user is connected to own node or mobile node.**
- **If the user is connected to a remote node, then only the SBBS address is used, respectively, the SBBS address will be stored in the Addresses.**
- Addresses in the new format should be displayed on the **"my active","my expired",and "contacts"** tabs.
- When a user shares an address, the address must be in a new format.
- SBBS address should only be displayed on the receive screen in "address details"
- In the address details, change the " signature" to " wallet signature".

Сurrent:
![image](https://user-images.githubusercontent.com/45556620/135284967-92295ef5-7ccf-49c9-8510-76967a251133.png)

**Comment by AndreyDyakonov** [comment]
Checked
