### ISSUE TITLE
 Change the address type from "maximum privacy" to "maximum anonymity" for maximum anonymity transactions.

### ISSUE THREAD

**Issue by AndreyDyakonov** [BeamMW/ios-wallet#544]
Please change the address type from "maximum privacy" to "maximum anonymity" for maximum anonymity transactions
- sent transaction (tx info - "General" and "Payment proof" tabs)
- sent to own address (tx info)
- received transaction (tx info)
- send screen (confirmation) 

![333](https://user-images.githubusercontent.com/85252690/136174176-fb790a40-a41b-49b8-9955-396b88fba2a1.png)

**Comment by AndreyDyakonov** [comment]
Checked

**Comment by Denis-Asipenko** [comment]
![telegram-cloud-photo-size-2-5397827740297704741-y](https://user-images.githubusercontent.com/45556620/136212675-eb070fc2-dd9e-403c-aab9-8144b47e63ec.jpg)
