### ISSUE TITLE
Rework search results design

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#545]
1) Highlight with blue color #543 
2) Update design of search results: add separator, make titles in caps (as on transaction details screen) https://zpl.io/brPoEm7 
![image](https://user-images.githubusercontent.com/47353570/136401974-e16f33dc-c8fb-4e37-b38c-e49f5f0fb2bb.png)

3) Search by name https://zpl.io/V0Nzo7E
![image](https://user-images.githubusercontent.com/47353570/136402029-b66e3860-7c5e-4c42-b652-b3ad0756a83b.png)

4) If no search results display text "There are no transactions matching search criteria", instead of "Your transaction list is empty" https://zpl.io/2pNg33y
![image](https://user-images.githubusercontent.com/47353570/136402253-8668e0c8-11b3-49dc-8376-b49d8a19d60c.png)

Current design:
![image](https://user-images.githubusercontent.com/47353570/136276811-6ad0730c-0ec6-40a2-b0b4-89902fea8ba9.png)

**Comment by AndreyDyakonov** [comment]
1. Please move the "comment"(description) above the separator as it is included in the basic information block

<img width="350" src="https://user-images.githubusercontent.com/85252690/153372945-e92a5c94-2fa7-4fc8-aa2a-ae0835473df7.jpg">

2. Please move the transaction ID under the field name

in master:
<img width="350" src="https://user-images.githubusercontent.com/85252690/153380637-06dbc10e-8220-4b06-baa7-431d377c747b.jpg">

in design:
<img width="350" src="https://user-images.githubusercontent.com/85252690/153380669-da985a91-7815-4e2a-8c18-92fae80fb831.jpg">

3. Please in the search result remove the ":" icon after the fields (tx id, sending/receiving address, kernel id ...)

<img width="350" src="https://user-images.githubusercontent.com/85252690/153382374-beea0658-2214-4caf-91ac-3e7b9667ac89.jpg">

**Comment by AndreyDyakonov** [comment]
Checked
