### ISSUE TITLE
Display how much funds receiver gets via online and offline transactions

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/ios-wallet#557]
1) For **online** transactions add info how much funds will get the recipient (after fees). https://zpl.io/25ljoGn
![image](https://user-images.githubusercontent.com/47353570/144095060-3aaf8971-d00d-441a-9caa-d5e5c34275be.png)

2) For **offline** transactions add info how much funds will get the recipient (after fees). https://zpl.io/VK3BQDR
![image](https://user-images.githubusercontent.com/47353570/144095153-55c1d12d-603f-4fd5-a0a7-62cb1579e3f6.png)

3) For **Max anonymity** transaction add info how much funds will get the recipient (after fees). https://zpl.io/bA3KDlq
![image](https://user-images.githubusercontent.com/47353570/144095297-3672095a-d487-4db5-9d5f-93281b32ece6.png)

4) For **Public offline** transaction add info how much funds will get the recipient (after fees). https://zpl.io/2E38xRl
![image](https://user-images.githubusercontent.com/47353570/144095454-25a8dd38-d15e-4ccb-a159-bb84f3241307.png)

5) Please add separator lines after "transaction type" and before "recipient will receive" https://zpl.io/2E38xRl
![image](https://user-images.githubusercontent.com/47353570/144095626-1280adb1-5d2f-47f7-9e74-15ff3871e5fc.png)

**Comment by gingervik** [comment]
irrelevant as receiver will get all amount. fee is taken from sender's
