### ISSUE TITLE
Implement Addresses for iOS

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#57]

**Comment by alexandrashelenkova** [comment]
@kaminskyelina  address screens are here https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5c9a1124c2d2d2052d550aed

**Comment by Denis-Asipenko** [comment]
The additional menu doesn't correspond to design.
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5c9a06898aaf5905283bdd64
![image](https://user-images.githubusercontent.com/45556620/55144582-3501f680-5152-11e9-94db-86aa89aae19a.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/55144666-64b0fe80-5152-11e9-9ce5-b40558149d45.png)
As well need to add a "Contact" tab in "Addresses" screen.
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5c9a0688d12e87057b5036f6
![image](https://user-images.githubusercontent.com/45556620/55145024-06d0e680-5153-11e9-87a0-4e6ed126bf94.png)

**Comment by alexandrashelenkova** [comment]
Actions menu should be same as here zpl.io/VDB3K7W
That is more ios way, drop down menu from top bar is android way.

**Comment by Denis-Asipenko** [comment]
checked
