### ISSUE TITLE
Send screen - incorrect display of fees and amounts in the error message under the "amount" field.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/ios-wallet#570]
**Bug description**
The send screen displays an incorrect fee amount:
-  with a zero balance the correct fee amount is 0.001 beam
![image](https://user-images.githubusercontent.com/45556620/162416765-148f13f9-0450-4609-a35c-874e325c7f94.png)

- if the user enters an amount exceeding the amount on the balance, then it is necessary to show him a message that **the maximum amount is** xxxxxx(balance amount - transaction fee = the maximum amount is), regardless of what amount the user entered (the difference...we don't show how much user needs to add)

https://user-images.githubusercontent.com/45556620/162421215-c8152ee4-7ecc-4a05-81ec-f5a16a3e4392.mp4

https://user-images.githubusercontent.com/45556620/162421250-76b45920-e9c7-40aa-b8e5-c6907559b749.mp4

**Comment by AndreyDyakonov** [comment]
Incorrect display the error message with a zero balance
(the message says that the maximum amount available is greater than 0)
<img width="450" src="https://user-images.githubusercontent.com/85252690/162914828-f6203597-21b4-4940-a8c1-9ae5c34ee163.jpg">

for example desktop 


![2022-04-12_11-15-40](https://user-images.githubusercontent.com/85252690/162914940-4667c6a8-9b86-45ca-b3bf-93200feaf93c.png)

**Comment by AndreyDyakonov** [comment]
Checked
