### ISSUE TITLE
Invalid address in push notification

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/ios-wallet#571]
**Bug description**
After the transaction has been received by the recipient, the sender receives a push notification. This push notification specifies an incorrect address, i.e. not the recipient's address, but the sender's address.
**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/45556620/168560599-03ddaed6-c762-47d1-9595-efa332e9b090.png)
![image](https://user-images.githubusercontent.com/45556620/168560629-57ac676a-19e6-4fdd-a75b-4aab9c226d5d.png)

**Comment by AndreyDyakonov** [comment]
It is not fixed 
In notification needed display receiving address (not sending address)

![photo_2022-06-06_17-01-53](https://user-images.githubusercontent.com/85252690/172176820-d0e00c3e-466b-4cc2-acfc-5ec979d3a589.jpg)

**Comment by AndreyDyakonov** [comment]
Checked
