### ISSUE TITLE
Restore Wallet (automatic)

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#6]

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova please attach screenshots

**Comment by alexandrashelenkova** [comment]
Screens are here: https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5c9076beea78dc066b914539

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova let's talk we need more functionality here: there should be 2 options for restore:
* automatic, where wallet will download blockchain files from Beam storage somewhere in the cloud
* advanced, where wallet will be able to connect to the trusted node that will supply the files

**Comment by alexandrashelenkova** [comment]
Added missing screens here and updated old ones https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5d19f974160fa1aff5706f5d

**Comment by Denis-Asipenko** [comment]
design:
![image](https://user-images.githubusercontent.com/45556620/62125531-11a0b100-b2d6-11e9-9c6e-eaf2d794d464.png)
actual:
![image](https://user-images.githubusercontent.com/45556620/62125553-23825400-b2d6-11e9-8ca2-b6c65d53e268.png)
words are not removed when you use the quick delete " X"
[video_2019-07-30_14-25-54.zip](https://github.com/BeamMW/ios-wallet/files/3446573/video_2019-07-30_14-25-54.zip)
Need to replace the loading screens in accordance with the design
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5c751b6726c62e6244b010ba
![image](https://user-images.githubusercontent.com/45556620/62125937-35b0c200-b2d7-11e9-8448-35e09d531926.png)
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5d1ad7c6384819076e3b61c4
![image](https://user-images.githubusercontent.com/45556620/62125964-495c2880-b2d7-11e9-8e8b-22f5ced89b8e.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/62126066-95a76880-b2d7-11e9-911e-6e0bd6f55827.png)
![image](https://user-images.githubusercontent.com/45556620/62126127-b374cd80-b2d7-11e9-9dc4-f9c2751e2c38.png)

**Comment by Denis-Asipenko** [comment]
without filling in the seed phrases, you can go to the password creation screen and eventually create a wallet.
[video_2019-07-31_15-30-55.zip](https://github.com/BeamMW/ios-wallet/files/3451802/video_2019-07-31_15-30-55.zip)

**Comment by Denis-Asipenko** [comment]
checked
