### ISSUE TITLE
QR code not readable by Android

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#60]
Scan QR code from Receive screen by Android fails
*Scan QR from Desktop OK

Seems like the problem with QR on iOS

**Comment by DenisDemyanko** [comment]
@kaminskyelina 

This is not an iOS error
I can scan the code using the android application. 
Possible error in the android scanner

![IMG_3192 copy](https://user-images.githubusercontent.com/11455593/54917980-b87ad800-4f05-11e9-8c53-3c633c449e32.jpg)

**Comment by Denis-Asipenko** [comment]
Android scans QR code IOS wallet.
