### ISSUE TITLE
Encode the object type / protocol into QR code

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/ios-wallet#62]
So that our users:
- Will get an error when trying to scan this code from another app
- Will open Beam Wallet automatically (if installed) when OS-level scanning will happen

**Comment by kaminskyelina** [comment]
New format:
beam:12d1a5d6dc54af1792dc67325aeb274c38c36e005c730b964e978f0d3afdfddbc26?amount=12.102

Must: read old formats

**Comment by Denis-Asipenko** [comment]
about design: just add field "Transaction amount" above field "Comment" (like in desktop version)
![image](https://user-images.githubusercontent.com/45556620/57133962-293acd00-6dad-11e9-95f1-1ad41f1a8cd8.png)

**Comment by DenisDemyanko** [comment]
> about design: just add field "Transaction amount" above field "Comment" (like in desktop version)
> ![image](https://user-images.githubusercontent.com/45556620/57133962-293acd00-6dad-11e9-95f1-1ad41f1a8cd8.png)

@Denis-Asipenko Hi. But in the mobile design this field should be on top. Please check https://zpl.io/anpJOmr

@sasha-abramovich Tell me where the field should be?

**Comment by sasha-abramovich** [comment]
Should be named "Receive" amount on every platform. And the design https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5c73e6ed1896bf1a964c4fe4 looks right.

not sure what is the question is

**Comment by sasha-abramovich** [comment]
BTW, in desktop it's here: https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5bd18f9c140d6a09ac8bd6dd
(also called "Receive amount", FYI: @gingervik @Sergei-Beam)

**Comment by Denis-Asipenko** [comment]
On receive screen max Transaction amount which user can enter should be <=262,800,000

**Comment by Denis-Asipenko** [comment]
checked
