### ISSUE TITLE
Proof of Payment for iOS

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#63]

**Comment by alexandrashelenkova** [comment]
Screens are here https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5ca1ac27163c972ad46ebf27
zpl.io/VDB1y8v
zpl.io/2v7LAEe

**Comment by Denis-Asipenko** [comment]
The “Copy” button should function as a "copy code" button.
Code verification doesn't work.
![image](https://user-images.githubusercontent.com/45556620/55404874-90245680-5561-11e9-88a5-2d8f21f279f2.png)
![image](https://user-images.githubusercontent.com/45556620/55404920-aa5e3480-5561-11e9-9849-657685baa42d.png)

**Comment by Denis-Asipenko** [comment]
checked
