### ISSUE TITLE
Cannot Login in Flight Mode

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#67]
Cannot Login in Flight Mode

**Scenario**
Enable Flight Mode
Open Beam Wallet
Login

**Result**
Error - no internet connection

**Expected result**
Login offline

**Comment by kaminskyelina** [comment]
According to @Denis-Asipenko  we should not login
In Android and Desktop the wallet just stacked in login, here we have "no internet" error
The solution should be the same for all platforms

**Comment by Denis-Asipenko** [comment]
We should not login in wallet when connecting to random node.
When the user tries login in wallet need a message of error.
