### ISSUE TITLE
Settings- Implement Change Password

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#71]
@alexandrashelenkova  - Settings screen is missing in the design
for now implemented - send logs and version in settings screen

**Comment by alexandrashelenkova** [comment]
Settings screen is here zpl.io/25OMeK8
Changing password screens are here
zpl.io/VDBRDyJ
zpl.io/boDgkdW

**Comment by Denis-Asipenko** [comment]
1. Display is incorrect password  only after tap button "next". Text when entering an incorrect password: 
- The old password you have entered is incorrect.
Actual:
![image](https://user-images.githubusercontent.com/45556620/55622855-06b39500-57aa-11e9-96f1-a4b953d944cf.png)
2. New password cannot be old. Text a message error:
- New password cannot be the same as old. 
3. If the password is not entered in fields "password" and "confirm password"  must be displayed an error message:
-  Password should not be empty.
Message and fields must be red in colour at this moment. 
Actual:
![image](https://user-images.githubusercontent.com/45556620/55623623-45e2e580-57ac-11e9-87de-36ad0c8ee365.png)
Create new password screen- when you click the back arrow we have to return to the previous screen.
Actual: Return to the setting screen.

**Comment by DenisDemyanko** [comment]
@Denis-Asipenko  
_Create new password screen- when you click the back arrow we have to return to the previous screen.
Actual: Return to the setting screen._

**Why go back to the password entry screen?**

**Comment by DenisDemyanko** [comment]
Please check 1.0.2(7) version

**Comment by Denis-Asipenko** [comment]
Discussed to @alexandrashelenkova  and solved this scenario doesn't suit us-"Create new password screen- when you click the back arrow we have to return to the previous screen."
However, the error messages need to be done as in my comment above.
_Display that the password is incorrect only after tap button "next". Text when entering an incorrect password:
**The old password you have entered is incorrect**._

**Comment by Denis-Asipenko** [comment]
checked
