### ISSUE TITLE
Contact is not shown in UTXO details

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#72]
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5c8cc174ed2b7b0dcb1a41cb
![image](https://user-images.githubusercontent.com/45556620/55391468-17fa6880-5542-11e9-8711-4b09706bbcb6.png)

**Comment by Denis-Asipenko** [comment]
invalid
