### ISSUE TITLE
Forgot Password (Depends in Restore functionality)

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#77]
Design and Spec are needed

(Related to BeamMW/beam#165)

"Forgot password" button should lead to the restore flow.

**Comment by Denis-Asipenko** [comment]
Crash app.
Steps to reproduce the behaviour:
Wallet installed and created. Wallet is closed.
1. Open wallet.
2. At authorizations screen select "Forgot password?"
3. Click "OK" button in "Restore wallet" window.
4. From "Seed phrase" screen return to authorizations screen.
4. Again at authorizations screen select "Forgot password?"
5. Click "OK" button in "Restore wallet" window.
Expected: open "Seed phrase" screen.
Actual: crash app.

**Comment by DenisDemyanko** [comment]
@Denis-Asipenko 

I can not reproduce, also I do not see any crashes in the Fabric.
Please try again and let me know.
Thx!

**Comment by DenisDemyanko** [comment]
Please check 1.0.2(7) version

**Comment by Denis-Asipenko** [comment]
Doesn't match the design.
Design:
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5cac8491a4d3efa2651561cd
![image](https://user-images.githubusercontent.com/45556620/55798556-ea7c6480-5ad7-11e9-9480-badf2265199d.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/55798952-da18b980-5ad8-11e9-8e9a-9f8cea967bf1.png)

Design:
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5c751b6726c62e6244b010ba
![image](https://user-images.githubusercontent.com/45556620/55798593-0122bb80-5ad8-11e9-8ffe-0b7f26ec07de.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/55798936-cec58e00-5ad8-11e9-944f-486e3cdac4ab.png)

version 1.0.2(8)

**Comment by Denis-Asipenko** [comment]
checked

**Comment by kaminskyelina** [comment]
Forgot password removed from design
