### ISSUE TITLE
Ask for password on every Send

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#78]
Design is missing for iOS

**Comment by kaminskyelina** [comment]
@alexandrashelenkova Alexandra, we need design for the switcher of password request in Settings screen and Send screen also please

**Comment by alexandrashelenkova** [comment]
Password screen is here 
zpl.io/bljRrLD
Settings screen is here 
zpl.io/25OMeK8

**Comment by Denis-Asipenko** [comment]
Doesn't correspond to design.
Actual:
![image](https://user-images.githubusercontent.com/45556620/55627045-e2f64c00-57b5-11e9-978a-c7a6c841fece.png)
design:
![Screenshot_53](https://user-images.githubusercontent.com/45556620/55627061-eb4e8700-57b5-11e9-8570-d8e1932110ee.png)

**Comment by DenisDemyanko** [comment]
Please check 1.0.2(7) version

**Comment by Denis-Asipenko** [comment]
checked
