### ISSUE TITLE
Hide Balance when sending money face-2-face

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#83]
Use case: Hide amounts when sending money face-2-face

- Default is unlocked 
- Enable/Disable in any time in screen that shows balance (Main and Send) 
- Hide balance only everywhere
- Аfter button toggle - back to regular view
- After wallet reset - back to default (unlocked)

**Comment by alexandrashelenkova** [comment]
Screens are here
zpl.io/VqWLnGl
zpl.io/bPxdmKL
zpl.io/2vOlWvr
zpl.io/am5eWz6
zpl.io/bLdOdZ6

**Comment by kaminskyelina** [comment]
What was decided about Receiver, we don't hide anything? @alexandrashelenkova

**Comment by alexandrashelenkova** [comment]
Decided not to hide transaction history at all, only balance

**Comment by alexandrashelenkova** [comment]
Decided with Sasha that secret mode won't affect utxo screen by now, links on screens are above

**Comment by Denis-Asipenko** [comment]
@alexandrashelenkova  this information isn't about the user's balance?
![image](https://user-images.githubusercontent.com/45556620/56418429-93c51680-629f-11e9-8335-ee57ccdbf497.png)
And this information isn't about the user's transaction history? 
![image](https://user-images.githubusercontent.com/45556620/56418612-1a79f380-62a0-11e9-8afc-12a24d5e016d.png)

**Comment by alexandrashelenkova** [comment]
@Denis-Asipenko yes :)

**Comment by Denis-Asipenko** [comment]
checked
