### ISSUE TITLE
UTXO details

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#9]

**Comment by Denis-Asipenko** [comment]
does not match the design.
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5bfa78ff92d01e7ea2aa7391
![image](https://user-images.githubusercontent.com/45556620/54920846-59bd5a80-4f15-11e9-9517-77cf2fc9a106.png)
![image](https://user-images.githubusercontent.com/45556620/54920818-43af9a00-4f15-11e9-8ba9-4e76121646cf.png)

**Comment by Denis-Asipenko** [comment]
checked
