### ISSUE TITLE
Export transaction history to the file

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#94]
Export in CSV format, according to the order that in the wallet
Share via share menu
Save file

**Comment by alexandrashelenkova** [comment]
Added on transaction's actions dialog here zpl.io/2v7LAEe

**Comment by Denis-Asipenko** [comment]
Please, add what is marked red on a screenshot.
![image](https://user-images.githubusercontent.com/45556620/56274641-c805cf00-6107-11e9-8f38-ea2db371b364.png)
In name, file add transactions_#timestamp#.csv

**Comment by Denis-Asipenko** [comment]
checked
