### ISSUE TITLE
Show total available balance when sending Beam

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#95]

**Comment by Denis-Asipenko** [comment]
Doesn't match to design.
design:
![image](https://user-images.githubusercontent.com/45556620/56279236-6c8c0f00-6110-11e9-8ab4-e32724745f41.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/56279516-f6d47300-6110-11e9-80c7-4fd7004b4945.png)

**Comment by Denis-Asipenko** [comment]
checked
