### ISSUE TITLE
Autocompletion of seed phrase (after 4 chars)

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#97]
1. Once user started to print the word (after 4 chars) - suggest completion option
2. User should tap on suggested word, if he does so, so the cursor jumps to the next word
3. On the last word the cursor doesn't jump
4. If user doesn't tap on suggested word , the cursor will not jump, he will need to move to next tab manually

**Comment by kaminskyelina** [comment]
What happens with short words? (3-4 chars) @alexandrashelenkova

**Comment by Denis-Asipenko** [comment]
checked
